### ISSUE TITLE
gamelist.xml-error

### ISSUE THREAD

**Issue by TobiasKoller** [muldjord/skyscraper#1]
hi,
your tools is really great!!
I just tried it out and it works great.

But I found a little bug in the gamelist.xml-file.
It seems that you are not replacing special XML-characters in the author-tag.

Look at the & in this example:

`<developer>Nintendo R&D1</developer>`

![xml-parse-error](https://user-images.githubusercontent.com/15647346/28497607-baf34be0-6f8b-11e7-9eb9-6fda5570fb89.PNG)

**Comment by muldjord** [comment]
Thank you for reporting this. I completely revamped the xml escaping. This should no longer be an issue.

Fixed in the just released 1.1.8 :) Enjoy!
