### ISSUE TITLE
First-run Simple Mode -- very minor issue

### ISSUE THREAD

**Issue by daftinquisitor** [muldjord/skyscraper#10]
Probably no more than a minor annoyance here, but just wanted to make mention. Ran Skyscraper setup in Simple Mode. The very last question it asks is, "Do you want to run it now? (Y/n)?"

Typing in "Y" resulted in the message "User chose not to run script, now exiting..."

Again, not a huge issue since it printed the path and I knew where to go to to run it, but should probably check that last choice to see if it was coded backwards or something.

**Comment by muldjord** [comment]
It's all in the little things. Normally I would assume users answered "y" and not "Y". Y is just uppercase to signify that it's default. But I will change it to also accept "Y".

As a workaround, just answer "y" or merely press enter, which defaults to "y".

**Comment by daftinquisitor** [comment]
Honestly, I just typed it as it appeared on screen. :p
