### ISSUE TITLE
MAME ROM subdirectory parsing

### ISSUE THREAD

**Issue by RDBowers** [muldjord/skyscraper#102]
I am using Skyscraper 2.9.5 with the latest version of RetroPie-Setup script version 4.4.4.
I have my MAME ROMs sorted into subdirectories based on their genre under the subfolder \\RETROPIE\roms\mame-libretro\. The only exception is the first subfolder .\A-Top100\
 which contains duplicate ROM sets of my favorite arcade games.

The subdolders are,
.\A-Top100\
.\B-BeatEmUp\
.\C-Climbing\
.\D-Driving\
.\E-Puzzle\
.\F-Fighter\
.\G-Multigame\
.\I-Pinball\
.\K-Ball-Paddle\
.\L-Lightgun\
.\M-Maze\
.\N-MiniGames\
.\O-Sports\
.\P-Platform\
.\Q-Quiz\
.\R-Rhythm\
.\S-Shooter\
.\T-Tabletop\
.\U-Uncategorized\
.\X-Mature\

I can scrape from the online sources and then scrap the LocalDB cache to generate the screenshots and gamelist.xml, but I have noticed two issues.

1. If their are no ROM files in the emulator base \\RETROPIE\roms\mame-libretro\ folder, Skyscraper ignores the emulator ROM folder and doesn't look into the subfolders. I have been able to trick Skyscraper into checking the subfolders by including at least one ROM file in the emulator base ROM folder. It would be nice if Skyscraper would automatically check subfolders in the emulator base ROM folder if they are present.

2. The path address in the generated gamelist.xml folder is incorrect. The generated file has
`<game>
    <path>./1943.zip</path>
    <name>1943: Counter Attack (World 900227)</name>
    ...
</game>`
Based on my subfolder structure the path statement should be, 
    <path>./S-Shooter/1943.zip</path>

All other fields appear to be correct.

**Comment by RDBowers** [comment]
I am not sure but I would expect yes. I am using whatever defaults apply using the RetroPie setup module.

**Comment by muldjord** [comment]
1. Just had a look at this, and Skyscraper *does* look into the subfolders even if there are no roms located in the inputFolder for roms. I have no idea why this doesn't work for you. I just tested it with your exact use case (for "mame-libretro") and it works just fine with only having roms in subfolders. Not sure how to fix this as I can't recreate it. If you have more info on how to recreate this issue, please let me know.

2. Just fixed this. It will be in 3.0.0.

**Comment by RDBowers** [comment]
I did further testing and found Skyscraper requires a least one file in the \\RETROPIE\roms\mame-libretro folder to allow Skyscraper to recognize the ROMs in subfolders. 

I did a test with no files in the base emulator ROM folder and Skyscraper didn't recognize it. I then created a blank text file, called it temp.txt and Skyscraper would then scrape the ROMS in subfolders.

Hope this helps you recreate the issue.

**Comment by muldjord** [comment]
EDIT: Ah, now I know why. This is not a Skyscraper issue, it's an issue with the check mitu does in his RetroPie-Setup script. It must check whether the folder is empty before it issues the Skyscraper command. And it's the script that needs the file, not Skyscraper.

I've reported the issue to the script maintainer. Closing this now.

**Comment by RDBowers** [comment]
Makes sense. Thanks for resolving.
