### ISSUE TITLE
Fail gracefully when running out of storage

### ISSUE THREAD

**Issue by dominicdoty** [muldjord/skyscraper#104]
**Describe the feature**
Skyscraper should fail gracefully when running out of storage on the system. Ideally it would stop the scrape and inform the user, but even just checking at the end of the scrape and informing the user then would be helpful.

**Additional context**
I noticed while doing a scraping run that I would intermittently get errors from libpng. Unfortunately I didn't write down the specific error, but it was something like "libpng error: write error".
After the run, none of the media was updated in ES. In the process of trying to discover the cause of this, I noticed I had run out of space on my SD card, which seemed to be the source of the libpng error, and the images not showing up in emulation station.

**Comment by muldjord** [comment]
I actually already fixed this a week ago in the upcoming 3.0.0 release. I'll leave this open so others can see it until 3.0.0 is released.

**Comment by dominicdoty** [comment]
Excellent! Thank you for all your work on this. The software is outstanding!

**Comment by muldjord** [comment]
Glad you like it! :)

**Comment by muldjord** [comment]
3.0.0 now out where this is fixed. :)
