### ISSUE TITLE
https://github.com/muldjord/skyscraper/archive does not exist. Requested by install script

### ISSUE THREAD

**Issue by micbuffa** [muldjord/skyscraper#105]
Hi! I followed the instructions for getting and updating skyscraper. In the update_skyscraper.sh script, there is this command that fails : 

```
echo "--- Fetching Skyscraper v.${LATEST} ---"
    wget -N https://github.com/muldjord/skyscraper/archive/${LATEST}.tar.gz

```
As the "archive" subdir get a 404 error not found...

**Comment by micbuffa** [comment]
Well, actually, even copying and pasting this simple command from the instructions fails 👍 
```
buffy:skysource mbuffa2$ wget -q -O - https://raw.githubusercontent.com/muldjord/skyscraper/master/update_skyscraper.sh | bash
--- Fetching Skyscraper v. ---
--2019-01-19 15:30:56--  https://github.com/muldjord/skyscraper/archive/.tar.gz
Resolving github.com... 140.82.118.3, 140.82.118.4
Connecting to github.com|140.82.118.3|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
buffy:skysource mbuffa2$
```

**Comment by muldjord** [comment]
This is a local SSL problem. You'll need to fix that on your system, there's not much I can do about it.

**Comment by micbuffa** [comment]
The url for the tar.gz does not exist

**Comment by muldjord** [comment]
Yes it does, please read above. Your version of wget doesn't support the github ssl protocol, which probably means that your ssl is outdated. There's nothing I can do about that on my end I'm afraid. What system are you on?

**Comment by micbuffa** [comment]
Ok, it xas my wget that has a bad symlink (I'm on mac os). SSL fixed now. I had to remove the --overwrite option in the tar xvfz command in the script as it complained "overwrite option not supported by tar". It worked fine then.
