### ISSUE TITLE
sg-1000 scraping no files found

### ISSUE THREAD

**Issue by ghost** [muldjord/skyscraper#106]
working pretty good so far, but have some sg-1000/genesis games and tried to scrape them, but keeps coming back with file not found. used all the various sources to to avail.

filename syntax samples as noted: (not sure if these were named correctly)
16 Tiles Mahjong (Unl) [c].bin
After Burner II (U) [!].bin
Sonic the Hedgehog (JUE) [!].bin

and noticed that even though no info found, nothing is written to the gamelist.xml file ... is this normal behaviour, I would think it would still write the game to the file without the metadata, so the game could be launched, but as it stands the xml file is empty

**Comment by muldjord** [comment]
Are these sg-1000 or genesis roms? Those are two very different systems. If you have them mixed that will be a problem when trying to identify them in the databases.

Concerning getting the empty entries in the gamelist.xml, you can use the `--skipped` command line option to do so. But it shouldn't be necessary, the games show up in ES even if they are not in the game list.

**Comment by muldjord** [comment]
Closing due to lack of response
