### ISSUE TITLE
Shared path for cache folder

### ISSUE THREAD

**Issue by rrbenitez05** [muldjord/skyscraper#108]
Hello,

I have my roms in a shared drive and I want to Skyscraper to use that same shared drive for the cache.
I am on a retropie 4.4 and the shared drive is on a windows 8 machine. 
My rom folder is on that shared folder at

d:/RetroPie/roms

So I opened up the config and i'm just confused on how I should "word" that shared drive so that Skyscraper points to it.  

So right now the config has this path for the cache  is

#cacheFolder="/home/pi/.skyscraper/cache"

So I want to change that path to the shared drive. 
The shard path on the pc is

d:/RetroPie/

so should that path be 

cacheFolder="d:/Retropie/cache"  

or

"//RetroPie/pi/.skyscraper/cache"  

I guess what i'm asking is what path should i use?

Thank you!

**Comment by cmitu** [comment]
You've already opened a topic in the RetroPie forum - https://retropie.org.uk/forum/topic/20985/. Github is for bug reports, not for RetroPie support.
