### ISSUE TITLE
Here are some extra Mac commands to get it installed

### ISSUE THREAD

**Issue by qthegaijin** [muldjord/skyscraper#109]
To get the latest Skyscraper set up on my mac, I had to modify+add a few lines to the process.

PreReq Install:
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
$ brew install gnu-tar --with-default-names
$ brew install wget
$ brew install qt5
$ brew link qt5 --force
$ brew install p7zip

Then I had to modify 1 line in update_skyscraper.sh:
"tar xvzf ${LATEST}.tar.gz --strip-components 1 --overwrite"
to
"gtar xvzf ${LATEST}.tar.gz --strip-components 1 --overwrite"

Would it be possible to make something like "update_skyscrapermac.sh" to go alongside the regular linux one?
I have it running smoothly right now on Mac OS 10.12.6.

Cheers!

**Comment by davidaubespin** [comment]
As a note, you could follow the standard install (i.e. without installing p7zip and using the regular tar command) if you simply remove "--overwrite" (which I think is the default anyway on Mac OS tar).

**Comment by qthegaijin** [comment]
That works too.
I needed p7zip for the unzipping of roms during scrape if I chose to do so.
