### ISSUE TITLE
Occasional hangs after showing Elapsed and Estimated time

### ISSUE THREAD

**Issue by bleuge** [muldjord/skyscraper#11]
Running in Raspberry Pi3 with last Retropie and last Skyscraper (just compiled)

Sometimes after some scraping, it seems it hangs after showing the times. Don't know what is doing exactly, it stops there for many minutes, finally i hit ctrl+c 

I used --verbose, but don't show anything about this

Is there a way i can tell if it's working? I suppose if it don't show anything new for several minutes is bugged?
Thanks
Edit: for example, now is stopped in Shinobi game using openretro as scraper. It says 100% match, then shows the times, and ... thats all. I must hit ctrl+c to exit.

**Comment by muldjord** [comment]
Does it halt at the same point every time? If it prints the "Shinobi" result on the screen, that means it has been scraped succesfully (and is therefore not the game causing problems), so if it's a certain game causing the problem it's the following game. But, keep in mind that it runs 4 threads, so they aren't necessarily alphabetical. I suggest trying a scraping run and adding '-t 1' which forces it to 1 thread. Then it will run them alphabetically, and you can figure out what game might cause the problem (the one following the one it prints on the screen). If it stops at the same game everytime, please let me know which game, the exact filename. Also, please tell me which platform you are scraping.

EDIT: Yes, 'verbose' is not very useful at the moment. I plan to expand that a lot in a future release. But for now I am focused on the compositor for 2.3.0.

**Comment by bleuge** [comment]
I am scraping all platforms, with -t 8, used your skyscript.sh as model for the rest.
Could it be openretro?
When it halts is always after printing estimated time. 
WIFI Network is ok, i am sure because i opened another console and run a ping -t there.
Maybe --verbose could print more data? I could easily modify the source and test...

**Comment by muldjord** [comment]
It will always hang at that point no matter what is wrong. The screen output is accumulated and printed with the same function to avoid overlaying output from different threads. So that doesn't tell you much I'm afraid.

I have a 30 second timeout on the network connection, so if it stops for more than that, it might be because of something else. Unless it completely looses connection, then I'm not sure how it would react.

Could you try it with a cabled network? The Wifi on the Pi is known to be quite unstable, even when placed relatively close to the access point.

**Comment by bleuge** [comment]
It finnished, after some ctrl+c and restarts... I guess is something related to wifi/network or something like that. But, if network timeouts, doesn't skyscraper catch the exception and show an error? 
It just stays there in the screen and nothing written after Estimated Time.

**Comment by muldjord** [comment]
I will look into the timeout code when I get 2.3.0 out the door. All my time is going into getting that ready at the moment.

**Comment by muldjord** [comment]
Reopened this issue, as I've found a specific flaw in my network code that sometimes makes it stall if the source file is called something like "[BIOS] Something". I will fix this issue in 2.3.4.
