### ISSUE TITLE
Scraper not t able to scrape some games

### ISSUE THREAD

**Issue by RetroD** [muldjord/skyscraper#110]
Hello, I just started using skyscraper and found it really good and easy to use.
I just had a small issue when scraping my amiga whdload collection on my rpi3 (retropie setup on stretch) 
I am not sure if this is something that is best to report here or somewhere on OpenRetro (which is the module I am using). 
Basically I am scraping the latest supported lha games for my whdload setup for amiberry and everything went great apart from a small percentage of my collection. Most are games I don't really care about, but noticed all the indiana Jones games (adventure or arcade versions) did not scrape. I coud manually create the entries for these from what I read in the docs but I though I should report it in case there is an issue with the scraper or  OpenRetro. Any advice?

**Comment by muldjord** [comment]
I know Frode, who own OpenRetro, adds the new WHDLoad games occasionally. When he does, it should automatically be added to the xml file I use to map them to actual games. So this is mostly a case of waiting for them to be added. I guess you could also do it yourself I think. Either way, It's not a Skyscraper issue. Closing this.
