### ISSUE TITLE
Request for an specific item from scraper

### ISSUE THREAD

**Issue by ferarias** [muldjord/skyscraper#111]
It would be useful to add an option to request a well-known item from a scraper. For example, if I do

`Skyscraper -p amiga -s openretro /home/pi/RetroPie/roms/amiga/TitusTheFox_v2.0_0226.lha`

I get no results because the scraper does not allow more than 2 words. However, I know the item exists at https://openretro.org/amiga/titus-the-fox

I could get this exact entry by using, for example 

`Skyscraper -p amiga -s openretro /home/pi/RetroPie/roms/amiga/TitusTheFox_v2.0_0226.lha --exact "amiga/titus-the-fox"`

What do you think?

**Comment by muldjord** [comment]
These options already exist, please read the documentation: https://github.com/muldjord/skyscraper/blob/master/docs/CLIHELP.md
