### ISSUE TITLE
Add an option to skip free space check

### ISSUE THREAD

**Issue by mprasil** [muldjord/skyscraper#114]
**Describe the feature**
It would be nice to have an command line option to skip free space check.

**Contact mails and documentation**
Not relevant.

**Additional context**
I was trying to run Skyscraper on the samba share in Gnome. Share is mounted via gvfs and it appears that the free space check fails for some reason there even though there's couple TB free and throws out this error: 

```
You have very little disk space left, please free up some space and try again. Now aborting...
```

Besides some issues estimating the free space in my case (which is probably very edge case) it seems like the program [requires](https://github.com/muldjord/skyscraper/blob/master/src/skyscraper.cpp#L446-L451) 200MB of free space, which might block some valid use cases as the media downloaded can be orders of magnitude smaller. It would be nice to have some option to skip the check.

**Comment by muldjord** [comment]
Skyscraper checks both the drive where the artwork and game list is exported to, but it also checks the folder where the Skyscraper cache resides. Are you sure none of those locations are running low on disk space? I will add a `spaceCheck="false"` option to the config.ini `[main]` section for the next version, but please check that you are in fact not having low disk space as I am very interested in finding out if this is your gvfs that's reporting faulty space left.

**Comment by mprasil** [comment]
I've just created the rom folder locally and symlinked the roms and it ran just fine. So the cache folder was the same.

`df` shows correct free space on the gvfs mounted  samba share, but the path contains unusual characters, which makes me wonder if it's not related to some broken path parsing, I'll try to copy paste it once I get to my PC.

Still though, I think it's good that you add this option as some people might find that somewhat artificial limit a bit.. umm limiting.

**Comment by muldjord** [comment]
The limit is fine in the context of the RetroPie where all folders reside on the system drive. But I agree, for cases like this, where something is causing it to fail the check, it should be possible to disable it. It has been implemented and will be in 3.0.2 when it releases.

**Comment by mprasil** [comment]
Okay, so here's the gvfs path:

```
/run/user/1000/gvfs/smb-share:server=server.domain.name,share=sharename/path/on/share
```

`df -h` on that directory shows:

```
Filesystem      Size  Used Avail Use% Mounted on
gvfsd-fuse      2.1T   35G  2.1T   2% /run/user/1000/gvfs
```

So there clearly is enough space, the path is going to test proper path handling though. :smile:

**Comment by mprasil** [comment]
Hi, I've compiled the master branch and can confirm all works fine with `spaceCheck="false"` set in the config file. From my side this is resolved and OK to close, however if you want to dig down into the space check issue, feel free to ask questions.

Thanks a lot for fast response.

**Comment by muldjord** [comment]
How much space do you have in `~/.skyscraper`? That's where the cache resides and this is also checked, as I mentioned earlier.
