### ISSUE TITLE
Skyscraper doesn't list option for system contained in a symlink

### ISSUE THREAD

**Issue by IgniparousTempest** [muldjord/skyscraper#115]
Posting bug report in reference to [this discussion](https://retropie.org.uk/forum/topic/21057/skyscraper-doesn-t-list-option-for-system-contained-in-a-symlink) on RetroPie forums.

**Describe the bug**
Skyscraper doesn't follow symlinks.

**To Reproduce**
Move one of the ROM folders somewhere else and symlink it.

**Special circumstances**
One of the ROM folders is a symlink.

**Technical information**
 - Skyscraper version: 3.0.1
 - Internet connection: fibre
 - OS: RetroPie
 - OS Version 4.4

**Additional context**
None.

**Comment by muldjord** [comment]
Have you tested this? Skyscraper does, to the best of my knowledge, follow symlinks just fine. This should be an issue with the RetroPie script, not Skyscraper itself. If you've tested Skyscraper itself and it has this problem, let me know.

**Comment by muldjord** [comment]
Just tested this myself, it works just fine. Please report issues with the RetroPie-script to mitu instead, thanks.
