### ISSUE TITLE
Use of `--startat` and `--endat` switches crashes Skyscraper under specific conditions

### ISSUE THREAD

**Issue by Gemba** [muldjord/skyscraper#116]
**Synopsis**
Use of `--startat` and `--endat` crashes Skyscraper under specific conditions.

**Severity**
Low. Workaround present.

**Version-Info**
-  Skyscraper 3.0.1
-  Built on retropie 4.4.6 (4fe3f72f)

**Actual behaviour**
Skyscraper crashes when using a filename interval, which looks valid on the terminal.

```
$ ls -1 ;/opt/retropie/supplementary/skyscraper/Skyscraper -p snes  -s screenscraper \
--startat "Addams Family, The (Europe) (En,Fr,De).zip" \
--endat   "Addams Family Values (Europe) (En,Fr,De).zip"

Addams Family, The (Europe) (En,Fr,De).zip
Addams Family, The - Pugsley's Scavenger Hunt (Europe).zip
Addams Family, The (USA) (Arcade).zip
Addams Family Values (Europe) (En,Fr,De).zip
media

------------------------------------------
Running Skyscraper v3.0.1 by Lars Muldjord
------------------------------------------
Platform:           'snes'
Scraping module:    'screenscraper'
...
Bus-Zugriffsfehler
Unhandled fault: alignment exception (0x001) at <hex1>
pgd = <hex2>
[<hex1>] *pgd=<hex3>, *pte=0, *ppte=0,
```

For `strace` output see: <https://pastebin.com/gGFgnmkF>

**Additional information**
When using the same filename for `--startat` and `--endat` the above error does not occur, so a filename "escape" problem (esp. due to `()` and whitespace chars) can be crossed out.

**Expected behaviour**
Skyscraper starts operation with the files in between `--startat` and `--endat` since `ls` shows the user a valid, non-empty interval of files.

**Analysis**
`ls` sorts locale specific. So what the users sees on the terminal with ls is not what skyscraper "sees".

Proof: Resetting locale to Standard C (`LANG=C ls`) aligns the users and skyscrapers perception and skyscraper "sees" a empty interval of files, when using the same values for `--startat` and
`--endat` as above:
```
LANG=C ls -1 ;/opt/retropie/supplementary/skyscraper/Skyscraper -p snes  -s screenscraper \
--startat "Addams Family, The (Europe) (En,Fr,De).zip" \
--endat   "Addams Family Values (Europe) (En,Fr,De).zip"

Addams Family Values (Europe) (En,Fr,De).zip
Addams Family, The (Europe) (En,Fr,De).zip
Addams Family, The (USA) (Arcade).zip
Addams Family, The - Pugsley's Scavenger Hunt (Europe).zip
media

------------------------------------------
Running Skyscraper v3.0.1 by Lars Muldjord
------------------------------------------
Platform:           'snes'
Scraping module:    'screenscraper'
...
Bus-Zugriffsfehler
```
Locale used in this scenario:
```
$ echo $LANG
de_DE.UTF-8
```

**Workaround**
Use `--startat` and `--endat` with values as reported by the output of `LANG=C ls -1`. Example:
```
$ LANG=C ls -1 ;/opt/retropie/supplementary/skyscraper/Skyscraper -p snes  -s screenscraper \
--startat "Addams Family Values (Europe) (En,Fr,De).zip" \
--endat   "Addams Family, The - Pugsley's Scavenger Hunt (Europe).zip"

Addams Family Values (Europe) (En,Fr,De).zip
Addams Family, The (Europe) (En,Fr,De).zip
Addams Family, The (USA) (Arcade).zip
Addams Family, The - Pugsley's Scavenger Hunt (Europe).zip
media

------------------------------------------
Running Skyscraper v3.0.1 by Lars Muldjord
------------------------------------------
Platform:           'snes'
Scraping module:    'screenscraper'
...
Starting scraping run on 4 files using 1 threads.
Sit back, relax and let me do the work! :)
...
```

**Comment by muldjord** [comment]
Thank you for the thorough description, I appreciate that a lot. This was easy to reproduce and I have now fixed the crash on master. It will be in the next release (3.0.2). Now closing.
