### ISSUE TITLE
[Request] Link directly to the cached video in gamelist.xml instead of using a symlink?

### ISSUE THREAD

**Issue by HumanRob** [muldjord/skyscraper#118]
First of all thanks for adding the ability to symlink to the cached video instead of creating a new copy - it's going to save so much space on my sd card! After trying it out though I'm wondering whether it might be better just to bypass symlinks altogether and just point the video tags in gamelist.xml directly to the cached file. Would there be any downsides to doing this?

The main issue I see with symlinks after trying them out is that they don't work well if you manage your roms folder via a samba share. If I browse the folder there isn't a way of telling which ones are symbolic links and which aren't without running an SSH shell to check. Backing up via a samba share would create duplicate copies of videos, and restoring via a samba share wouldn't work unless you then re-run skyscraper for every platform to restore the symlinks.
Again, I might be missing something (like maybe permissions issues?) but it doesn't seem like the symlinks need to be there when the gamelist.xml video tags could just point directly to the cache.

If you don't want to or can't implement this change the existing feature is still very useful as it stands, so thanks again!

**Comment by muldjord** [comment]
Well, it's all down to the internal variables I use for the video node. The symlinking is done in a different place basically and all the game entries in the internal data structure share the same video path. I'd have to change that on the fly to make this work which I'm not really sure I want to do. But I might look into it at some point.
