### ISSUE TITLE
Cache database losses results when scraping different sources

### ISSUE THREAD

**Issue by kcgen** [muldjord/skyscraper#119]
If Skyscraper is pulling from two different sources at the same time, then the last instance to complete will clobber the cache results written by the other instance.

For example, fetch from different sources at the same time:

1. `Skyscraper -p fba -s screenscraper 1943u.zip`
2. `Skyscraper -p fba -s arcadedb 1943u.zip`

In my example, Arcadedb finished first:

> ---- Scraping run completed! YAY! ----
> Writing 10 (10 new) resources to cache, please wait... Success!

Then screenscraper finished second:

> ---- Scraping run completed! YAY! ----
> Writing 13 (13 new) resources to cache, please wait... Success!
> Sorting entries... Done!!!

Let's take a look at the cache database:

`Skyscraper -p fba --cache show`
```
------------------------------------------
Running Skyscraper v3.0.1 by Lars Muldjord
------------------------------------------
Platform:           'fba'
Scraping module:    'cache'
<snip>

Reading and parsing resource cache, please wait...
Successfully parsed 13 resources!

Resource cache stats for selected platform:
'screenscraper' module
  Titles       : 1
  Platforms    : 1
  Descriptions : 1
  Publishers   : 1
  Developers   : 1
  Ages         : 0
  Tags         : 1
  Ratings      : 1
  ReleaseDates : 1
  Covers       : 1
  Screenshots  : 1
  Wheels       : 1
  Marquees     : 1
  Videos       : 0
```

We see that all memory of the arcadedb results are list..  even though it fetched good data.

The problem here is Skyscraper reads the cache file on startup, and clobbers it on successful completion - regardless of whatever updates might have been made in the meantime.

As a developer, I would suggest several approaches to tackle this:
 1. Don't use an XML file as a cache index; use something like sqlite3, which handles concurrency regardless of parallel accesses both at the thread and process level.  This will also let you write to the cache after each game is successfully queried, as opposed to waiting until the end and performing one big mass-write (and clobbering whatever's in the xml file).
 1. If you want to keep using XML - then don't read the XML file on startup. Instead, wait until you want to write, then check for the presence of a lock file (db.lock, for example). If it exists, then wait a second and check again (looping wait). Once the lock file is not present, then create the lock file, read the existing XML file, update it with your new records, write the XML file, then delete the lock file.
1. Another alternative: consider eliminating the notion of a cache index all together.  Instead use hashed files for all of the fetched content (like you're already doing for images), including all the text fields. For example, description/$hash.txt, publisher/$hash.txt, release_date/$hash.txt etc..   This approach eliminates all potential corruption or inconsistency issues between the index and the directory contents.. because with this approach, you simply directly query the directories.

**Comment by muldjord** [comment]
Please do not run Skyscraper in parallel, it is not meant to be used like that. The only use case I can see for this is to circumvent the limits the scraping sources have on threads. This is highly frowned upon as the limits are there for a reason. We all have a responsibility to make sure the online databases are healthy. Hence the limits.. Closing issue.

**Comment by kcgen** [comment]
> The only use case I can see for this is to circumvent the limits the scraping sources have on threads.

Well, the use case and bug here involves **_different_** sources, and does not attempt or desire to circumvent the limits embedded in Skyscraper nor the limits imposed by the given online source.

Likewise, addressing this bug properly is an entirely separate concept to allowing (or not allowing) limit-circumvention, which should be done using a per-source lock file, regardless of platform.  As it stands (regardless of this bug), Skyscraper happily circumvents source limits if it's run against the same source multiple times provided the platform is different.  That said, I do not run it that way given I appreciate our online sources.. I'm merely providing it as a counter example to your use of limit circumvention as an objection to adressing this bug. 

This bug results in losing the entire run-worth of data, which might be gigabytes of content that needs to be re-downloaded.  To me, this is far more harmful to both the user (who might have just consumed their monthly thegamesdb query alottment) and the source providers, because in all cases the same run needs to be repeated resulted in wasted time and consuming precious API hits and bandwidth from the sources.  Skyscraper actually received the data **and lost it**.  That's what this bug is about.

**Comment by muldjord** [comment]
Then don't run it in parallel. I have no intention of letting Skyscraper do disk IO for each and every cache lookup. I hope you can see how that is undesirable. Skyscraper currently has the entire cache in ram, which is both fast and optimal for SD cards.
