### ISSUE TITLE
Does not see dreamcast .chd files as roms

### ISSUE THREAD

**Issue by esmith13** [muldjord/skyscraper#12]
Performed initial simple scrape for dreamcast and it found 0 roms in default rom directory which in fact had a few dozen dreamcast .chd files.
compiled/executed on Lubuntu 17.10 dedicated retropie/ES system. Roms in default path /home/pi/RetroPie/roms/dreamcast/. Attempted scrape with my preferred settings as well as with all default options.

**Comment by muldjord** [comment]
I will add .chd files for dreamcast in 2.3.2

**Comment by esmith13** [comment]
Thanks! Also, if you don't already have them yet - .chd files are also used for the systems "segacd", "pcengine"/"tg16",  and "psx".

 Also, not to be a pest but just to mention the other compressed disc image formats/systems used (I have not tested any of these yet to see if already supported):
"psp" - iso, cso, pbp
"psx" - cue, pbp, chd
"gc" - iso, cso, gcz
"wii" - iso, cso, gcz, wbfs
"dreamcast" - iso, gdi, cdi, chd, cue
"segacd" - cue, chd
"pcengine"/"tg16" - cue, chd


Thank you again for your time.

**Comment by muldjord** [comment]
Wii and Gamecube wasn't in so I've added them. Some of the file extensions for the rest have been added. All will be in 2.3.2.

**Comment by muldjord** [comment]
2.3.2 out now :)
