### ISSUE TITLE
Problem creating gamelists correctly

### ISSUE THREAD

**Issue by chvimax** [muldjord/skyscraper#120]
Hello,
i'm using skyscraper db after getting the stuff from screenscraper. In gamelist it creates (example): <name>4-in-1 Fun Pak (UE) [!]</name> and don't finde the entry <resource sha1="b1443c09ee3f2bee5437111a635b6d84155f600e" type="title" source="screenscraper" timestamp="1549103056426">4-in-1 Fun Pak</resource>. Why it don't take the "titel" and give it to "name" in gamelist. Same problem with <cover>.../downloaded_media/gb/covers/4-in-1 Funpak (UE) [!].png</cover> emulationstation only show the cover when it is under <image><image />. And when i scrap and something will not found, he says: (Filenames saved to '~/.skyscraper/skipped-screenscraper.txt') but nothing to find here. I'm using newest version RetroPie with Pie 3B+. First installed Skyscraper manually, than the retropie version but no change. deleated everthing and gone back to manually version. Can't find a solution, pealse help.

**Comment by muldjord** [comment]
Please ask this on the retropie subreddit or on the retropie forums. This is for bugs and feature requests only. People will be able to help you there. Thanks.
