### ISSUE TITLE
Cache database losses results if process terminates mid-scrape

### ISSUE THREAD

**Issue by kcgen** [muldjord/skyscraper#121]
If a long-running scraping session is terminated (for any reason), then the cache will not be updated resulting in loss of the entire run's worth of data.

A real example: start a multi-hour scraping run.  After one hour, thousands of good hits and gigabytes of images have been downloaded from the source. At some point after the first hour, the scraping job terminates due to an external reason (for example, laptop battery running low and OS auto-shuts down). In this example, all of the good hits fetched during the prior hour _**are lost**_ and must be re-downloaded from the source again. 

The expected behavior is that positively fetched results are cached atomically, per-rom, and do not depend on the termination state of the process at some point in the future.

**Comment by muldjord** [comment]
Yes, this is an issue I am well aware of. Might fix this at some point. It will not be implemented as you suggest though as disk IO would be pretty high. I would instead simply catch the signal and quitting nicely instead of just doing a premature ending of the process.

**Comment by muldjord** [comment]
This has now been fixed, will be in 3.0.2. When recieving SIGINT it will save the cache and exit nicely. Thank you for pointing it out.

**Comment by bsdf** [comment]
i lost an hours-long scraping session due to this issue-- my ssh session was terminated which sends `SIGHUP` rather than `SIGINT` (if i understand correctly)

**Comment by muldjord** [comment]
I suggest running it through screen or sending it to background if you are having SSH stability issues.

EDIT: I will check if it makes sense to act on SIGHUP as well. But I don't really think that's how it works. If an SSH session is interrupted by network dropout, I'm pretty sure the task is simply killed off. But I will look into it.

EDIT2: I just did some quick testing on SIGHUP and as expected it doesn't work. When the terminal process is killed it takes its child processes with it. This would work for daemonized processes, not for attached processes. So no dice. So my suggestion is to detach it by running it through screen or other wise make sure it's not directly attached to your session.

**Comment by bsdf** [comment]
thanks for taking a look-- it was definitely my fault in assuming that it would cache items as it retrieves them. i'll be more careful in the future
