### ISSUE TITLE
Add amigacd32 to scrapeable platforms

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [muldjord/skyscraper#122]
Hopefully self explanatory.

A lot of ES themes have the option of using 'amigacd32' as an extra platform.

A forthcoming Amiberry update is going to add support for .cue files (at minimum) to be loaded for CD32 games direct from the command line. ISO and IMG files are also a possibility.

OpenRetro has a seperate section for CD32 games rather than disk amiga games, which it might be preferable to scrape uniquely (or as a priority) for this:  https://openretro.org/browse/cd32

Please consider adding an option to scrape files for this platform, using the existing sources.

**Comment by HoraceAndTheSpider** [comment]
Additional:  it seems the CUE files are included in the main page, so we could look at creating an XML for UUID's also.
https://openretro.org/cd32/alfred-chicken/edit#cfa21fc6-d8aa-51bf-9771-fb16c49314b3

**Comment by muldjord** [comment]
Actually this should already work. Just checked, and .cue is already in the supported extensions for Amiga. And Amiga has the CD32 included as aliases for all of the scraping modules, so it should just work.

EDIT: I do a check for 'cd32' in the filename and change the platform dynamically while scraping the Amiga platform. So as long as the files include 'CD32' or 'cd32', it will look for a result with that platform in particular.

**Comment by HoraceAndTheSpider** [comment]
the above requires the platform's path to be changed to `/roms/amigacd32/` when required i assume?
Some of the problem is that the CUE filename often wont include the CD32 part (i'm going by TOSEC naming here) and would ordinarily pick up the disk version.

This is solved by `-p amigacd32` option, or if it checked the full path for `cd32` when scraping and not just the filename (as per my manual change suggestion)

**Comment by muldjord** [comment]
I could absolutely do that, but 'cd32' is not a RetroPie platform, so that'd need to be added first. But you could just aswell just add a 'cd32' folder under your 'amiga' folder and put your cd32 games in there.

**Comment by muldjord** [comment]
Just thought of something else I could do. In addition to checking for 'cd32' in the filename, I can also change the platform if it's a .cue, .img or .iso file while scraping the 'amiga' platform. It's a pretty clear cut distinction except it would also change it to 'cd32' for 'cdtv' games. But I think the positive outweighs the negative of that.

**Comment by muldjord** [comment]
Just tested this with '-s openretro' and it works well. This will be in 3.0.4.

**Comment by HoraceAndTheSpider** [comment]
Sounds good.

I think it’s unlikely RetroPie will add cd32 as a separate platform, but many of the themes for  already seen to be set up to add it to amigacd32

**Comment by HoraceAndTheSpider** [comment]
ha, cant believe i'm back here again.  I've just been using the EmulatonStation integration of SkyScraper (which is very nice - kudos to those involved)

When picking 'amigacd32' it just seems to scan from the parent /roms/ folder, so suddenly is trying to scan a lot of files! Not sure if this happens with any other more obscure platforms.

**Comment by muldjord** [comment]
Oh my, that must mean you've wrapped around and The Matrix has been reset. :P

The script lists the folders you have in the `roms` folder as platforms. That's the only reason it's shown. Skyscraper doesn't support `amigacd32` as a separate platform to the `amiga` platform. But I guess I could add it, even though I don't think it's a RetroPie platform (which is what I try to stick to, but you already know that).

Buuuuut, since you're being so darn persistent. :D I guess I'll add it. It'll just be a copy of the Amiga platform basically, but with a different input folder.

**Comment by muldjord** [comment]
3.6.1 out now with `amigacd32` as a separate platform.

**Comment by HoraceAndTheSpider** [comment]
Legend - thank you!

**Comment by HoraceAndTheSpider** [comment]
My “argument” on this is that we get all should those lovely Cd art covers :)
