### ISSUE TITLE
Generate a list of games missing resources matching type

### ISSUE THREAD

**Issue by JaymesRS** [muldjord/skyscraper#123]
**Describe the feature**
I would like to be able to help out the data sources that are missing resources for certain games, especially gameplay videos or screen grabs that are easy to get right within RetroPie. Since Skyscraper knows what I have cached, I would like to be able to generate a list of games missing resources by type, eg. create a file with all games missing screenshots by Platform - Title. This would save me from having to page through the game lists individually.

**Comment by msdos** [comment]
This is useful not only for scraping videos, but to know which games we can contribute to screenscraper.fr database.

If this is not possible from Retropie, is there a CLI command to get this somehow?

**Comment by muldjord** [comment]
I agree, this would be very useful. I have been pondering this for a while, and I think I'll end up making a `--cache report:<SOMETHING>` cli command that will allow you to create various reports from the cached data. This could then be `--cache report:missing=video` which would then create a report with all roms missing videos or similar. Or you could do `--cache report:missing=all` which would simply create a report with all missing data. Something along those lines.

**Comment by muldjord** [comment]
3.2.0 has just been released with this feature implemented. :) Read more about it [here](https://github.com/muldjord/skyscraper/blob/master/docs/CLIHELP.md#--cache-reportmissingall-textual-artwork-media-or-resource1resource2).

**Comment by JaymesRS** [comment]
Thank you!
