### ISSUE TITLE
[Request] Possibility to add a test mode for comparing scrapped data from different sites

### ISSUE THREAD

**Issue by bleuge** [muldjord/skyscraper#125]
I've have my scrapping done for now, but I also got a huge cache I got last year when I first discovered this great tool, I'll try to import it, so my cache will be lot bigger, so I was thinking...

Skyscraper -p amiga --test openretro screenscraper

This could show what you are actually printing in the scrapped data,  but without actually doing it, and showing the screen splitted with the two platforms showed if they were first in the priorities file

The idea is to test scrapped data prior generating real gamelists, so a user could test some possible cases and choose the best scraper for each item with data.

I don't know if this could be useful for anyone, but I was thinking in doing it by hand, comparing files in the cache data to see if I can make good selections for the priorites lists.

Or maybe this could be do in other way?, Skyscraper has so powerful options...

Thanks @muldjord !

**Comment by muldjord** [comment]
You can already do `--pretend` when generating the game lists (leave out `-s`). Then it will show you what it wants to do. You can even add a single rom on command line to see what it will choose for that particular rom. And you can also use `--startat` and `--endat` to check a span of roms. As long as you use `--pretend` it will only show you the results, not actually change the game list.

I don't think I will make a mode as you request. It seems to cumbersome to me. But I will at some point make some `edit` modes where you can edit the cached data for any of the roms (this will basically also give you what you are requesting, just allow you to edit while you are doing it). But it's not coming anytime soon as I don't have much time to work on Skyscraper at the moment. :)

I will close this now.

**Comment by bleuge** [comment]
Yes!, thanks, I can do it this way with some logging :D
Your edit idea is great also!
