### ISSUE TITLE
Spelling mistake in config.ini leading to confusion

### ISSUE THREAD

**Issue by quicksilver7837** [muldjord/skyscraper#130]
I have seen several people have issues adding their screenscraper credentials to the config.ini. looks like there is a spelling mistake that people aren't noticing.

#[<scraping module, eg 'screenscaper'>]
#userCreds="user:password"

Should be screenscraper not screenscaper

**Comment by muldjord** [comment]
Fixed. Thanks for letting me know. Closing.
