### ISSUE TITLE
Update documentation on edit artwork.xml correct location

### ISSUE THREAD

**Issue by vitto** [muldjord/skyscraper#131]
I'm using skyscraper for my retropie machine and it's fantastic, the only thing i didn't found is where I should edit/update the `artwork.xml` file since the [artwork docs](https://github.com/muldjord/skyscraper/blob/master/docs/ARTWORK.md#artwork-look-and-effects) just says where I shouldn't.

Is it possible to add the right procedure to update the artwork?

**Comment by vitto** [comment]
Sorry, I just realized you wrote `~/SKYSOURCE/artwork.xml` not `~/.skyscraper/artwork.xml`.

**Comment by vitto** [comment]
I still find difficult to understand how to update this xml, I cannot see changes take effect with reboot, where I can find the right procedure?

**Comment by muldjord** [comment]
https://github.com/muldjord/skyscraper/blob/master/docs/USECASE.md#the-game-list-generation-phase

**Comment by muldjord** [comment]
Also added note about this in the artwork docs. Thanks.
