### ISSUE TITLE
Support for Launchbox Games DB as scraper

### ISSUE THREAD

**Issue by ozy24** [muldjord/skyscraper#132]
Hello i'm not sure how possible this is but I discovered that LaunchBox has an extensive games database.  Is it possible for Skyscraper to support this as a content source?

https://gamesdb.launchbox-app.com/

Regards,

Chris

**Comment by muldjord** [comment]
I've looked into this before, but haven't been able to find any sort of API for it that will allow me to look up data in a meaningful way. It seems to be Launchbox only. Let me know if you find an API for it. And I don't mean this: http://pluginapi.launchbox-app.com/html/33539a00-0c45-8b3a-35fc-299c5808baca.htm which is just a plugin api for the Launchbox app itself. I can't use that for anything.

**Comment by RolfVeinoeSorensen** [comment]
There seems to be no API for scraping the LaunchBox. 
LaunchBox  seems to just download a zipped metadata with xml files it then parses.
https://gamesdb.launchbox-app.com/Metadata.zip
It then uses the internal id to get images
`  <Game>
    <Name>20th Century Video Almanac</Name>
    <ReleaseYear>1993</ReleaseYear>
    <Overview>In The Best of Our Century, we've taken multimedia to dizzying new heights and you control the ride! Relive the most earthshaking events of the 20th century. Touch down on the moon with the Apollo astronauts. Relive Woodstock. Attend President Kennedy's inauguration. Take a front row seat for the incredible 1916 World Series. This multimedia reference work uses one of the world's largest archives of historical video to produce a visual encyclopedia of the century, with audio, photos, and text. The 20th Century Video Almanac provides a broad look at the events that shaped our world.</Overview>
    <MaxPlayers>1</MaxPlayers>
    <Cooperative>false</Cooperative>
    <VideoURL>https://www.youtube.com/watch?v=dfFT6jqjFq0</VideoURL>
    <DatabaseID>17687</DatabaseID>
    <CommunityRating>2.75</CommunityRating>
    <Platform>3DO Interactive Multiplayer</Platform>
    <ESRB>Not Rated</ESRB>
    <CommunityRatingCount>20</CommunityRatingCount>
    <Genres> Education</Genres>
    <Developer>The Software Toolworks</Developer>
    <Publisher>The Software Toolworks</Publisher>
  </Game>`
https://gamesdb.launchbox-app.com/games/images/17130
So unless some agreement is reached with a real API I agree it does not seem right to use this source both from the perspective of to much workaround coding and maybe they dont want to share...

**Comment by ozy24** [comment]
OK thank you for looking into it.. I thought this might be the case.

Hopefully the situation will change in the future.

**Comment by muldjord** [comment]
Interesting, thanks for the info. If used, I would have to set up an API myself, which is not something I am willing to do. But I could create a module called "launchbox" and simply crave that users download and extract that zip file before using it (and the data from it would carry a 'launchbox' source, so there would be plenty of attribution by doing it like this). But it would be textual data only, as I don't think they would allow the downloading of images. Either way, I would need permission to do this aswell.

Frankly I'm not sure I think it's worth the effort.

**Comment by muldjord** [comment]
Looked into this a bit more and I've concluded that this isn't really feasible to do. I would have wanted to ask users to download the metadata zip manually and put it in the Skyscraper folder. It would then use that to scrape data from. The problem here being that the xml is more than 100 megs and Skyscraper is already stretching it memory wise on the RPi. So this would almost certainly crash the software on many occasions. Alternatively I could load each entry in the xml at a time and compare it to the current game search, but that would create insane amounts of reads on the disk, just for a single game. Not a solution either. So yeah, I'm closing this.
