### ISSUE TITLE
Error: "couldn't read artwork xml" when attempting to purge cache

### ISSUE THREAD

**Issue by 2fst4u** [muldjord/skyscraper#134]
I am receiving the following error when I attempt to purge my cache:

"couldn't read artwork xml file 'artwork.xml'. Please check file permissions. Now exiting"

I am on version 3.1.3 installed from source through retropie.

This error causes the cache to remain and nothing gets deleted.

**Comment by 2fst4u** [comment]
![IMG_20190317_182344](https://user-images.githubusercontent.com/15257926/54485711-7ab4f880-48e2-11e9-8611-4d23eab2ba09.jpg)

**Comment by 2fst4u** [comment]
The permissions on the file are:

```
-rw-r--r--  1 pi pi     881 Mar 14 05:31 artwork.xml
```

**Comment by 2fst4u** [comment]
I have done an uninstall of skyscraper (which seems to try to clear the cache as the first step because the same error appears at the start of the process) and deleted all leftover folders and files, then ensured my retropie script was updated, then reinstalled skyscraper fresh and I still get the error.

**Comment by muldjord** [comment]
EDIT: I've reported it to 'mitu' myself and referred him to this issue.

Original: Please report this to 'mitu' on the retropie forums. I am not the maintainer of the RetroPie script. Closing. You can refer him to this issue as it is very well documented, so thank you for that.

Also, please remember to put a battery in your fire alarm and put it back up. :)

**Comment by 2fst4u** [comment]
Lol the smoke alarm is spare, I promise. 

Thank you for referring, I wasn't sure how to make contact.
