### ISSUE TITLE
Please add "PC Win3.xx" as a PC alias for screenscraper

### ISSUE THREAD

**Issue by quicksilver7837** [muldjord/skyscraper#137]
Currently its not possible to scrape any windows 3.1 games via screenscraper. These games are in the pc folder and run via dosbox. I would assume the issue is because windows 3.1 is not currently an alias of PC. I believe screenscraper lists as "PC Win3.xx"

**Comment by muldjord** [comment]
The alias has been added to all relevant platforms and will be in the next release. :)
