### ISSUE TITLE
forceFilename not working

### ISSUE THREAD

**Issue by jayjayuk** [muldjord/skyscraper#138]
Hi, i am pretty sure forceFilename is not working.

when i scrape screenscraper for psx with filename - "Gran Turismo 2 (USA) (Arcade Mode)"
the returned title is - Gran Turismo 2 (arcade Mode)(USA)(Arcade Mode)

if i have forceFilename="true" i get - Gran Turismo 2 (arcade Mode)(USA)(Arcade Mode)
and forceFilename="false" i get -      Gran Turismo 2 (arcade Mode)(USA)(Arcade Mode)

i have tried this in the config.ini in [main] and [screenscraper] and have also tried --forceFilename and nothing seems to work.

noBrackets works as expected and have tried using and not using this tied in with it (really just to see if i could get better output but then noticed forceFilename doesnt seem to be doing anything)

**Comment by muldjord** [comment]
It does work. But the tags returned from the source are added aswell. You can disable this with "brackets=no"

**Comment by jayjayuk** [comment]
let me clarify..

when i scrape screenscraper for psx with filename - "Gran Turismo 2 (USA) (Arcade Mode)"
the returned title from screenscraper is - Gran Turismo 2 (arcade Mode)
((Gran Turismo 2 (arcade Mode) (USA) (Arcade Mode) is what gets put in gamelist.xml))
^^^^ this is a -s scrape to gather and is the returned title from screenscraper... this seems ok

if i have forceFilename="true" i get - Gran Turismo 2 (arcade Mode)(USA)(Arcade Mode)
and forceFilename="false" i get - Gran Turismo 2 (arcade Mode)(USA)(Arcade Mode)
^^^^ these are when i leave out -s and make a gamelist, these are the titles in gamelist.xml

i have tried forceFilename while scraping and while generating, all combos, it does nothing. you also told someone else on reddit what this is meant to do... use the name of the file when generating the gamelist instead of the cached one, which means, if i generate with forceFilename="true", in emulationstation my game should be listed as...
Gran Turismo 2 (USA) (Arcade Mode)
as this is my filename without the extension. but all i can get is...
Gran Turismo 2 (arcade Mode)(USA)(Arcade Mode)
or this using brackets="false"
Gran Turismo 2


sorry i mentioned brackets which has confused this matter, brackets=true/false works fine and its not what i need.

can you clarify again how the forcefilename works.. because based on the docs and what you said on reddit, it seems do nothing

ps.
for reference
https://www.reddit.com/r/RetroPie/comments/aftxjo/in_skyscraper_there_is_an_option_to_search_for/

**Comment by muldjord** [comment]
I agree this is not optimal and I plan to change this behavious in a future version. I've added a note about it in the docs: https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md#forcefilenamefalse

**Comment by jayjayuk** [comment]
yes that helps clear things up abit, as now i see your examples are without brackets in the example it makes sense how it actually works. i think you hold all bracket info and check for the brackets="true" and just append them if needed and generate the string for gamelist. i think the forceFilename should do exactly that, display the filename exactly, and brackets should work on the two titles separately (filename and scrape return name)  and then create the gamelist title based on filename="?" first and then check for brackets="?" and then generate.

thanks for adding to the docs just to clear it up for now anyway and keep up the good work on this... so far its been doing great, scraped over 1000 unchecked files and got scrapes for all but 5. really good work. THANKS :)
