### ISSUE TITLE
Import videos un-cached

### ISSUE THREAD

**Issue by hanthecat** [muldjord/skyscraper#140]
Right now you can choose to leave images uncached but not videos.

A cacheVideos="false" line in the ini file would be great

Use case: I use emumovies sync to download my media. I would like to simply import that and then scrape thegamesgb for only descriptions.

Ideally, to avoid multiple copies of the same media, the import directory can be the roms/platform/media folder.

Process:
1. Copy new media directly into the roms/platform/media folders
2. Refresh cache, skyscraper sees new files, matches to rom
3. rewrite game xml file with new media updated

Alternate process:
1. emumovies sync downloads to somewhere locally or network mounted folder
2. skyscraper imports from that directory without copying files to skyscraper cache folder
2. skyscraper generates new xml file and copies missing media directly from network folder to media folder

**Comment by muldjord** [comment]
> Right now you can choose to leave images uncached but not videos.

You can, actually. Just don't enable them for anything other than the import module. You set `videos="true"` just for the import module by adding it to config.ini as explained in the docs.

But you *will* have to go through the Skyscraper import module to do what you want. This won't change. It won't be possible to use an external custom bunch of video files as "cache" so to speak.

EDIT: Btw, please also consider using the `--symlink` option. Described in the docs.

**Comment by hanthecat** [comment]
I appreciate the symlink option though I am curious as to why it doesnt operate the other way around. It makes sense to me to have all the media in the same place for an easier time making a backup. Storing screenshots in one place and videos in a different one seems needlessly complex.

**Comment by muldjord** [comment]
That's quite easily explained. The files in the media folder can be a combination of several images composited together. They aren't necessarily the raw input images. That's one thing. Another thing is that the file in any ES folder is part of the ES ecosystem, not the Skyscraper ecosystem. Read more about the principles behind Skyscraper here: https://github.com/muldjord/skyscraper/blob/master/docs/USECASE.md

**Comment by hanthecat** [comment]
I've read though it. Just doesn't jive with my mindset, which is ok. I was trying to minimize the size of that skyscraper ecosystem because space on a the pi is always at a premium. I was trying to leave things uncached but still expecting it to filter through to the gamelist.xml. I've got all my media already local in other folders. I was looking to skyscraper to simply put it together and make those xml files.

I just need to rethink the way I use skyscraper. Ill probably just move skyscraper to a different system and run it with the pi filesystem mounted.
