### ISSUE TITLE
Add video file size limit to config.ini

### ISSUE THREAD

**Issue by silverfr0st** [muldjord/skyscraper#142]
First of all, thank you for such wonderful game scraper!

I want to suggest the ability to limit the size of downloaded video files in config.ini. This will allow more flexibility to manage games multimedia data collection. 

Now you can configure the maximum resolution for images and which ones to download. At the same time for the video there are no additional options at all.

For instance, I don't want to store video files larger than 10MB. At the moment I have to manually remove them for each platform. And if I want to check for updates, then I will need to wait until these big video files are downloaded again only to erase them once more. This makes no sense.

For some platforms, video files take up more than 10GB. Having the ability to limit the maximum size for video files, everyone can choose a reasonable limit for each platform.

I hope that this feature will seem useful to you and will be implemented in the next versions! Thanks!

**Comment by muldjord** [comment]
I've now implemented a `videoSizeLimit` config variable that can be set in both main, platform and module sections. It allows you to set a data limit in MB's (eg `videoSizeLimit="10"` for 10 megs max). If the size of a downloaded video exceeds this limit while gathering data, it will not cache the file. If it's not cached it will say so in the output aswell.

This will be in 3.1.5 when it's released at some point.

**Comment by silverfr0st** [comment]
Wow, that was quick! Thank you very much!

**Comment by muldjord** [comment]
3.2.0 has just been released with this feature implemented. :)
