### ISSUE TITLE
Assertion `mType == FLODER' failed.

### ISSUE THREAD

**Issue by the-real-dje33** [muldjord/skyscraper#145]
**Describe the bug**

I'm trying to scrap ScummVM games.
When I restart my retropie I have the following error.
Emulationstation: home/pi/retropiesetup/tmp/build/emulationstation/es-app/src/filedata.cpp:216: void Filedata::addchild(filedata*): Assertion `mType == FLODER' failed.

if I delete the gamelist.xlm file everything works again

**To Reproduce**
use this gamelist.xml
https://pastebin.com/1R5pSNeW

**Special circumstances**
scrapp in french

**Technical information**
 - Skyscraper version: 3.1.4

 - Internet connection: [ASDL]
 - OS: [RetroPie]
 - OS Version [e.g. 4.4.12]

**Comment by muldjord** [comment]
Quickly looked into the gamelist you provided. The XML passes xmllint (an XML parser and error checker) so I'm not sure what that error is. The file Skyscraper generates is correct and valid XML, so it has to be something else. Maybe related to some of your artwork files. Maybe some of them weren't saved correctly due to whatever. Have you checked that you have enough free space left?

**Comment by the-real-dje33** [comment]
I have enough free space
/dev/root           15G    8,6G  5,3G  62% /

I think I found the problem

if I replace` &apos;  `everything works

ex :
```
"l&apos;apprenti pirate Guybrush" don't works
"l'apprenti pirate Guybrush" works
```

**Comment by muldjord** [comment]
That is very odd. This is an ES issue then. The `&apos;` is valid XML and *should* be `&apos;` as it is a special character in XML. I wonder if they've changed something recently that made this work like this. In that case it's a regression in my opinion.

**Comment by muldjord** [comment]
[Here's](https://www.advancedinstaller.com/user-guide/xml-escaped-chars.html) a random link about what I am talking about. It is ok to not have them escaped in the text however. But it certainly should *not* crash if it is... That really bothers me, as I use an xmlEscape routine on all the stuff I put in the XML. If suddenly it crashes if it's escaped in some places, I'll need to handle thos cases differently. Bollocks!

**Comment by muldjord** [comment]
Just tested this on my own system by adding some `&apos;` to the `<desc>` nodes. It works fine as it should and the `&apos;` is converted to `'` in the ES gamelist. Not sure why it crashes on your setup. If you could locate precisely which `&apos;` that seems to be causing the problem I could look further into it.

**Comment by the-real-dje33** [comment]
I'll do some testing this week

**Comment by the-real-dje33** [comment]
I think it's an emulationstation bug
If i check "parse gamelists only" everything works 
I made a post on retropie forum.
