### ISSUE TITLE
missing brackets to 'name' on skipped entries

### ISSUE THREAD

**Issue by hexive** [muldjord/skyscraper#146]
Skyscraper v3.1.4 on Retropie 4.4

Skipped entries 'name' do not include brackets.

I tested setting brackets="true" in config.ini and with no brackets setting in config.ini  (default true).

Filename:
`A Bug's Life - Cracked (Unl) v1 dforce3000.sfc`

Returned XML:
```
<?xml version="1.0"?>
<game>
    <path>./A Bug&apos;s Life - Cracked (Unl) v1 dforce3000.sfc</path>
    <name>A Bug&apos;s Life - Cracked</name>
    <cover />
    <image />
    <marquee />
```

**Comment by muldjord** [comment]
Just don't skip them. Unless you have a reason to, it's always best to let it process everything again. Otherwise you'll encounter inconsistencies like this sometimes. Skipping means exactly what it says. It will skip them, and not process them. Which leaves them intact and, in this case, without the brackets.

**Comment by hexive** [comment]
I apologize, I may have used the wrong terminology.

I'm using skipped="true" in order to include skipped entries when writing final game list. I have a large romset and emulationstation loads 50% faster when only looking at gamelist xml instead of also doing a filecheck so its important to have all files included in the xml.

I thought the intended behavior of brackets="true" combined with skipped="true" would be to return file brackets in names of roms that have successfully been scraped as well as brackets in names of roms that could not be successfully scraped.

Thanks for your time!

**Comment by muldjord** [comment]
Thanks for the clarification. When a game is skipped it currently happens before the brackets are processed. This is the reason. I'll add a note of it and depending on whether it brings with it other problems, I might change this in the next release. Thanks for letting me know.

EDIT: I just looked over the code and I don't see any problems in processing the filename brackets prior to the skip check. So this should work from the next release.
