### ISSUE TITLE
Satellaview support

### ISSUE THREAD

**Issue by LordPinkerton** [muldjord/skyscraper#147]
Would like to see supported added for Satellaview. I have read through all the documentation and can't see how to currently scrape these roms. ScreenScrape has a database for them, but I'm unsure if these are being queried when scraping my snes folder, as all are skipped with no info found. I even tried using a --query with checksums and file names and nothing. Unless the ability already exists and I'm just doing something very wrong.

**Comment by muldjord** [comment]
Just tested this and it works fine here. You must have run out of requests or hit some other limit. The Satellaview is, as you mention, a snes platform. And it has been part of Skyscraper as an alias for a long time. As long as you add your files to the roms/snes folder, it works.
