### ISSUE TITLE
Not scraping right game. Force scrape?

### ISSUE THREAD

**Issue by LordPinkerton** [muldjord/skyscraper#148]
I am trying to scrape the game "Jungle Book 2, The (Europe) (En,Fr,De,Es,It,Nl).gba". However, skyscraper always pulls this up as Jungle Book, the original for the GBA instead of the EU second part. I have tried using the query using the md5, rom name, sha1, but it always comes up with the same wrong version. Is there any other method of forcing the scraper to use a specific checksum variable as the scraping information? I also have played around with various match percentages, and nothing helps.

**Comment by muldjord** [comment]
Try checking this out, it might help you: https://github.com/muldjord/skyscraper/blob/master/docs/REGIONS.md

Good luck!

**Comment by LordPinkerton** [comment]
While I appreciate the reply and information, I have already tried changing the region priority as I know this was an eu game. This has not helped. In a folder labeled gba on it's own, I tried the following command.
Skyscraper -p gba -s screenscraper --region eu

I have also tried a query.
Skyscraper -p gba -s screenscraper --query md5=1A2C640094216F9D15DC7A2AC3B8C1E0 "/home/pi/RetroPie/roms/gba/Jungle Book 2, The (Europe) (En,Fr,De,Es,It,Nl).gba"

I have cleared the gba cache and gamelist entirely. Either way, it always comes up as the first US game.

**Comment by muldjord** [comment]
Just looked up that particular MD5. It is mapped incorrectly in Screenscraper to "Jungle Book" and I can't remap it to "Jungle Book 2" as such a game doesn't exist in their database. In other words, this is not a Skyscraper issue, it is a Screenscraper issue and should be fixed on their end.
