### ISSUE TITLE
Add arcadia, crvision, astrocde platforms

### ISSUE THREAD

**Issue by raphkoster** [muldjord/skyscraper#149]
All three of these are playable under MESS, and crvision and arcadia are even past of the default install of lr-mess.

**Comment by muldjord** [comment]
I've added 'arcadia' and 'astrocde' to the upcoming 3.1.5 release. :)

Neither TheGamesDb nor ScreenScraper supports 'crvision' so I can't add it as I don't know what aliases or platform ID's they would be using. They need to support them before I can. Let me know if you know something I don't.

**Comment by raphkoster** [comment]
You appear to be correct, I can't find any of the platform's games on either of the two databases. Something to fix when I have a rainy day! :)
