### ISSUE TITLE
internal ScreenScraper names containing '/' or '()' cannot be found by Skyscraper

### ISSUE THREAD

**Issue by kcgen** [muldjord/skyscraper#150]
For example, **_Disney / Pixar - Toy Story 2 - Buzz Lightyear To The Rescue!_** exists on screenscraper for platform PSX:

 https://www.screenscraper.fr/gameinfos.php?gameid=19320&action=onglet&zone=gameinfosinfos

Because of the slash in screenscraper's internal name, skyscraper appears unable to find a match for it. I tried the following filenames:

- Disney-Pixar - Toy Story 2 - Buzz Lightyear To The Rescue!
- Disney Pixar - Toy Story 2 - Buzz Lightyear To The Rescue!
- DisneyPixar - Toy Story 2 - Buzz Lightyear To The Rescue!
- Disney - Toy Story 2 - Buzz Lightyear To The Rescue!
- Pixar - Toy Story 2 - Buzz Lightyear To The Rescue!

- Disney-Pixar - Toy Story 2 - Buzz Lightyear To The Rescue!
- Disney Pixar - Toy Story 2 - Buzz Lightyear To The Rescue!
- DisneyPixar - Toy Story 2 - Buzz Lightyear To The Rescue!
- Disney - Toy Story 2 - Buzz Lightyear To The Rescue!
- Pixar - Toy Story 2 - Buzz Lightyear To The Rescue!

- Disney-Pixar Toy Story 2 - Buzz Lightyear To The Rescue!
- Disney Pixar Toy Story 2 - Buzz Lightyear To The Rescue!
- DisneyPixar Toy Story 2 - Buzz Lightyear To The Rescue!
- Disney Toy Story 2 - Buzz Lightyear To The Rescue!
- Pixar Toy Story 2 - Buzz Lightyear To The Rescue!

- Disney-Pixar Toy Story 2 - Buzz Lightyear To The Rescue!
- Disney Pixar Toy Story 2 - Buzz Lightyear To The Rescue!
- DisneyPixar Toy Story 2 - Buzz Lightyear To The Rescue!
- Disney Toy Story 2 - Buzz Lightyear To The Rescue!
- Pixar Toy Story 2 - Buzz Lightyear To The Rescue!

- Disney-Pixar - Toy Story 2 - Buzz Lightyear To The Rescue!
- Disney Pixar - Toy Story 2 - Buzz Lightyear To The Rescue!
- DisneyPixar - Toy Story 2 - Buzz Lightyear To The Rescue!
- Disney - Toy Story 2 - Buzz Lightyear To The Rescue!
- Pixar - Toy Story 2 - Buzz Lightyear To The Rescue!

- Disney-Pixar - Toy Story 2 - Buzz Lightyear To The Rescue!
- Disney Pixar - Toy Story 2 - Buzz Lightyear To The Rescue!
- DisneyPixar - Toy Story 2 - Buzz Lightyear To The Rescue!
- Disney - Toy Story 2 - Buzz Lightyear To The Rescue!
- Pixar - Toy Story 2 - Buzz Lightyear To The Rescue!

- Disney-Pixar Toy Story 2 : Buzz Lightyear To The Rescue!
- Disney Pixar Toy Story 2 : Buzz Lightyear To The Rescue!
- DisneyPixar Toy Story 2 : Buzz Lightyear To The Rescue!
- Disney Toy Story 2 : Buzz Lightyear To The Rescue!
- Pixar Toy Story 2 : Buzz Lightyear To The Rescue!

- Disney-Pixar Toy Story 2 : Buzz Lightyear To The Rescue!
- Disney Pixar Toy Story 2 : Buzz Lightyear To The Rescue!
- DisneyPixar Toy Story 2 : Buzz Lightyear To The Rescue!
- Disney Toy Story 2 : Buzz Lightyear To The Rescue!
- Pixar Toy Story 2 : Buzz Lightyear To The Rescue!

```
------------------------------------------
Running Skyscraper v3.1.4 by Lars Muldjord
------------------------------------------
Platform:           'psx'
Scraping module:    'screenscraper'

Reading and parsing resource cache, please wait...
Successfully parsed X resources!

Looking for optional 'priorities.xml' file in cache folder... Found!
Priorities loaded successfully!

Starting scraping run on 1 files using 1 threads.
Sit back, relax and let me do the work! :)

#1/1 (T1) Pass 1 ---- Game 'Disney-Pixar - Toy Story 2 - Buzz Lightyear to the Rescue! (USA)' not found :( ----
```

Whenever a screenscraper internal name contains a slash / or special characters like (...), screenscraper is unable to find it.

**Comment by muldjord** [comment]
This works fine for me it is not related to the / or () as you mention. Please use one of the filenames that exist on their website. Psx is notoriously difficult to scrape, as it doesn't work by using checksums since many ISO's vary in size (and other reasons). So it relies in the filename instead. And in this case, it works just fine if you, for instance, use the filename "Disney-Pixar's Toy Story 2 - Buzz Lightyear to the Rescue! (USA).cue".

**Comment by kcgen** [comment]
Thanks Lars,  I wasn't seeing how you figured out to use the possessive form of **Disney-Pixar's** given all the titles shown at https://www.screenscraper.fr/gameinfos.php?gameid=19320&action=onglet&zone=gameinfosinfos
are listed unpossessively as **Disney-Pixar**.

Then I saw the link to ROMs on the same page (just above the list of titles), and indeed I see the filenames such as you reported here.  This is a huge help; I can now manually rename my dumps to match those in the ROM list, as opposed to using the title names.

I suppose Skyscraper uses ROM name matches instead of title matches? (maybe it could search both lists if the API allows?).

Regards.

**Comment by muldjord** [comment]
> I suppose Skyscraper uses ROM name matches instead of title matches? (maybe it could search both lists if the API allows?).

It does in the case of ScreenScraper, but it varies depending on source. You can check the details [here](https://github.com/muldjord/skyscraper/blob/master/docs/SCRAPINGMODULES.md).

Good luck with it! :)
