### ISSUE TITLE
Discrepancy between screenscraper and cache for psx

### ISSUE THREAD

**Issue by Sinistral2099** [muldjord/skyscraper#151]
**Describe the bug**
I have a US PSX full rom set in PBP and CHD format. When I scrape them with screenscraper, I get 66 not found. This is expected. When I then scrape the same roms with the localdb to build the gamelist, I get 457 skipped.

**To Reproduce**
I have rerun the commands over and over trying to correct the discrepancy between the two. I have not yet tried to query the individual missing roms. The exact commands used to reproduce this were:
Skyscraper -s screenscraper -p psx
Skyscraper -s localdb -p psx

**Special circumstances**
Is your system set up in any special manner that could interfere with how Skyscraper works?

**Terminal output**
If applicable, add terminal output to help visualize your problem.

**Technical information**
 - Skyscraper version: 3.1.4
 - Internet connection: Cable 100Mbps
 - OS: Ubuntu
 - OS Version 18.04

**Additional context**
This does not happen with any other platform.

**Comment by muldjord** [comment]
Try with '-m 0'

**Comment by Sinistral2099** [comment]
Still skipped 470 with local db when using -m 0. To be clear, it finds them and downloads the art into the cache. It fails to build the image from localdb for some reason though.
