### ISSUE TITLE
Purge single rom?

### ISSUE THREAD

**Issue by tukicat** [muldjord/skyscraper#154]
Is there anyway to purge a single rom, rather than a whole system? At the moment the only way I can think of doing it is by deleting the rom, vacuuming that system, and the replacing the rom.

**Comment by tukicat** [comment]
Is there anyway to purge a single rom, rather than a whole system? At the moment the only way I can think of doing it is by deleting the rom, vacuuming that system, and the replacing the rom.

**Comment by muldjord** [comment]
Use `--cache edit "<ROM FILENAME>"`. Please read the documentation here for more info: https://github.com/muldjord/skyscraper/blob/master/docs/CLIHELP.md#--cache-edit
