### ISSUE TITLE
Prompt loop on first run

### ISSUE THREAD

**Issue by thadboyd** [muldjord/skyscraper#160]
On first run, 3.2.5 displays the prompt:

> Please enter the frontend you wish to scrape for (enter for 'emulationstation'):

Regardless of how I answer, it just repeats the prompt.  I've tried just hitting enter, I've tried typing out `emulationstation`, I've also tried `EmulationStation`, `Emulationstation`, `'emulationstation'` in single quotes, `attractmode`, `pegasus`, `1`, `2`, `3`, and `*`.  No difference; all inputs just bring the same prompt back up.  Eventually I just hit Ctrl-C to kill the program (which doesn't exit cleanly; it outputs `Segmentation fault (core dumped)` when I hit Ctrl-C).

Tested on Manjaro ([AUR package](https://aur.archlinux.org/packages/skyscraper-git/)) and Debian Buster (compiled using `wget -q -O - https://raw.githubusercontent.com/muldjord/skyscraper/master/update_skyscraper.sh | bash`).  Both are version 3.2.5 and exhibit the same behavior.

**Comment by muldjord** [comment]
Thank you for reporting this. This is a bug. I will fix it.

**Comment by muldjord** [comment]
This has now been fixed. Please update to 3.2.6 and try again.

**Comment by thadboyd** [comment]
Fix confirmed in 3.2.6.  Thanks!
