### ISSUE TITLE
screenscraper.fr "standarized video"

### ISSUE THREAD

**Issue by JuanVCS** [muldjord/skyscraper#162]
Would it be possible for the screenscraper.fr module to default fetching the "standarized video" where available? It's suffixed as video-normalized.mp4

The format is much more consistent (framerate, dimensions, lenght), and sometimes the only video available - as I noticed with Killer Instinct on the SNES, where skyscraper didn't fetch a video.

**Comment by muldjord** [comment]
Sounds interesting, I will look into it. Thanks for the heads up.

**Comment by muldjord** [comment]
3.3.0 now released, that tries for "video-normalized" first and then falls back to "video" afterwards if normalized wasn't found.
