### ISSUE TITLE
Add platform pc98

### ISSUE THREAD

**Issue by leosmeira** [muldjord/skyscraper#165]
Source: https://www.igdb.com/platforms/pc-98

**Comment by muldjord** [comment]
It has been added on master. It will be in 3.2.9 when it's officially released. Thanks for the suggestion.

**Comment by leosmeira** [comment]
Skyscraper don't generate gamelist.xml to platform pc98

*Tested in*: Skyscraper master (14/09/2019) / Ubuntu 19.04
*Command:* Skyscraper --unattend --skipped -g /home/leonardo/.emulationstation/gamelists/pc98 -o /home/leonardo/.emulationstation/downloaded_media/pc98 -p pc98

**Comment by muldjord** [comment]
3.3.0 out now with this platform added

**Comment by leosmeira** [comment]
Thank's. It worked very well

Em dom, 15 de set de 2019 15:24, Lars Muldjord <notifications@github.com>
escreveu:
