### ISSUE TITLE
Add platform pokemini

### ISSUE THREAD

**Issue by leosmeira** [muldjord/skyscraper#166]
**Sources:**
https://www.mobygames.com/browse/games/pokemon-mini/
https://thegamesdb.net/list_games.php?platform_id=4957
https://www.igdb.com/platforms/pokemon-mini

**Comment by muldjord** [comment]
Added. it's on master and will be in 3.2.9.

**Comment by leosmeira** [comment]
Thank's. 
Where is the commit?

**Comment by muldjord** [comment]
Just use the latest master. 3.2.9 is not out yet, but it works on the master branch.

EDIT: Sorry, I had forgotten to push the commit. *Now* it's on master.

**Comment by muldjord** [comment]
3.3.0 out now with this platform added

**Comment by leosmeira** [comment]
Thank's. It worked very well

Em sex, 13 de set de 2019 17:32, Lars Muldjord <notifications@github.com>
escreveu:
