### ISSUE TITLE
Skyscraper don't generate gamelist.xml to platform pc98

### ISSUE THREAD

**Issue by leosmeira** [muldjord/skyscraper#167]
Skyscraper don't generate gamelist.xml to platform pc98

**Describe the bug**
The Skyscraper hangs and does not generate the gamelist nor return error.
See print: https://imgur.com/a/z9LIluu

**To Reproduce**
Skyscraper --unattend --skipped -g /home/leonardo/.emulationstation/gamelists/pc98 -o /home/leonardo/.emulationstation/downloaded_media/pc98 -p pc98

**Technical information**
 - Skyscraper version: Master (14/09/2019)
 - OS: Ubuntu 19.04 with RetroPie 4.5

**Additional context**
List of roms: https://file.io/CLBjBv

**Comment by muldjord** [comment]
Please try again on the updated master. I think I just fixed this. I had forgotten a crucial addition in the platforms definitions file, my bad. Thanks for reporting this.

**Comment by muldjord** [comment]
3.3.0 out now with this platform added
