### ISSUE TITLE
Default rom directory change

### ISSUE THREAD

**Issue by Jmanning6600** [muldjord/skyscraper#17]
My question is when scraping a already scraped rom set how do you change the default directory if the directory used is not the default?

**Comment by Jmanning6600** [comment]
for example Skyscraper searches for /home/pi/RetroPie/roms/n64' by default i need it to search /home/pigaming/RetroPie/roms/n64 is there any way to make this happen?

**Comment by muldjord** [comment]
Read the documentation

**Comment by muldjord** [comment]
"-i" does exactly what you want, but please spent some time reading the output of "--help". These are basic functionalities and are well documented. No need to create an issue for this.
