### ISSUE TITLE
PSX .bin extension as default

### ISSUE THREAD

**Issue by HoshiQaVam** [muldjord/skyscraper#171]
I've noticed that quite a few PSX rom files are shared as .bin files. Of 20 PSX rom files that I have, 17 are .bin and only 3 are .img.

As .bin is not currently a default accepted extension for PSX (though is for other platforms like Megadrive), skyscraper is only finding 3 of my 20 PSX files to scrape.

I appreciate that I can modify the ini file to force skyscraper to look for .bin, or I can go through the frustrating process of converting all of the .bin roms to .img or .iso, but given the high proportion of PSX rom files that appear to be .bin I am surely not the only person with this issue. It would therefore be helpful if .bin became a default.

**Comment by muldjord** [comment]
Hi, yeah, I am aware of this actually. The problem being that .bin files are very often accompanied by a .cue file for the PSX platform. If I add .bin it will suddenly look for the game twice and also add the game to the gamelist twice. So I've left it out for this reason. You can imagine the mess that would cause for people who only have cue+bin pairs of games (which is many, many cases).

**Comment by HoshiQaVam** [comment]
How about adding an "excludeExtension" variable either globally or per-system so that we can force the .cue file to be ignored?

**Comment by BenMcLean** [comment]
What would be the correct syntax to include or exclude BIN?

**Comment by muldjord** [comment]
It's documented [here](https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md#extensionszip-uae-adf). You would add the following to your `~/.skyscraper/config.ini` to completely overwrite the extensions for the psx platform. You can also use `addExtensions` which appends extensions to those already supported.
```
[psx]
extensions="*.bin"
