### ISSUE TITLE
Gamecube GCM file extension not recognised

### ISSUE THREAD

**Issue by mrsilver76** [muldjord/skyscraper#173]
Gamecube image files can use the GCM file extension - which is, technically, just a renamed ISO. However Skyscanner v3.3.0 (Windows) doesn't recognise that extension and so skips over the files.

The obvious workaround (which works) is editing `config.ini` to add:

```
[gc]
addExtentions="*.gcm"

```
Although it would be nice if you could add it to the defaults please!

**Comment by muldjord** [comment]
Thanks for pointing this out. I've added it by default for Gamecube and it will be in the next release, no ETA.
