### ISSUE TITLE
Tar failing in the update script per instructions

### ISSUE THREAD

**Issue by davidmgrantham** [muldjord/skyscraper#175]
**Describe the bug**
In the README.md you have instructions to use "brew install gnu-tar --with-default-names"
The --with-default-names seems to have been deprecated. 

The solution I have found is to simply remove --with-default-names from the brew command.
Then update the update_skyscraper.sh script to call gtar directly. 

Line 20: gtar xvzf ${LATEST}.tar.gz --strip-components 1 --overwrite

I tried to push a commit for this for a PR but I lack the rights to do so.

**To Reproduce**
Follow instructions for Mac OSX

**Terminal output**
`3.3.2.tar.gz                                 [    <=>                                                                           ]   2.22M  2.77MB/s    in 0.8s

Last-modified header missing -- time-stamps turned off.
2019-11-20 12:42:31 (2.77 MB/s) - ‘3.3.2.tar.gz’ saved [2324611]

--- Unpacking ---
tar: Option --overwrite is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help`

**Technical information**
 - Skyscraper version: [3.3.2]
 - OS: [OSX Mojave]
 - OS Version [10.14.6]

**Comment by muldjord** [comment]
Thanks, I've updated the readme slightly to reflect this. Closing.
