### ISSUE TITLE
Thegamesdb got unplugged

### ISSUE THREAD

**Issue by zkvsky** [muldjord/skyscraper#179]
It's going to be down for weeks it seems

**Comment by muldjord** [comment]
Thanks for letting me (and others reading this) know. Hopefully they will be back online soon.

**Comment by rfrayer420** [comment]
That is sad, it doesnt change the fact this one dope scraper.

**Comment by tv21** [comment]
It seems TheGamesDB is back up, but for some reason skyscraper usually only seems to get cover art and not any other kind of art that may be available.

**Comment by muldjord** [comment]
Thanks for the update. :)
I've been looking into this and it seems TheGamesDb also supports clearlogo and banners, which would be wheel and marquee for Skyscraper. These will be supported in 3.4.1. Thanks for pointing it out tv21

**Comment by muldjord** [comment]
I've been looking into this and it seems TheGamesDb also supports clearlogo and banners, which would be wheel and marquee for Skyscraper. I will try to support those as well.

**Comment by zkvsky** [comment]
It's alive, so let's close this?

**Comment by muldjord** [comment]
Yep, it's back up and running. :)
