### ISSUE TITLE
Update gamelist only with changes, not rewriting it

### ISSUE THREAD

**Issue by stuffu** [muldjord/skyscraper#180]
When scraping a single rom it would be awesome just to add that new or updated rom to gamelist.xml instead of writing a new xml every time.

I guess there are more people than me who makes adjustments to the scraper data (file names etc) and you need to redo this every time ju update a platform with a single rom and you can then also skip the time needed to write from cache again.

Also, when space is an issue the cache folders are tempting to remove but doing that will result in that all cache needs to be downloaded again (and using resources from the api limits) when updating just a single rom.

Maybe it isn't possible for some reason but that would be awesome.

Speaking of awesome, thanks for the amazing work you are doing with Skyscraper!

**Comment by muldjord** [comment]
It's a nice idea, but I'm not interested in implementing this for the following reason:
The basic idea with Skyscraper is to have the data in one place (the resource cache) and use that data to generate gamelists for several frontends or whenever you change your setup (artwork, naming scheme, whatever). So basically you are not doing it "the Skyscraper way" when you are editing the gamelist.xml directly. Instead, you should edit the cached data for the rom using Skyscraper:
```
Skyscraper -p <PLATFORM> --cache edit <FILENAME>
```
This will bring up the resource editor, allowing you to add and change data for any resource related to the rom. Consider using this method instead.

**Comment by zkvsky** [comment]
@muldjord I've been reading upon custom data import and it's sorta kinda what I want but not sure yet.
Ideally I'd like to have something akin to custom/personal cache, which would always be checked first and take priority over anything else.

**Comment by muldjord** [comment]
@barolo I'm not referring to the import module. I'm referring to the cache edit as mentioned above, which is *exactly* what you described. :) Please check it out. It adds user-defined resources to the cache of any textual type, which will always be prioritized above anything else.

EDIT: Added a very important "not" at the beginning.

**Comment by zkvsky** [comment]
@muldjord Gotcha, thanks!, Imma test it out later.
Btw, screenscraper [ with account ] started pulling 0b wheels/logos for me, not sure what's up with that yet

**Comment by stuffu** [comment]
Thanks, I see the reason not to implement it. Will try the import module...

**Comment by muldjord** [comment]
@stuffu, no, please use `--cache edit <filename>` instead. The import module if mostly for media such as artwork and videos. It also works for textual data, but the cache edit feature is much more suited and easier to use for textual data.

EDIT: It's fully documented [here](https://github.com/muldjord/skyscraper/blob/master/docs/CLIHELP.md#--cache-editnewtype)
