### ISSUE TITLE
Artwork.xml is operwritten on updates.

### ISSUE THREAD

**Issue by teeedubb** [muldjord/skyscraper#182]
**Describe the bug**
A clear and concise description of what and where the bug is.
Artwork.xml is overwritten when Skyscraper is updated via the included update script.

**To Reproduce**
Can you reproduce this behaviour? If so, how? What EXACT command did you run that gave the error?
Modify artwork.xml update/force update Skyscraper and view artwork.xml

**Special circumstances**
Is your system set up in any special manner that could interfere with how Skyscraper works?

**Terminal output**
If applicable, add terminal output to help visualize your problem.

**Technical information**
 - Skyscraper version: [e.g. 2.4.9] v3.3.4

**Additional context**

**Comment by muldjord** [comment]
The Skyscraper update script does not touch the `~/.skyscraper/artwork.xml`file and neither does Skyscraper if it already exists in `~/.skyscraper`. Are you maybe editing the raw file in `~/skysource`? Please don't alter any of the files in `~/skysource`. The script _will_ overwrite them the next time you update (as it should, it's a source download directory).

Here's the Skyscraper code that checks the current artwork.xml:
```
  current = "artwork.xml";
  distro = "/usr/local/etc/skyscraper/artwork.xml";
  copyFile(distro, current, false); // False means it won't overwrite if it exists
```
As you can see it has `false` set which indicates that this file should only be copied if it doesn't already exist. And all the update script does is download the latest release, unpack it, compile it and install all of the files into the `/usr/local/etc/skyscraper` folders so Skyscraper can find them when it runs.

Let me know if I am missing something here.

**Comment by teeedubb** [comment]
Hi and Merry Xmas,

The dir ~/skysource does not exist on my machine and the artwork.xml file is in ~/.skyscraper. From memory Skyscraper was installed via the script in the git repo. I'll try reinstalling and see what happens.

**Comment by muldjord** [comment]
It might be that it is the script that overwrites it then, I don't know. I am not the maintainer of the script. You can try asking the user 'mitu' on the retropie forums if this issues persists for you.
