### ISSUE TITLE
Separate Out MSX Platforms

### ISSUE THREAD

**Issue by davidmgrantham** [muldjord/skyscraper#183]
**Describe the feature**
Separate out MSX platforms.
I currently have my msx and msx2 system separated in es_system.cfg. When trying to scrape i get the following.

"Please set a valid platform with '-p [platform]'"

**Additional context**
Im assuming i could rename this folder to msx and possibly be able to scrape on my .mx2 backups then rename back to msx2. I'll try this first.

**Comment by muldjord** [comment]
It will stay as one platform, but I might implement some sort of platform aliases at some point. Currently you can set a temporary input folder with `-i <inputfolder>`. Just remember to set the same input folder when generating the gamelist afterwards. Or, as you mention, rename the folder temporarily.

**Comment by mixpc** [comment]
Hi,

I've just seen this topic is related to [mine](https://github.com/muldjord/skyscraper/issues/291
) as well.
For reference, these are the two steps that I follow to achieve the goal:

```
# 1.- Scrap
skyscraper -p arcade -s screenscraper -i '/home/user/RetroPie/roms/mame2003-lite-retropie'

# 2.- Create gamelist. Images stored in an external USB drive
skyscraper -p arcade -i '/home/user/RetroPie/roms/mame2003-lite-retropie' \
-g '/home/user/.emulationstation/gamelists/mame2003-lite-retropie' \
-o '/media/usbdrive/RetroPie/media/mame2003-lite-retropie'
```

Of course, anyone could customize it to their own liking.

So @muldjord thank you for your great software and no rush about this feature request as this workaround is fully functional.

Regards,

**Comment by muldjord** [comment]
3.6.10 out now with `msx2` as platform. Please test. Closing this, reopening if errors reported.
