### ISSUE TITLE
Screenscraper json has changed (fixed)

### ISSUE THREAD

**Issue by Micket** [muldjord/skyscraper#184]
Since I was unsuccessful at scraping any games from screenscraper (despite verifying that the md5sum's where correct), I did some digging. As far as I can see, this
https://github.com/muldjord/skyscraper/blob/master/src/screenscraper.cpp#L170
is now outdated. Dumping the json, I can see that I actually do find the game, but the json now contains both id and name;
```json
"systeme": {"id": "3", "text": "NES"},
```
thus this fixes the problem
```cxx
game.platform = jsonObj["systeme"].toObject()["text"].toString();
```
After making this change, everything worked perfectly.

By the looks of the code, it seems to be that this check is actually not necessary, as it already verifies that a proper title is set, and this platform value field is supposedly never wrong.

**Technical information**
- Skyscraper 3.3.4
- OS: Fedora 31

**Comment by muldjord** [comment]
Thank you for letting me know. I don't use Skyscraper on a daily basis so I rely on these info from you guys. Thanks!

3.3.5 has been released with this update included. I will let this stay open for the time being, so others can see it.

**Comment by Wood578Guy** [comment]
Thanks for fixing this!  I was having all kinds of trouble getting screenscraper to work yesterday, now it's all fixed!
