### ISSUE TITLE
Add flag to output ~/.skyscraper/skipped-screenscraper.txt to gamelist directory instead

### ISSUE THREAD

**Issue by parker-hemphill** [muldjord/skyscraper#185]
When I scrape I create a list of my systems and loop through them.  On each system scrape it creates ~/.skyscraper/skipped-screenscraper.txt but then clobbers the file with the next system.  I'm asking for the option to set a flag to either save the file to a new location or append the system name to it.  I looked through the command line switches and didn't see an option for doing this.  Looking back I could have added a command in the loop to move that file manually but this seems like a good idea for novice users that can't do things like loops.

**Comment by muldjord** [comment]
This makes sense, I will include the platform in the filename from 3.3.6. Thanks.

**Comment by parker-hemphill** [comment]
This works perfectly.  Thanks!
