### ISSUE TITLE
Skyscraper found nothing on Screenscraper

### ISSUE THREAD

**Issue by mkspawn** [muldjord/skyscraper#190]
Hello,
when i use skyscraper without edit config.ini then working.
But when i only use my login details for sreenscraper api, then then there find my account and 6 threats but found nothing,
i got only message
Screenscraper Apiv2 returned invalid / empty JSON.
I dont know when was the last update, but i know that has worked last month.
Thanks.

**Comment by muldjord** [comment]
Hi, this is a screenscraper issue. They are having a lot of trouble with their servers and it's hit and miss what works and what doesn't. It works for me right now, but only for textual resources not for media. And their login server works too.

Please just try again later.

**Comment by mkspawn** [comment]
Hello, but why work this with free account and its found but when i user my credentials then its found nothing more.

**Comment by muldjord** [comment]
Because they have different ways to handle users and some of them are working, others aren't. If you want more specific information you can go to their discord. :)

**Comment by mkspawn** [comment]
Hmm i test again my pass was wrong but with API he knows which user and how
much threats i have but worked not.

Lars Muldjord <notifications@github.com> schrieb am Sa., 25. Jan. 2020,
20:42:

**Comment by muldjord** [comment]
Yes, because the API is down or unstable. This is exactly the issues they are having. Just wait a few weeks until it gets back to a stable state again.

**Comment by mkspawn** [comment]
I use the scraper from screenscraper direct with thats it working well.
You can close the ticket

Lars Muldjord <notifications@github.com> schrieb am So., 26. Jan. 2020,
02:07:

**Comment by muldjord** [comment]
Yes, and it works with Skyscraper as well too, since their API is now up and running again. Again, this was not a Skyscraper issue. I just tested it, and it works fine.

**Comment by mkspawn** [comment]
OK very good.

Lars Muldjord <notifications@github.com> schrieb am So., 26. Jan. 2020,
15:22:
