### ISSUE TITLE
Try alternate database if first comes up empty, also try alternatives in case of numbers.

### ISSUE THREAD

**Issue by tv21** [muldjord/skyscraper#192]
Would very much appreciate if Skyscraper could first try ScreenScraper but if that comes up empty for a particular game then automatically try TheGamesDb (and also I will note that  Skyscraper usually seems to fail to get artwork other than cover art from TheGamesDb).

Also it would be nice if Skyscraper could try a couple of variations if it doesn't get any results, in particular, if the title contains a number as either a normal number or a Roman numeral try substituting the opposite.  For example if you have "Some Game 3" and it fails try "Some Game III" or vise versa because quite often that is an issue with games with numbers in the titles.  I realize it would be easier if the databases themselves would take into account all possible variations when searching but since they don't seem to, maybe you could try at least that particular alternative.  With Roman numerals I would maybe only try a substitution to a normal number if they are the last thing in the title OR the last thing to appear prior to a colon character(:), particularly with the letter I which could be the number 1 but usually isn't.

**Comment by muldjord** [comment]
1. Skyscrapers core design does not allow for this (and to make it do this would require an insane amount of code rewriting, not gonna do that, sorry). Instead run it several times with different sources as described [here](https://github.com/muldjord/skyscraper/blob/master/docs/USECASE.md)

2. Skyscraper already does this (pretty much _exactly_ as you describe) and does it quite well. Please run it with `--verbosity 3` to see which variations it is trying with. Keep in mind that it only works for the search-based scraping modules as described [here](https://github.com/muldjord/skyscraper/blob/master/docs/SCRAPINGMODULES.md). If you have a specific example of a filename that should work, please provide it so I can test it.
