### ISSUE TITLE
Retropie (Raspberry pi 4) - cant scrape symbolic links on usb subdirectories

### ISSUE THREAD

**Issue by rhunjadi** [muldjord/skyscraper#195]
**READ BEFORE YOU POST**
Do not ask questions on how to use Skyscraper here. This is for BUG / ERROR reports only. Skyscraper questions can be asked at the RetroPie forums (https://retropie.org.uk/forum) where other users might be able to help you out.

Before you do, please read the documentation (https://github.com/muldjord/skyscraper/tree/master/docs) thoroughtly. Every feature and option is documented down to the last detail.

If you've encountered a bug, please take your time to describe it well using the following template. If not, it will be deleted without response.

**Describe the bug**
**Skyscraper dosn't  parse symbolic link directories.** 

**To Reproduce**
Can you reproduce this behaviour? If so, how? What EXACT command did you run that gave the error?

I have created symlink for a dreamcast directory on usb:
`home/retropie/roms/ln -s /media/usb0/roms/dreamcast/* dreamcast`

so the content of sd card symbolic links look like this:

------------------------------
pi@retropie:~/RetroPie/roms/dreamcast $ ls -ga
total 3
drwxr-xr-x  2 pi 4096 Feb 25 20:45  .
drwxr-xr-x 37 pi 4096 Feb 24 21:53  ..
**lrwxrwxrwx  1 pi   70 Feb 25 20:17 '90 Minutes - Sega Championship Football.chd' -> '/media/usb0/roms/dreamcast/90 Minutes - Sega Championship Football.chd'**

**lrwxrwxrwx  1 pi   43 Feb 25 20:17 'Bomberman Online' -> '/media/usb0/roms/dreamcast/Bomberman Online'**

**drwxr-xr-x  2 pi 4096 Feb 25 20:56 'Sonic Shuffle'**

------------------------------
As you can see there are two symbolic links (one file and one folder) to usb and one folder on sdcard:
Symbolic link of a file 90 Minutes - Sega Championship Football.chd which is pointing directly to the usb file
Bomberman Online which is pointing to the directory on usb folder with content of 'Bomberman Online.gdi'
Sonic Shuffle is a folder made on the sd card with the content of 'Sonic Shuffle.gdi'

When I run the skyscraper and scrape the games the result is:
-  90 Minutes - Sega Championship Football and Sonic Shuffle gets parsed and can be found in .emulationstation/gamelists/dreamcast/gamelist.xml.  
- Bomberman Online is not found and can't be parsed. But if I create a file named Bomberman Online.gdi in the folder /RetroPie/roms/dreamcast in the game gets scraped.The same goes for example /RetroPie/roms/dreamcast/Bomberman Online/Bomberman Online.gdi. 

So the conclusion is that scraping of subfulders is working ok on sd card but if I have sylinks to subfolders on sdcard, the scraper dosn't work.

**Special circumstances**
Is your system set up in any special manner that could interfere with how Skyscraper works?
No costumizations made.

**Terminal output**
If applicable, add terminal output to help visualize your problem.

**Technical information**
    Raspberry Pi 4 
 - Skyscraper version: 3.4.1
 - Internet connection: wired
 - OS:  RetroPie 4.5.13
 - OS Version RetroPie 4.5.13

**Additional context**

**Comment by muldjord** [comment]
Please recheck your symlinks. This does not look right:
```
lrwxrwxrwx 1 pi 43 Feb 25 20:17 'Bomberman Online' -> '/media/usb0/roms/dreamcast/Bomberman Online'
```
It has to be a symlink to one of the supported file types. In this instance it should be a .chd file or similar. You mention that one of them works, and other don't. That's a pretty clear indication to me that it is your symlinks that are wrong. Skyscraper works with symlinks, I just tested it.

**Comment by rhunjadi** [comment]
thank you for your quick anwser!

The link 'Bomberman Online' is a taget to a directory '/media/usb0/roms/dreamcast/Bomberman Online'. Then the content of the directory in /media/usb0/roms/dreamcast/Bomberman Online'
is (files on USB):

pi@retropie:~/RetroPie/roms/dreamcast/Bomberman Online $ ls -ga
total 1160589
drwxrwxrwx 1 pi       4096 Feb 25 00:41  .
drwxrwxrwx 1 pi       8192 Feb 25 10:35  ..
-rwxrwxrwx 1 pi         87 Dec 24  1996 'Bomberman Online.gdi'
-rwxrwxrwx 1 pi    1425312 Dec 24  1996  track01.bin
-rwxrwxrwx 1 pi    1237152 Dec 24  1996  track02.raw
-rwxrwxrwx 1 pi 1185760800 Dec 24  1996  track03.bin

I tought that your algorithem is also scraping subdirectories on symlinks the same like subdirectories on sd card. But it looks like the scraping of symlinks only works if I have direct symlink to file not the directory and his content.

I just made a little example...I made also a file Bomberman Online.gdi on usb :

pi@retropie:**/media/usb0/roms/dreamcast** $ ls -ga
total 332384
drwxrwxrwx 1 pi      8192 Feb 26 11:01  .
drwxrwxrwx 1 pi      4096 Feb 15 12:25  ..
drwxrwxrwx 1 pi      4096 Feb 25 00:41 'Bomberman Online'
-rwxrwxrwx 1 pi         0 Feb 26 11:01 'Bomberman Online.gdi'



pi@retropie:**~/RetroPie/roms/dreamcast** $ ls -ga
lrwxrwxrwx  1 pi   43 Feb 26 11:02 'Bomberman Online' -> '/media/usb0/roms/dreamcast/Bomberman Online'
lrwxrwxrwx  1 pi   47 Feb 26 11:02 'Bomberman Online.gdi' -> '/media/usb0/roms/dreamcast/Bomberman Online.gdi'


if I scrape the target 'Bomberman Online.chd' and then rapair the paths in gamelist.txt to target 

`<path>/home/pi/RetroPie/roms/dreamcast/Bomberman Online.gdi</path>`   
changed to 
`<path>/home/pi/RetroPie/roms/dreamcast/Bomberman Online/Bomberman Online.gdi</path>`

then I delete the  'Bomberman Online.gdi' -> '/media/usb0/roms/dreamcast/Bomberman Online.gdi' 
everything works as expected...

But this is a lot of work...because I have a lot of subdirectories....

**Comment by muldjord** [comment]
I just tested it, and you are right, files insde symlinked folders won't be scraped. I will have to look into this.

**Comment by rhunjadi** [comment]
Thank you SO much! this is an example of a **good** support :)

Just one more question....is it possible to make to show the scraped content on a directory prespective not just directly on file?....It seems a little clumsy to show the content of a game only when I go into the directory and not on top of it. For example if I am browsing in retropie menu of dreamscast games I have to go into every directory of game to show the art and videos. It would be nicer just to show it also when I am not directly in the directory of a game but also one level up.

**Comment by muldjord** [comment]
Symlinked paths are now fixed. It's on the master branch and will be in 3.4.2 when it's released.

EDIT: Concerning artwork on folders, I just realize I already do this for all the extensions supported by the selected platform. But if more than one file is detected inside the subfolder of one of the supported extensions, it will revert to file mode.

For instance:
```
snes/subfolder/game1.zip
snes/subfolder/game2.zip
```
For this folder it would show artwork when selecting the file. But for:
```
psx/subfolder/game1.chd
```
it would show the artwork when selecting the folder. So I'm guessing, in your case, your subfolders contain more than one file of the supported extensions. Could you please tell me which file extensions you have in a subfolder where it shows the artwork on the files instead of the containing folder?

**Comment by rhunjadi** [comment]
The problem was (as you said in prevoius post) in more files extensions. I was just experimenting to check how the skyscraper worked. As I can see I did a mistake by creating more files in one folder with the same name as folder but with different extensions (like .gdi, .chd, .conf, ...).

Hope the release 3.4.2 will be out soon to check if everything with symlinks work now.

Thank you again for your fast and effective support.

**Comment by muldjord** [comment]
You're welcome. 3.4.2 is out now, feel free to try it out. :)

**Comment by rhunjadi** [comment]
That was quick! :)

I can confirm that everything works like a charm. Do I need to thank you again? :) 

Thank you :)

**Comment by muldjord** [comment]
Glad it works, thanks for testing. And thank you for pointing out the symlink bug! I'll close this now.
