### ISSUE TITLE
Doesn't work with nointro roms when filename includes multiple game name variants

### ISSUE THREAD

**Issue by joaoluizcarvalho** [muldjord/skyscraper#197]
I finally learned how to generate 1G1R sets using nointro .dat files and ClrMamePro. However, I noticed Skyscraper fails when the ROM filename includes multiple game name variants.

For example: "Bare Knuckle - Ikari no Tekken ~ Streets of Rage (World) (Rev A).zip" should be recognized as Streets of Rage for the Sega Genesis, but Skyscraper finds no result for this game.

I am using screenscraper. I thought  the ROMS would be identified by their CRC, so I thought the filename actually didn't matter. Apparently I was wrong because Skyscraper+screenscraper also misidentified "Flintstones, The (USA) (Proto) (Ocean).zip" as "Flintstones, The (USA) (Taito).zip". These are two completely different games for the Sega Genesis (the Ocean game is based on the live-action movie, while the Taito game is based on the cartoon).

I experienced similar issues with my Sega Master System 1G1R nointro romset.

Am I doing something wrong here?

**Comment by muldjord** [comment]
Skyscraper follows the official API requirements for requests as documented by ScreenScraper. The requests contain crc, md5 and sha1 checksums as the main ways to identify a rom. But it also includes the filename, file size and specific platform id (in the same request). If a unique game can be found by mixing and matching several of these within that platform restriction, it will return a result. So the matches are most likely from incorrectly connected games in their database, either to a checksum or the precise filename.

Please go to screenscraper.fr and look them up. If they are incorrectly connected (checksums or precise filename) in their database, you can report it to them. Either way, I would like to know what you conclude.

So this is most likely not a Skyscraper issue. If you were scraping with one of the filename based modules (mobygames, thegamesdb, openretro) I could understand why this would happen. These modules are not checksum based and are entirely reliant on the composition of the filename. I do A LOT to try and get around false positives, but obviously it can't be avoided entirely. Especially for something basically being called the same thing.

**Comment by joaoluizcarvalho** [comment]
Thank you for the quick reply. And thank you SO MUCH for your work with Skyscraper. It completely changed my experience with Retropie.

I found that the Ocean prototype of the Flinstones game is not listed as a Mega Drive game on screenscraper. The ROM (CRC=9281FF45) is incorrectly linked to the Taito game: https://www.screenscraper.fr/gameinfos.php?plateforme=1&gameid=324
I'll try to correct that on their end.

However, for the Streets of Rage game, this is what I get with '7z l -lst':

Path = Bare Knuckle - Ikari no Tekken ~ Streets of Rage (World) (Rev A).md
Size = 524288
Packed Size = 370470
Modified = 1996-12-24 23:32:00
CRC = 4052E845

This is the list of roms for the Streets of Rage game on screenscraper:
https://www.screenscraper.fr/gameinfos.php?gameid=7&action=onglet&zone=gameinfosroms

The filename and CRC match exactly with one of the roms listed in there, so I don't understand what is wrong here.

**Comment by muldjord** [comment]
Glad you like it! Appreciate it. Skyscraper will checksum the zipfile unless you use the `--unpack` option. That might be the reason. Please check the checksum of the zipfile instead or use `--unpack`. Let me know how it goes.

**Comment by joaoluizcarvalho** [comment]
The unpack option solved it for me, thank you so much!

Still, I find it odd that it correctly identifies pretty much every single game, except for those with multiple game name variants on the filename.

My guess is that, since the CRC data wasn't correct, it was relying solo on filename for identifying the roms. Since the filenames I was using were exact matches with the ones listed in screenscraper, it would always identify the game correctly; except when there was multiple game name variants on the filenames, even though the filenames were still exact matches with screenscraper listings (with multiple game name variants and all).

Do you think it would could be an issue with the "tilde" symbol on the filename?

**Comment by muldjord** [comment]
Yes, I believe you are correct. If it finds a unique match with filename + platform it will use that even if the checksums don't match. I don't believe it is an issue with the tilde symbol, but it's been a long time since I've tested this.

I'm guessing you 7zipped your files yourself which will make all of your roms incompatible with `screescraper` except for matching with exact filename. `--unpack` fixes this, but it is also a lot slower to use.

Closing.

**Comment by joaoluizcarvalho** [comment]
This is probably a stupid question, but i'll ask anyway. I assume --unpack only applies to .7z and .zip files, correct? If I have both zipped and unzipped files in my roms directory, and I use the --unpack option, Skyscraper will unpack .zip and .7z files for scraping purposes, but will treat the other (unzipped) roms as if --unpack was not being used, correct?

**Comment by muldjord** [comment]
Correct. 

EDIT: Quick note though: If the zip file is more than 8 megs, it will fall back to not unpacking it, to avoid running our of memory on the Pi. The `--unpack` option is a pretty hacked together solution as it is right now, so I had to implement some limits to avoid outofmem errors resulting in a crash for smaller systems.

**Comment by joaoluizcarvalho** [comment]
I forgot to ask: does --unpack apply to .chd files also?

**Comment by muldjord** [comment]
No, only 7z and zip files. And be aware of my edit above concerning memory.

**Comment by joaoluizcarvalho** [comment]
Here is an idea (may be a stupid idea, and if so, then I'm sorry): if it's a zip file and it is less than 8mb, then unzip it and calculate crc, md5 and sha1 checksums (as usual); if the zip file is more than 8mb, then do not unzip it, but use the crc found in the zip file header, and leave md5 and sha1 blank. My guess is that crc, file size and file name should be enough for an accurate identification. And this would be a lot faster than unzipping every file it scrapes.

My point is that calculating md5 and sha1 for the zip file (instead of for the roms inside the zip file) will work only if you are using a zip file you downloaded from a well-known source, and keep it intact.

If you use a rom manager, it may change the roms names inside the zip files (and, consequently, change the zip file's checksums).

In fact, this is exactly why scraping with unpack=false wasn't working for my zip files: I used RomVault to validate my roms, and RomVault changed the rom names inside the zip files, consequently changing the zipfiles' checksums.

In this case, it would be better to have only the CRC checksums for the roms, than not having any matching checksum data at all.

**Comment by muldjord** [comment]
> My guess is that crc, file size and file name should be enough for an accurate identification

It is, but the ScreenScraper guys have asked me to always use all of them in order to keep using their API, so that's what I am going to do.

But It's not a bad idea, although it's a niche problem and very rare for me to hear about issues concerning this. Especially since most zipped roms are smaller than 8 megs for the retro platforms. So we're basically looking at cdrom based games and gba games or something like that.

With that said, I want to completely overhaul the `--unpack` implementation, and by that I can remove the 8 meg limit. Problem will be solved at that point. No ETA.
