### ISSUE TITLE
Cover art associated with wrong games 

### ISSUE THREAD

**Issue by HumanRob** [muldjord/skyscraper#2]
After scraping (tried this with both Amiga and spectrum games on emulation station), several titles will often show the cover artwork for the previous, completely unrelated, title. Re-ran the import a few times, and thought it might be related to threading so re-ran again with 1 thread but it made no difference.

Let me know if there's anything else you need. 

Many thanks

**Comment by muldjord** [comment]
Could you give me an example of two games that clash - exact filenames, including suffix? Also, please provide your config.ini and command line used when this error appears. I should then be able to reproduce it and see if it is an error or an artifact coming from Skyscraper being 100% automated. Thank you.

**Comment by muldjord** [comment]
Closed from lack of feedback.
