### ISSUE TITLE
PS2 ISO.GZ File Parsing

### ISSUE THREAD

**Issue by zcrowhti** [muldjord/skyscraper#201]
Skyscraper Does Not Properly Scrape PS2 Files in ISO.GZ format.

I've attempted several scrapers on PS2 compressed ISO files with very lackluster results. Skraper.net handles them appropriately, but Skyscraper seems to have some kind of parsing issue around them. This issue is prevalent on screenscraper & thegamesdb scrapers. The tool is searching for rom.iso when file name is rom.iso.gz. I've tried adding "iso.gz" via the --addext flag, but that didn't work. Randomly some titles will return data, but he majority out of 100s of ISO files fail.

**Command**
Skyscraper --nosubdirs -i /mnt/test/PS2 -p ps2 -s screenscraper --nomarquees --nowheels --nocovers --noscreenshots -u user:pass --relative

Skyscraper --nosubdirs  -i /mnt/test/PS2 -p ps2 -s thegamesdb --nomarquees --nowheels --nocovers --noscreenshots --relative rom.iso.gz

**Special circumstances**
Network share

**Terminal output**
`#183/597, (5/178)
Elapsed time   : 05:20:02
Est. time left : 12:04:02

#184/597 (T1) Pass 1 ---- Game 'God Hand.iso' not found :( ----

'screenscraper' requests remaining: 19954

#184/597, (5/179)
Elapsed time   : 05:21:29
Est. time left : 12:01:36

#185/597 (T1) Pass 1 ---- Game 'God of War II.iso' not found :( ----

'screenscraper' requests remaining: 19954

#185/597, (5/180)
Elapsed time   : 05:30:06
Est. time left : 12:15:08

#186/597 (T1) Pass 1 ---- Game 'God of War.iso' not found :( ----

'screenscraper' requests remaining: 19954

#186/597, (5/181)
Elapsed time   : 05:39:26
Est. time left : 12:30:03
`

**Technical information**
 - Skyscraper version: 3.4.3
 - Internet connection: Gbit
 - OS: Debian 10

**Comment by muldjord** [comment]
Here's the issue. Some roms have names such as `Game name v1.2.zip`. At the moment Skyscraper uses the `.zip` part. If I expanded that the everything after the first `.` the file extensions would become `2.zip` which is wrong.

So this is a great example of blancing use cases. Many roms on Amiga use `.` in the filename. The solution could be a config flag like `useCompleteSuffix` or similar. Let me know if you feel like this would be useful.

**Comment by muldjord** [comment]
Please try with `--addext "*.iso.gz"` as the documentation describes [here](https://github.com/muldjord/skyscraper/blob/master/docs/CLIHELP.md#--addext-extension)

**Comment by muldjord** [comment]
This is a layered problem. It's not actually searching for "rom.iso" when using `screenscraper`, that's just how it's shown in the output. I use completeBaseName for the output since many Amiga roms have `.` in them (eg. `Game name v1.2.lha`). So I can see how you would assume that. You can use  `--verbosity 3` to see what it actually searches for.

It _does_ use `rom.iso` when using `thegamesdb`. The reason being the same as above. Some Amiga games use `.` in the name. So I'll need to think about this for a bit.

**Comment by muldjord** [comment]
> Skraper.net handles them appropriately,

What does this mean exactly? Do you have an example of a `something.iso.gz` that works with Skraper? I can't find any in their database for Saturn. There's only `God Hand (USA).iso` and similar. No `.iso.gz`.

**Comment by zcrowhti** [comment]
Hey Muldjord, 90% of the PS2 archives returned metadata when I used skraper. While less than 5% returned data on skyscraper. This wasn't an issue for any other platform with double extension format (wii/gc used rom.nkit.gcz format). I didn't capture the traffic to see what was different in the calls between tools, though.

**Comment by zcrowhti** [comment]
I noticed an interesting pattern just now. All the scrapes that do work with skyscraper are dual disk games. Here is an example:

`#90/597 (T1) Pass 1 ---- Game 'Devil May Cry 2 [D1].iso' found! :) ----
Scraper:        screenscraper
From cache:     NO
Search match:   100 %
Compare title:  'Devil May Cry 2'
Result title:   'Devil May Cry 2' ()
Platform:       'Playstation 2' ()
Release Date:   '2003-01-29' ()
Developer:      'Capcom' ()
Publisher:      'Capcom' ()
Players:        '1' ()
Ages:           '16+' ()
Tags:           'Beat'em Up, Platform, Action' ()
Rating (0-1):   '0.7' ()
Cover:          YES (uncached) ()
Screenshot:     YES (uncached) ()
Wheel:          YES (uncached) ()
Marquee:        YES (uncached) ()

[...]

#91/597 (T1) Pass 1 ---- Game 'Devil May Cry 2 [D2].iso' found! :) ----
Scraper:        screenscraper
From cache:     NO
Search match:   100 %
Compare title:  'Devil May Cry 2'
Result title:   'Devil May Cry 2' ()
Platform:       'Playstation 2' ()
Release Date:   '2003-01-29' ()
Developer:      'Capcom' ()
Publisher:      'Capcom' ()
Players:        '1' ()
Ages:           '16+' ()
Tags:           'Beat'em Up, Platform, Action' ()
Rating (0-1):   '0.7' ()
Cover:          YES (uncached) ()
Screenshot:     YES (uncached) ()
Wheel:          YES (uncached) ()
Marquee:        YES (uncached) ()
[...]

#92/597 (T1) Pass 1 ---- Game 'Devil May Cry 3.iso' not found :( ----

#93/597 (T1) Pass 1 ---- Game 'Devil May Cry.iso' not found :( ----

---
ls Devil\ May\ Cry*
'Devil May Cry 2 [D1].iso.gz'  'Devil May Cry 3.iso.gz'
'Devil May Cry 2 [D2].iso.gz'  'Devil May Cry.iso.gz'

`
All of these archives correctly scraped using Skraper.

**Comment by muldjord** [comment]
I thiiiiink I know what might be happening. If you rename `Devil May Cry 3.iso.gz` to `Devil May Cry 3.iso` it works. Maybe what Skraper does internally is that it removes the `.gz` part for files that has them before searching for them.

EDIT: Yes, that works. If I only use the basename (leaving out `.iso.gz` entirely) it works. I'll need to do some more testing with this implementation, as I worry this might pull in some false positives on other platforms. But if my tests come out clean, I'll make this the default behaviour from the next release (3.4.4).

**Comment by muldjord** [comment]
It's on master now. If you want to test it, you can compile master, `sudo make install` it and try it out.

**Comment by zcrowhti** [comment]
Just spot checked a few dozen games, and that seemed to fix it. Great work and great app, my friend! Is there a way to buy you a beer? :+1:

**Comment by muldjord** [comment]
Glad it worked and thank you for testing! No need for beer, I have some in the fridge ;) :beer: Cheers!

Closing this.
