### ISSUE TITLE
ScreenScraper APIv2 returned invalid / empty Json

### ISSUE THREAD

**Issue by game93** [muldjord/skyscraper#203]
happening with most games is it a problem on your end or mine 

please help im pulling my hair out

**Comment by muldjord** [comment]
Please try again, it works fine here (meaning it's either a problem on your end, or ScreenScraper was down for a bit and is now up again). If it's still a problem, please provide the contents of the json error file as described in the error message.

**Comment by game93** [comment]
it seems to be working atm oh btw do you contol how many screenscraper request you get a day because i am a patron so shouldnt i get 50 000 not 10000

**Comment by muldjord** [comment]
I am not affiliated with ScreenScraper in any way. You need to contact them.

**Comment by game93** [comment]
i have tried any they haven't replayed 
so what do you do then ??

**Comment by muldjord** [comment]
As I said, I have nothing to do with ScreenScraper, so I don't know. Try their Discord? Closing.

**Comment by game93** [comment]
also a few of my games are not getting screenshots can you help

**Comment by muldjord** [comment]
The docs will give you answers: https://github.com/muldjord/skyscraper/tree/master/docs

If you need advice I suggest asking on the RetroPie subreddit or on the RetroPie forums. This is for bug reports and suggestions only.
