### ISSUE TITLE
ScreenScraper APIv2 returned invalid / empty Json

### ISSUE THREAD

**Issue by seriema** [muldjord/skyscraper#205]
**Describe the bug**
Screenscraper.fr is currently failing with a "invalid / empty Json" response. The `screenscraper_error.json` is empty from what I can tell.

It started happening and stopped a few times this same evening. 

**To Reproduce**
```bash
Skyscraper -s screenscraper -p nes
```

**Terminal output**
```bash
Request timed out, aborting request...
ScreenScraper APIv2 returned invalid / empty Json
The erroneous answer was written to '~/.skyscraper/screenscraper_error.json'. Please create a bug report at 'https://github.com/muldjord/skyscraper/issues' and attach that file.
```

**Technical information**
 - Skyscraper version: v3.4.3
 - Internet connection: adsl, I think
 - OS: Ubuntu
 - OS Version 18.04

**Additional context**
It's happening in my CircleCI setup. It's been working fine for a long time but tonight Screenscraper started erroring again. You can see the scraping output in the step "Run scraper on VM": https://circleci.com/gh/seriema/retro-cloud/734

**Comment by muldjord** [comment]
It's ScreenScraper - their servers are overloaded. Too many staying at home scraping games. As the output states, it times out because their servers don't respond in time. Skyscraper is fine.

**Comment by seriema** [comment]
Yeah I guessed so. Maybe there's another way to expect the situation and change the user message. As it is now Skyscraper says:
* check the error log, but it's going to be empty because the JSON was empty or the connection timed out
* open up a bug here, but there's nothing wrong with Skyscraper

**Comment by muldjord** [comment]
Yeah, I see your point. I'll think about it.

EDIT: I've now implemented a different message that clearly states what is happening. Thank you for reporting this. It will be in 3.4.4 to be released sometime today probably.

**Comment by muldjord** [comment]
3.4.4 out now
