### ISSUE TITLE
Enriching <name> tag in arcade platform

### ISSUE THREAD

**Issue by vg8020** [muldjord/skyscraper#206]
```
RetroPie 4.5.18 on rpi3
Skyscraper v3.4.5 by Lars Muldjord, from Retropie-Setup script
```
**Current status:**

`Skyscraper -p mame-libretro --skipped --forcefilename --relative --unattend`
will create a gamelist.xml with eg. tag
```
    <path>./ark2jp.zip</path>
    <name>ark2jp</name>
    <path>./ark2us.zip</path>
    <name>ark2us</name>
```
displayed in EmulationStation
```
ark2jp
ark2us
```
which allows understanding the video-game name, to some extent

`Skyscraper -p mame-libretro --skipped --relative --unattend`
will create a gamelist.xml with eg. tag
```
    <path>./ark2jp.zip</path>
    <name>Arkanoid - Revenge Of Doh</name>
    <path>./ark2us.zip</path>
    <name>Arkanoid - Revenge Of Doh</name>
```
displayed in EmulationStation
```
Arkanoid - Revenge Of Doh
Arkanoid - Revenge Of Doh
```
which is too generic as it does not allow noticing differences between video-games with the same name

**Suggestion:**

Adding a parameter that specifically applies to arcade/mame-libretro/mame-mame4all that allows generating a video-game name <name> that includes both video-game title and filename
eg.
```
    <name>Arkanoid - Revenge Of Doh [ark2jp]</name>
    <name>Arkanoid - Revenge Of Doh [arj2us]</name>
```

**Comment by muldjord** [comment]
This is a good idea. I think I'll do a name template instead of a simple option. That way you can get it exactly the way you want it to be. So, for instance, in `config.ini` you'd set a template like:
```
[mame-make4all]
nameTemplate="%t [%f]"
```
The `%t` will then be replaced by the actual title and `%f` will be replaced by the filename without suffix, resulting in:
```
Arkanoid - Revenge Of Doh [ark2jp]
```
It won't take too long to make, so I'll probably have it ready one of the coming days. Thank you for the suggestion.

**Comment by muldjord** [comment]
This is now on master. It will be in 3.4.6 which will be released once I've tested things thoroughly. The new option is documented [here](https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md#nametemplatet)

**Comment by vg8020** [comment]
This is excellent news. I'll keep a close eye on the next release v3.4.6 and run tests as well.

**Comment by muldjord** [comment]
3.4.6 out now. I've also implemented name template groups. It's all explained in the doc [here](https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md#nametemplatet). Let me know what you think. And thank you for the suggestion. :)

**Comment by vg8020** [comment]
`Updated: Running Skyscraper v3.4.6 by Lars Muldjord`

Here is my output:

Tokens beyond `%t` and `%f` are an unexpected gift. We all community certainly appreciate it.

```
Test #1:
skyscraper/config.ini
[mame-libretro]
nameTemplate="%t [%f]"
Command:
Skyscraper -p mame-libretro --relative --unattend /media/usb0/retropie-mount/roms/mame-libretro/ark2jp.zip

gamelist.xml
<?xml version="1.0"?>
<gameList>
  <game>
    <path>/media/usb/retropie-mount/roms/mame-libretro/ark2jp.zip</path>
    <name>Arkanoid - Revenge Of Doh [ark2jp]</name>
    <cover />
    <image>./media/screenshots/ark2jp.png</image>
    <marquee>./media/marquees/ark2jp.png</marquee>
```

Perfect `<name>` tag. Path is not considering `--relative` option, though.

```
Test #2:
same config.ini + add --forcefilename
Command:
Skyscraper -p mame-libretro --forcefilename --relative --unattend /media/usb0/retropie-mount/roms/mame-libretro/ark2jp.zip

gamelist.xml
<?xml version="1.0"?>
<gameList>
  <game>
    <path>/media/usb/retropie-mount/roms/mame-libretro/ark2jp.zip</path>
    <name>Arkanoid - Revenge Of Doh [ark2jp]</name>
    <cover />
    <image>./media/screenshots/ark2jp.png</image>
    <marquee>./media/marquees/ark2jp.png</marquee>
```

So `--forcefilename` is correctly overriden by `config.ini` platform NameTemplate settings.

```
Test #3: new config.ini + original command
[mame-libretro]
nameTemplate="%t [%f] by [%d]-[%p]"
Command:
Skyscraper -p mame-libretro --relative --unattend /media/usb/retropie-mount/roms/mame-libretro/ark2jp.zip

gamelist.xml
<?xml version="1.0"?>
<gameList>
  <game>
    <path>/media/usb0/retropie-mount/roms/mame-libretro/ark2jp.zip</path>
    <name>Arkanoid - Revenge Of Doh [ark2jp] by [Taito]-[Taito]</name>
    <cover />
    <image>./media/screenshots/ark2jp.png</image>
    <marquee>./media/marquees/ark2jp.png</marquee>
```

```
Test #4: new config.ini + original command
[mame-libretro]
nameTemplate="%t (%D) [%f] by [%d]-[%p] %P Player(s)"
Command:
Skyscraper -p mame-libretro --relative --unattend /media/usb/retropie-mount/roms/mame-libretro/ark2jp.zip

gamelist.xml
<?xml version="1.0"?>
<gameList>
  <game>
    <path>/media/usb0/retropie-mount/roms/mame-libretro/ark2jp.zip</path>
    <name>Arkanoid - Revenge Of Doh (19870601) [ark2jp] by [Taito]-[Taito] 2 Player(s)</name>
    <cover />
    <image>./media/screenshots/ark2jp.png</image>
    <marquee>./media/marquees/ark2jp.png</marquee>

```

From the different tests run, there are just to remarks I would like to add:

1. `<path>` tag should show relative path when such option is set in the command line. I should note that `gamelist.xml` is perfectly playable.
2. to make it golden, `%D` could be expanded to only show the year, eg. `%y`

Congratuations @muldjord v3.4.6 looks **amazing**.

**Comment by muldjord** [comment]
Thank you very much for testing it out, I appreciate the thoroughness of it.

> `<path>` tag should show relative path when such option is set in the command line.

I'm not sure I understand. Are you aware of the existing `--relative` CLI option and the `relativePaths="true"` config.ini option? They do exactly that.

EDIT: Ah, now I see. This is not working for your use case. I'll need to look into that.

> To make it golden, %D could be expanded to only show the year, eg. %y.

Good idea, I'll look into it for 3.4.7.

**Comment by vg8020** [comment]
Sorry, I may not have explained it well enough. In `Test #1` command is

`Skyscraper -p mame-libretro --relative --unattend /media/usb0/retropie-mount/roms/mame-libretro/ark2jp.zip`

so `gamelist.xml `should include a relative path in the `<path>` tag. However, it is showing

`<path>/media/usb/retropie-mount/roms/mame-libretro/ark2jp.zip</path>`

against expected

`<path>./ark2jp.zip</path>`

No option has been edited from original `config.ini` file except adding the NameTemplate. I have extensively used `--relative` option in v.3.4.5 and it has produced the expected relative path, so I thought it may be worth mentioning it.

Hope this clarifies & thank you for your efffort.

Edit: Ok, I see your edit now. So you noticed as well. Great synch.

**Comment by muldjord** [comment]
I'm a little in doubt what's going on here. I can see you use retropie-mount which, to my knowledge, symlinks the usb mount to the ordinary `/home/pi/RetroPie/roms` folder, it that correct? What does Skyscraper list as `Input folder` in the terminal when you run it? Does it say `/home/pi/RetroPie/roms` or `/media/usb/retropie-mount/roms`?

I do a search/replace for the input to `./` folder when I make the path relative. So for some reason your input folder is not the same as the one stored in my internal settings. Perhaps because it is a symlink.

**Comment by vg8020** [comment]
I think it is more of a proper mount than symlinks, but do not take my word. I installed opt package [romusbservice (Automatic mount)](https://github.com/RetroPie/RetroPie-Setup/wiki/Running-ROMs-from-a-USB-drive)

But I think I have it:

```
Test #5: config.ini + original command referring to /media/usb/retropie-mount/roms/mame-libretro path
[mame-libretro]
nameTemplate="%t (%D) [%f] by [%d]-[%p] %P Player(s)"
Command:
pi@retropie:~ $ Skyscraper -p mame-libretro --relative --unattend /media/usb/retropie-mount/roms/mame-libretro/ark2jp.zip 
------------------------------------------
Running Skyscraper v3.4.6 by Lars Muldjord
------------------------------------------
Platform:           'mame-libretro'
Scraping module:    'cache'
Input folder:       '/home/pi/RetroPie/roms/mame-libretro'
Game list folder:   '/home/pi/RetroPie/roms/mame-libretro'
Covers folder:      '/home/pi/RetroPie/roms/mame-libretro/media/covers'
Screenshots folder: '/home/pi/RetroPie/roms/mame-libretro/media/screenshots'
Wheels folder:      '/home/pi/RetroPie/roms/mame-libretro/media/wheels'
Marquees folder:    '/home/pi/RetroPie/roms/mame-libretro/media/marquees'
Cache folder:       'cache/mame-libretro'

```
gamelist.xml shows:
```
<?xml version="1.0"?>
<gameList>
  <game>
    <path>/media/usb/retropie-mount/roms/mame-libretro/ark2jp.zip</path>
    <name>Arkanoid - Revenge Of Doh [ark2jp] by [Taito]-[Taito] 2 Player(s)</name>
    <cover />
    <image>./media/screenshots/ark2jp.png</image>
    <marquee>./media/marquees/ark2jp.png</marquee>

```
Note different input path in command line and output path in log. In this case, `<path>` references the command line path.

However, when referencing the rom via `/home/pi/RetroPie` in this case `--relative` option works as expected:

```
Test #6: config.ini + original command referring to /home/pi/RetroPie/roms/mame-libretro path
[mame-libretro]
nameTemplate="%t (%D) [%f] by [%d]-[%p] %P Player(s)"
Command:
pi@retropie:~ $ Skyscraper -p mame-libretro --relative --unattend /home/pi/RetroPie/roms/mame-libretro/ark2jp.zip 
------------------------------------------
Running Skyscraper v3.4.6 by Lars Muldjord
------------------------------------------
Platform:           'mame-libretro'
Scraping module:    'cache'
Input folder:       '/home/pi/RetroPie/roms/mame-libretro'
Game list folder:   '/home/pi/RetroPie/roms/mame-libretro'
Covers folder:      '/home/pi/RetroPie/roms/mame-libretro/media/covers'
Screenshots folder: '/home/pi/RetroPie/roms/mame-libretro/media/screenshots'
Wheels folder:      '/home/pi/RetroPie/roms/mame-libretro/media/wheels'
Marquees folder:    '/home/pi/RetroPie/roms/mame-libretro/media/marquees'
Cache folder:       'cache/mame-libretro'

```
gamelist.xml shows:

```
<?xml version="1.0"?>
<gameList>
  <game>
    <path>./ark2jp.zip</path>
    <name>Arkanoid - Revenge Of Doh [ark2jp] by [Taito]-[Taito] 2 Player(s)</name>
    <cover />
    <image>./media/screenshots/ark2jp.png</image>
    <marquee>./media/marquees/ark2jp.png</marquee>

```
Note same input path in command line and output path in log. In this case, <path> references the relative path.

When scanning a whole `-p system` there is no reference to a single rom path in the command line (obviously) which results in a gamelist.xml that is always showing correct relative paths, if `--relative` option was keyed in the command line.

Lesson learned: If you are scanning a single rom in a mounted USB flashdrive and use the `--relative` option and want gamelist.xml to show the way you expect, always use the `/home/pi/RetroPie` path. So, basically, always use the `/home/pi/RetroPie` path. This is a rare case indeed and still, the resulting gamelist.xml file is perfectly playable.

**Comment by muldjord** [comment]
Ah, so this only happens when you generate the gamelist for a subset of roms. I think that's a rare case as you also mention. I can't actually come up with a good reason for doing that other than for testing stuff like we've been doing here. So I'll leave it for now.

Either way, thank you very much for your help with this. I'm gonna close this issue now.
