### ISSUE TITLE
Some files are found but not all

### ISSUE THREAD

**Issue by kec2** [muldjord/skyscraper#207]
**Describe the bug**
I'm scraping for the Amiga game Civilization AGA. This game has four disks but only two if them are found.

The files are name "Civilization [AGA] (Disk X of 4).adf" where x = [1, 2, 3, 4].

Output in: skipped-amiga-screenscraper.txt
'Civilization [AGA] (Disk 2 of 4)', No returned matches
'Civilization [AGA] (Disk 4 of 4)', No returned matches

**To Reproduce**
I ran geather information from RetroPie-setup.sh
I only ran for the Amiga platform.

**Special circumstances**
Is your system set up in any special manner that could interfere with how Skyscraper works?

**Terminal output**
I have attached the log file.

**Technical information**
 - Skyscraper version: 3.4.5
 - Internet connection: adsl
 - OS: RetroPie
 - OS Version 4.5.18

**Additional context**

**Comment by kec2** [comment]
Added log file

[rps_2020-04-08_141438.log.gz](https://github.com/muldjord/skyscraper/files/4452053/rps_2020-04-08_141438.log.gz)

**Comment by muldjord** [comment]
This is not a Skyscraper issue. You need to add these files to the ScreenScraper database. I am not affiliated with them. Closing.
