### ISSUE TITLE
Gamelist not being generated only for Genesis/Megadrive

### ISSUE THREAD

**Issue by jeffsnow88** [muldjord/skyscraper#210]
I have installed the skyscraper via terminal.

Execute the following command for each plataform:

Skyscraper -p genesis -s openretro

Logs show as information being scraped, however, no gamelist.xml/media folder is being generated (ONLY FOR Genesis). Others are working fine. I tried to check the rom/genesis folder (ls -a) nothing is showing a part from the roms. I also checked gamelist files on .emulationstation/gamelists but nothing is there also.

Using version 3.4.6

**Comment by muldjord** [comment]
This is for bug reports and suggestions only and this is neither. Please spend some time reading the docs. You need to generate the gamelist afterwards with `Skyscraper -p genesis`. Read more [here](https://github.com/muldjord/skyscraper/blob/master/docs/USECASE.md)

**Comment by jeffsnow88** [comment]
I believe this is a bug, since its not working? As I mentioned, I have executed the commands for each plataform. Output is not generated only for genesis. I checked all the docs, several times.

**Comment by muldjord** [comment]
You state that you run the command `Skyscraper -p genesis -s openretro` which gathers resources. It does not generate a gamelist. Therefore not a bug.

**Comment by muldjord** [comment]
If it still doesn't work when you've generated the gamelist, let me know. But I highly doubt that's the case.
