### ISSUE TITLE
--onlymissing skips count towards scrape failure

### ISSUE THREAD

**Issue by Paul-Colucci** [muldjord/skyscraper#211]
setting the only --onlymissing flag to fill the misses from another source, will count every skip as a failure.  For example, If you have 1,000 roms and scan them from source 1 and it scrapes 990 roms, then re-do the scan with another source and --onlymissing, the scan will fail after 42 skips.  You can only adjust this value to a maximum of 200, but skipping because of onlymiss flag shouldn't count toward the fail rate.

**Comment by muldjord** [comment]
Ah, yes, of course. I will see if I can find a proper solution.

**Comment by muldjord** [comment]
3.4.7 now out where this is fixed. Please test.

**Comment by Paul-Colucci** [comment]
Fixed! Thanks!

**Comment by muldjord** [comment]
Thank you for testing, closing.
