### ISSUE TITLE
Add LOVE support

### ISSUE THREAD

**Issue by JCodeShelver** [muldjord/skyscraper#212]
Could you add platform support for LOVE? It's an open-source 2D engine, and has many open-source games made for it, which I (and perhaps others) would like to scrape.

**Comment by muldjord** [comment]
I can easily add it, but what sources should it grab data from? As far as I can tell, none of the sources support it. Please let me know your thoughts on this.

**Comment by JCodeShelver** [comment]
Well I can't one source in your list of scraping modules that supports all LOVE Games (at least the six I have), and I haven't found a good database for LOVE metadata. itch.io was looking promising, but it's not meant for metadata, it just has some of the same contents on their webpages.

**Comment by muldjord** [comment]
Then I can't support the platform. There's not really a point in adding it if there's no official data for the games in the sources.

I don't have any data. The databases do. So I think you've begun this journey at the wrong end of the chain. You need to contact the databases, get them to support it officially as a platform, add the data for the games, and then contact me, so I can support that platform. That's how it would work :)
