### ISSUE TITLE
Not pulling screenshot correctly

### ISSUE THREAD

**Issue by Paul-Colucci** [muldjord/skyscraper#213]
I have the following rom for NES: P'Radikus Conflict (USA) (Unl).zip

It is listed in screenscraper:
https://www.screenscraper.fr/gameinfos.php?plateforme=3&gameid=18839

It clearly has a screenshot in the media section, however it is not being pulled.  All other information about the ROM is being pulled.  Not sure why this one field is failing.

I am seeing this happen on a few roms as well where everything is pulled but the screen shot.

**Comment by muldjord** [comment]
Ha, this is a tricky one and I know why. As a sanity check I actually make sure I've received more than 1024 bytes of data when checking the answer from ScreenScraper. And in rare cases the images are actually less than that. In this case it is only 884 bytes which causes it to be rejected. I'll adjust that limit to, let's say, 256 bytes instead. That will fix it.

Thank you very much for reporting this, I would not have catched this myself.

**Comment by Paul-Colucci** [comment]
Whenever I report stuff you fix it quick. That's why i even bother reporting =)

**Comment by Paul-Colucci** [comment]
That would also explain why a lot of the screenshots not coming back are from Atari 2600, a lot of the images are small it seems!

**Comment by muldjord** [comment]
Makes sense. I actually wonder if some of them are even smaller than 256 bytes... Hmmm... I'll run some tests. Stay tuned.

EDIT: Ok, so smallest Atari2600 screenshot is 456 bytes. I'll set the limit at 256 then.

**Comment by muldjord** [comment]
3.4.8 out now with a limit of 256 bytes. Tested and it now works for all Atari2600 screenshots (and wheel, cover and marquee, I've lowered the check for all of them). Again, thank you for reporting this, great find!

Closing.
