### ISSUE TITLE
gamelist.xml image generation errors

### ISSUE THREAD

**Issue by Paul-Colucci** [muldjord/skyscraper#215]
All the images are pulled from screenscraper and cached correctly, however when you generate the gamelist.xml, skyscraper goes to the local cache and then copies the images to the rom folder (or wherever you specificy)... sometimes resizing them, sometimes combining several images to make a screenshot.  This image that is generated sometimes become corrupt and then when you navigate to that Rom, emulation station crashes.  It is totally random, and every time the playlist is generated different images have errors.  I think there needs to be better error checking/recovery when generating the images.

**Comment by Paul-Colucci** [comment]
Also, it would be great to have a simple option to make the screen shot just be the screen shot returned from the source without editing.  It would produce smaller files which makes navigating in ES quicker, and also it would take much less time to make the gamelist because the images wouldn't have to be constructed in memory.  The way artwork is done can look nice, but sometimes it is not worth the extra time generating lists and dealing with potential errors.

**Comment by muldjord** [comment]
Please read the documentation on the artwork. It is entirely up to you how it's composited so what you ask for is already possible and even provided in the `/home/pi/.skyscraper/artwork.xml.example2`: https://github.com/muldjord/skyscraper/blob/master/docs/ARTWORK.md

Concerning the erroneous images, I believe there's a higher chance of a corrupt SD card. The reasoning being that Skyscraper does not randomly generate faulty images. If it did generate a faulty image (which there are already checks in place to ensure it doesn't) it would be the same image every time a gamelist was generated. There are no random things happening inside Skyscraper that would make it do things differently from run to run. So either it would generate the same bad image again and again, or it would not. Random makes little sense to me.

I have been scrolling through Skyscraper generated gamelists for a long time and I don't recall having EmulationStation crash on me ever for this reason.

Feel free to contradict me on this if you have info pointing directly to Skyscraper causing this.

**Comment by Paul-Colucci** [comment]
The problem is that it is not reproducible.  Every time you generate the game list different images will be corrupt.  It is great that the cache is stable, and the assets pulled are not corrupt. However, a full game list build requires 10+ minutes to generate the assets and then you need to load up ES and scroll through them 1 at a time making sure none of them are corrupt.  As someone with 12 systems and 4,000+ roms this makes skyscraper a non-starter for me, unfortunately because whenever I build a system I have no idea when/if it will crash due to a bad image.  Keep in mind the resulting action in  ES when this happens is that the entire pi will freeze, or it will just kill ES.  

In my case, I would not want to continue using the scraper unless there was a flag to skip the asset generation entirely, and just create gamelists using direct links to the media in cache.  Similar to what --symlnk does, but for all videos and images and without the symlink (just writing the full path to the file in cache).  That option would solve every single problem for me.

**Comment by muldjord** [comment]
I hope you can see my point in that the randomized nature of this issue seems odd. The compositor does things exactly the same each run. It's the exact same code using the exact same assets. It does not sometimes generate a corrupt image. Either it does or it doesn't. So I'm more inclined to point to a corrupt disk or something along those lines. As I have never seen this issue on any system I've ever used Skyscraper on myself I find it hard to believe this is a Skyscraper issue - at least until someone gives me proof of this in a reproducible way. If it was reproducible I'd love to look into it, absolutely.

**Comment by muldjord** [comment]
As I also mentioned, there is a check in place (and has been for more than a year) that will fail out and not use the generated screenshot if it can't be saved correctly. This further leads me to believe there's something else going on. It basically asks the Qt QImage to be saved with a certain filename. If it can't it will report back with "false" which I then check and in that case leave it out of the gamelist completely.

**Comment by muldjord** [comment]
So I can understand why this is a non-starter for you, of course it is. But so far you are the only one with this issue, so I would urge you to look beyond Skyscraper to solve it.

The only thing I can come up with that might make the system less error-prone if you have a faulty SD card, is to try and run the gamelist generator with `Skyscraper -s PLATFORM -t 1` which will force it to only use one thread.

**Comment by Paul-Colucci** [comment]
OK, i have done more investigation based on your advice.  I tried an alternate scraper that also generates composite images (scraper ui) and it also produced randomly corrupt images.  I then used a different pi/sd card and re-ran both scrapers without issue so it does seem to most likely be a corrupt sd card.  

At least while investigating this issue I found a few other good bugs to report...

**Comment by muldjord** [comment]
Absolutely. Those bugs were important finds, thanks. And glad you figured this out in the end.
