### ISSUE TITLE
Option to disable all artwork download [DONE]

### ISSUE THREAD

**Issue by herbymachine** [muldjord/skyscraper#219]
**Describe the feature**
Option to disable all artwork download when scraping. Not just disable them from being cached locally.

**Additional context**
I am using EmuMovies Sync for the artwork. Would save a bit of bandwidth and scraping time.

Anyway, thank you for all your great work!

**Comment by muldjord** [comment]
Yes, good idea. This has now been implemented for the modules that can support it (`screenscraper`, `thegamesdb`, `arcadedb` and `mobygames`). The remaining few modules don't support it without causing potential issues, but I think it's fine as they aren't as widely used.

It simply uses the existing `--noTYPE` CLI options and `cacheTYPE="false"` config.ini options and adheres to that.

It's on master now and will be in 3.4.11. And yes, it is a lot faster if you disable some or all now.

**Comment by herbymachine** [comment]
Just tested it with the latest master and it works great! 

Thank you for your prompt help! Much appreciated!

**Comment by muldjord** [comment]
You're welcome, thanks for testing!
