### ISSUE TITLE
Sharp X68000

### ISSUE THREAD

**Issue by trevor7oaks** [muldjord/skyscraper#22]
Hi, love your scraper. Any chance you can add the Sharp X68000?

**Comment by muldjord** [comment]
Glad you like it! Yes, it has now been added to the newly released 2.4.5 (the platform is called 'x68000'). Follow the update instructions on the main github page to get it. Pleas let me know if you test it, thanks. :)

**Comment by trevor7oaks** [comment]
Awesome, thanks. I only discovered your scraper last night as I wasn’t able to scrape Atari ST with the others. Going to rescrape my other systems as I like the results. I will scrape x68000 tomorrow and let you know. Thanks again

**Comment by trevor7oaks** [comment]
Quick question, can I scrape the art to my HDD where my roms are?

**Comment by trevor7oaks** [comment]
Worked really well. Missed 9 roms out of 3000. Those after a quick look were demo disks. It missed a few video snaps, but again these seemed to be Japanese puzzle games that I wanted to filter out anyway. Thanks again
