### ISSUE TITLE
Add bin/cue format support for 3DO scraping

### ISSUE THREAD

**Issue by therealdealneil** [muldjord/skyscraper#221]
**Describe the feature / request**
Add support for reading games in bin/cue format for 3DO, in addition to the iso format that currently exists.

**Additional context**
My 3DO games are in bin/cue format and Screenscraper supports bin/cue format for 3DO as well. It would be great to have Skyscraper support this.

I tested this in a fork and it worked perfectly. My commit is here: https://github.com/therealdealneil/skyscraper/commit/ab59f04443f477a9f34a4de90c4043bb134ff215

I'd gladly submit a pull request if desired.

**Comment by muldjord** [comment]
Done. It will be in the next release. Until then you can either use your fork or the `--addext *.cue` command-line option or the config.ini option `addExtensions="*.cue"`.
