### ISSUE TITLE
Add support for video conversion [DONE]

### ISSUE THREAD

**Issue by jgcobra** [muldjord/skyscraper#222]
**Describe the feature / request**
Hi, great scraper! 

I'd like to request the ability to convert videos when they are downloaded to the cache.

Currently RetroPie/OmxPlayer does not support yuv444p format videos, but this is the format that comes from many of the scraper sources. We have to manually convert the videos to yuv420p in order for them to show up in emulationstation (when using omxplayer for hardware acceleration), otherwise you just get audio and no video playing.

Now, if we convert the videos in the roms/platform/media/video/ folder, they will get overwritten next time skyscraper builds the game list, and we're back at square one. If we convert the videos in the cache, they will get overwritten next time skyscraper scrapes, and we're back at square one. This is a problem because it makes it difficult to update one's library without having to run a lengthy conversion script every time.

Ideally, skyscraper would be able to automatically convert the videos to yuv420p format on one of its job threads in parallel to downloading during scraping. It would write a converted file to the cache, and use that when building the game list. Rebuilding the game list would then not result in losing the conversion.

**Additional context**
This post talks about the issue and provides a sample bash script to convert the videos:
https://retropie.org.uk/forum/topic/15362/script-batch-convert-yuv-4-4-4-videos-to-yuv-4-2-0-in-retropie-linux

I also find that adding '--acodec copy --vcodec copy' to the ffmpeg command optimises the conversion quality by not recompressing the audio and video in different codecs.

I appreciate this would mean an external dependency on ffprobe and ffmpeg. Personally that doesn't bother me, but I know it does bother some users/devs, so as an alternative maybe allow a user-supplied script to be run on each video file, again in a parallel job thread once the file has downloaded. This script would take as parameters an input filename and an output filename, and allow us to write our own conversion scripts.

Thanks!
Graham

**Comment by muldjord** [comment]
It's an interesting idea and something I have been wanting to do. Instead of depending on the ffmpeg lib, I could simply run the conversions in the background through a terminal inside of Skyscraper using a user-configurable command which would default to something useful in the vein of what they do in the script you linked. So in `/home/USER/.skyscraper/config.ini` there would be:
```
[main]
videoConvertCmd="videoconvert.sh %i %o"
```
So if that config exists it would run it. `%f` would be replaced by the filename and `%o` would be replaced with the active `/home/USER/.skyscraper/cache/PLATFORM/videos` folder. That way you can basically do anything you like with it.

Doing it that way it's quite simple to implement.

My only gripe with it that it will be incredibly slow on the Pi's. But as long as it isn't on by default I think it's ok.

**Comment by muldjord** [comment]
Video conversion has now been implemented on master. If someone wants to test it out I would appreciate it. I've tested it a bit myself of course, but more testing is always welcome.

How to use it is described [here](https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md#videoconvertcommandconvertvideosh-i-o)

**Comment by muldjord** [comment]
Skyscraper 3.5.3 out now with video conversion included. Read more on how to use it [here](https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md#videoconvertcommandconvertvideosh-i-o).

**Comment by geoffoxholm** [comment]
It's great that you added support to do this. As a follow-up it might be good to include a command that checks if the formatting is necessary. In my experience, only a small percent of videos need to be reformatted. To do this in a generic way you could use `jq` to check for `ffprobe` output. Here's an example that checks if there is a stream in `yuv420p` format (where `%i` is the input file):

```sh
ffprobe %i -v quiet -print_format json -show_streams | jq '.streams[] | select(.pix_fmt == "yuv420p") | any' | grep true
```

The return of this will be `0` if formatting is needed, or `1` if not.

You can add to the requirements with `and`. For example the following will also require that the width be less than or equal to 640 and the duration be 30 seconds or less:
```sh
select(.pix_fmt == "yuv420p" and .width <= 640 and (.duration|tonumber) <= 30)
```

**Comment by muldjord** [comment]
I thought about doing this, but to be honest, I feel like this is up to the user. You can run scripts with the current implementation, and running an ffprobe inside of that is not that hard.
Also, a hardcoded check would just do one thing. What if something else needs to be checked? Do I then implement a second check? I think it's best to let the user figure it out. There are plenty of threads discussing how best to convert videos for use with different frontends.

**Comment by geoffoxholm** [comment]
Ah, good point. The external script can choose to actually format, or not format.

**Comment by jgcobra** [comment]
Finally got around to testing this, great work! I agree the check should be
user choice, and I implemented it with:

#! /bin/bash

echo Converting video...
echo Source: $1
echo Dest: $2

# Check if the video is already in 420p format
c=$(ffprobe "$1" 2>&1 | grep -c yuv420p)

if [ "$c" -eq 0 ]
then
    echo Incorrect source video format detected. Converting video to 420p
format...
    ffmpeg -i "$1" -y -pix_fmt yuv420p -acodec copy -strict experimental
"$2"
else
    echo Video is in correct 420p format. Copying as is...
    cp "$1" "$2"
fi

A few bits of feedback:
1) It wasn't clear that I still need to copy (or can I move?) the source to
the dest in the case of no conversion. This could just be clarified in the
docs.
2) It would be nice if my output was collected and displayed by the
skyscraper output, or accessible in a log somewhere so I can debug my
script more easily.
3) I'm not sure if this is already how it works, but running the conversion
on another thread whilst allowing the downloads of the next assets to
continue would be a great speedup on slow connections or for large
libraries.
4) For the non-technical user, it would be good to include a stock script
set up by default. Pretty much everyone is going to be wanting to do the
same thing here - detect a 444p and convert it to 420p. It the script was
part of the codebase then more people could contribute. Even more so for
non-technical users who just wonder why some videos only make sound.

**Comment by muldjord** [comment]
Thank you for your feedback.
1) I've tried to clarify this a bit. Please let me know if it makes more sense now.
2) This is already possible with `--verbosity 3`. I've added it as a note in the docs.
3) This is how it already works.
4) If the community can decide on the gold-standard script for converting videos to use with ES running on all RPi's, I wouldn't be against adding it to the repository. Feel free to spearhead this effort on the RetroPie forums and ping me when you have settled with a script that works well. The script you have above might be a good starting point for discussing it with the community I recon.
