### ISSUE TITLE
Can't call "Skyscraper --flags help" without specifying a platform

### ISSUE THREAD

**Issue by joyrider3774** [muldjord/skyscraper#226]
**READ BEFORE YOU POST**

**Describe the bug**
Can't call `Skyscraper --flags help` without specifying a platform

**To Reproduce**
call `Skyscraper --flags help`

**Special circumstances**
none

**Terminal output**
```
pi@retropie:~/.skyscraper $ Skyscraper --flags help
------------------------------------------
Running Skyscraper v3.5.2 by Lars Muldjord
------------------------------------------
Please set a valid platform with '-p [platform]'
Check '--help' for a list of supported platforms, now exiting...

```
**Technical information**
 - Skyscraper version: `Skyscraper 3.5.2`
 - Internet connection: `ADSL / VSDL`
 - OS: `Retropie`
 - OS Version `4.6`

**Additional context**
i'm not certain if this is a bug or that --flags can change depending on the platform. I could not immediatly see it so I thought i would mention it. If they are different depending on the platform it's not bug and issue can be closed

**Comment by muldjord** [comment]
The flags are / will be context sensitive and all require a platform to be set. But I can see how this can be confusing so I'll consider how to make this more clear.
