### ISSUE TITLE
"Can't create folder

### ISSUE THREAD

**Issue by gordonfreemanhr** [muldjord/skyscraper#227]
**Describe the bug**
I'm running roms from a USB stick on my Pi Zero, which is only 15GB large, so I need to save the space. I have modified to config.ini file, editing following lines:

[main]
#inputFolder="/media/usb/retropie-mount/roms"
...
#mediaFolder="/media/usb/retropie-mount/roms"
#cacheFolder="/media/usb/retropie-mount/skyscrapercache"
[platform]
#inputFolder="/media/usb/retropie-mount/roms/amiga"
...
#mediaFolder="/media/usb/retropie-mount/roms/amiga/media"

It doesn't work. Apparently Skyscraper did create the media folder in my FDS roms directory, which is good, but when I try to scrape GB, GBC or GBA, it just says: can't create the folder. I ended up creating the MEDIA folder and subfolders in every rom folder, but it still won't work, returning the same, "can't create folder", prompt.

Also, halfway through scraping Megadrive Skyscraper says: disk is full. It's not, as the USB stick is 32GB. It means, it's still writing the cache to the Pi, despite the .ini file modification.

**To Reproduce**
I need to scrape the roms straight to the USB stick and keep the Skyscraper cache there.

**Special circumstances**
At the startup Pi Zero shows up as 100% full. I don't know why. All the roms are on the USB stick.

**Terminal output**
"Can't create the folder, check permissions", "can't write resource to cache, is the disk full?"

**Technical information**
 - Skyscraper version: 3.4.4
 - Internet connection: wifi
 - OS: included with the Pi; some Linux clone, it was put together for me
 - OS Version: the latest, I've updated recently
**Additional context**
[Replace this text with any additional context that might help understand this issue better. Optional.]

**Comment by muldjord** [comment]
Please read what it says in the config.ini file at the top. You haven't uncommented the lines, so they are ignored. The `#` means the lines are ignored.

If it can't create the folders beyond that, you have permission issues. Maybe you created the folders as root or something (with sudo). I can't really know.

**Comment by gordonfreemanhr** [comment]
You're right - I missed the uncomment thing completely. Sorry. As for the folders, apparently is working now, GB is scraping. I'm just waiting around to see if the cache was successfully moved to the USB.

**Comment by gordonfreemanhr** [comment]
I got the "cache full, cancelling network query" (or something close to this) error. Is there any way I can enlarge the cache?

**Comment by muldjord** [comment]
Does it not tell you how to disable the check in the error message? I'm pretty sure it does. I would appreciate the exact error message for future reports. That makes it a lot easier for me to figure out what you mean.

But I actually do need to fix that, as it always checks for disc space at `/home/USER/.skyscraper/`. And since you seem to have moved your cache elsewhere, it shouldn't give this error. So I will look into that. Thanks.

**Comment by gordonfreemanhr** [comment]
I don’t think it does. It just said that the cache - now moved to media\usb\retropie-mount\skyscrapercache - is full and it’s exiting all network queries. I tried to get the prompt down, but I’m out of my screencraper queries for the day and it’s just exiting the process.

However, the message - out of space, aborting now - got displayed a few times , a row under a row, and it took it good 2-4 minutes to eventually abort scraping.

Thanks a lot for looking into the issue. I have few more systems to scrape on the other Pi.

**Comment by muldjord** [comment]
You should be able to use [this](https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md#spacecheckfalse)

**Comment by gordonfreemanhr** [comment]
Space check false, thanks. I’ll try that and get back to you.

**Comment by gordonfreemanhr** [comment]
It worked. Good tip. Thanks!
