### ISSUE TITLE
screenscraper: manual query not working

### ISSUE THREAD

**Issue by igno2k** [muldjord/skyscraper#231]
**Describe the bug**
When using --query with screenscraper module an error is thrown:
ScreenScraper APIv2 returned invalid / empty Json
The erroneous answer was written to '/home/USER/.skyscraper/screenscraper_error.json'.
content: Il manque des champs obligatoires dans l'url
in english: Mandatory fields are missing in the url

**To Reproduce**
Skyscraper -p <platform> -s screenscraper --query "query" <filename>

**Technical information**
 - Skyscraper version: 3.5.4
 - OS: Arch Linux

Any idea whats wrong?

**Comment by muldjord** [comment]
you have to add the required fields as the query. What did you wish to accomplish by setting the query to `--query "query"`? Or was that just an example?

You are, at the very least, required to give it a checksum as described in the docs [here](https://github.com/muldjord/skyscraper/blob/master/docs/CLIHELP.md#--query-string). Please read all of that. It has the examples.

**Comment by igno2k** [comment]
Thanks, when I use md5=<CHECKSUM> in the query it works fine.
I was assuming that I can use just a simple query with the screenscraper module but that does not work.

**Comment by muldjord** [comment]
Glad you figured it out. It works mostly with checksums, so they are required. I think you might be able to use `--query "romnom=FILENAME"` but I'm not sure.

Closing this.
