### ISSUE TITLE
No populated ROM folders on NFS mount of the whole rom folder

### ISSUE THREAD

**Issue by mxovd** [muldjord/skyscraper#234]
**Describe the bug**
Skyscraper can't find the roms inside the default rom folder when mounted over nfs.

**To Reproduce**
Edit retropie /etc/fstab to mount the complete rom folder
192.168.0.150:/Roms /home/pi/RetroPie/roms nfs defaults 0 0

**Special circumstances**
Permissions of my roms folder
drwxrwsr-- 9 pi pi 4096 May 23 05:02 roms     
Permission of the platform folder
drwxrwsr-- 2 pi pi 40960 May 22 14:29 snes 
Permission of a rom
-rw-rw-r-- 1 pi pi

**Terminal output**
No populated ROM folders were found in /home/pi/RetroPie/roms

**Technical information**
 - Skyscraper version: 3.5.5
 - Internet connection: wired
 - OS: RetroPie on rpi4
 - OS Version 4.6.1

**Comment by muldjord** [comment]
I just tried this by mounting one of my NAS nfs folders to `/home/USER/RetroPie/roms` and it worked without issue. My guess is you have a permission issue somewhere else. It does not seem to be a Skyscraper issue.

**Comment by muldjord** [comment]
The permissions on one of the platform folders for me is:
```
drwxrwxr-x user:user
```
I can't remember what the `s` is that you are getting, but maybe that's your issue.

**Comment by mxovd** [comment]
You are right, I changed the permissions of the folder to
drwxrwxr-x+  9 root  users 4096 May 23 13:02 roms
and now it's working. I'm not sure if it's the SGID or the execute permission for others that fixed it, but it's working now.

Thank you very much!
