### ISSUE TITLE
Please add support for SNES MSU-1 platform

### ISSUE THREAD

**Issue by igno2k** [muldjord/skyscraper#235]
**Describe the feature / request**
Please add support for the SNES MSU-1 platform. MSU-1 gives you the ability to add FMV and PCM quality sound to a SNES game.

The file extensions are identically to the snes platform.
The screenscraper platform code is: 210
I suggest the Skyscraper platform name: snesmsu1

Normally the file structure would be as the following:

snesmsu1/<gamename>/<gamename.sfc|smc|zip>

Additionally files (FMV and PCM files) are in the <gamename>-folder, but can be ignored for scraping.

Thanks!

**Comment by muldjord** [comment]
You should be able to just place the files in the `snes` folder. I am hesitant to start adding all these sub-platforms unless absolutely necessary. The MSU-1 platform is a subplatform of snes within ScreenScraper. It should work just by placing your files in `snes`. Please try that.

**Comment by igno2k** [comment]
Thanks, that is working perfectly fine!
