### ISSUE TITLE
Attract Mode list generator - add game description

### ISSUE THREAD

**Issue by sidamo82** [muldjord/skyscraper#238]
Hi

When Skyscraper generates attract mode game list, it reported two times rom name.

Example for bubble bobble:

Name;Title
bublbobl;bublbobl

I suggest to put on Title field, game description information instead of rom name.

Example for bubble bobble:

Name;Title
bublbobl;Bubble Bobble

**Comment by muldjord** [comment]
It already does this, so my guess is you set `--flags forcefilename`. Can you verify this?

**Comment by sidamo82** [comment]
you're in right, sorry it's my error.

I close this thread

Thank you
