### ISSUE TITLE
Backup existing game list file

### ISSUE THREAD

**Issue by igno2k** [muldjord/skyscraper#240]
**Describe the feature / request**
It would be nice to have the option to backup existing game list files when generating a new one. 
Example for Pegasus:
Original:
metadata.pegasus.txt
Backup:
metadata.pegasus.txt.bak
After that you could compare the files with system tools like diff / vimdiff.

**Additional context**
Setting should also be configurable via config.ini, e.g.:
alwaysBackupConfig="True"
backupConfigExt=".bak"

**Comment by muldjord** [comment]
Good idea. I'll add it to the roadmap, but I'll make it automatic so no configuration is needed.

**Comment by muldjord** [comment]
This has now been implemented and will be in 3.5.6. It won't be enabled by default. Can be enabled with the `gameListBackup="true"` config.ini option in either the `[main]` section or a `[FRONTEND]` section.

It's documented [here](https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md#gamelistbackuptrue)

**Comment by igno2k** [comment]
Great, thank you!
