### ISSUE TITLE
Sound enable/disable option in video scraping

### ISSUE THREAD

**Issue by gguilher** [muldjord/skyscraper#241]
**Describe the feature / request**

Hi,
I've tried to add in the ffmpeg converting options "-an" to disable audio in video, since my emulation station already has one background music and it is overlapping with the video sound.
But now the video is not scrapped. Idk why... can you please suggest what I can do ?

Also, if you are planning to add the audio options,
Maybe you can add volume options, like [mute or 30% or 60% or 100%]

Thanks.

**Comment by muldjord** [comment]
Most likely your script / command is not working. Please read the docs [here](https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md#videoconvertcommandconvertvideosh-i-o). Pay attention to the notes which describe how to enable debug output for the conversion.

**Comment by gguilher** [comment]
thanks for sharing this docs, I havent pay attention to them before.
