### ISSUE TITLE
Scraping through retropie-setup.sh seems to ignore videoConvertCommand setting

### ISSUE THREAD

**Issue by bagerard** [muldjord/skyscraper#243]
**Describe the bug**
I have some videos that needs to be converted after they are downloaded. I have found the `videoConvertCommand` setting that seems to be tailored for that but setting `videoConvertCommand` in `.skyscraper/config.ini` doesn't seem to be taken into account during scraping through the `retropie-setup.sh`

**To Reproduce**
I have first tried with `videoConvertCommand="ffmpeg -i %i -y -pix_fmt yuv420p -t 00:00:10 -c:v libx264 -crf 23 -c:a aac -b:a 64k -vf scale=640:480:force_original_aspect_ratio=decrease,pad=640:480:(ow-iw)/2:(oh-ih)/2,setsar=1 %o"` in the [main] but I couldn't see any impact of it on the videos (and scraping time was the same)

So I then tried with`videoConvertCommand="not_existing_script.sh %i %o"` into [main] (the bash script doesn't exist) assuming that it would fail abruptly if it was using it. Running the scraping went fine, like if it had ignored during the setting.

**Special circumstances**
I'm doing the scraping through the retropie-setup.sh > manage packages > manage optional packages > skyscraper, and I've also forced the cache refresh

**Terminal output**
NA

**Technical information**
 - Skyscraper version: 3.5.5
 - Internet connection: wifi
 - OS: retropie
 - OS Version retropie 4.6 (rpi4)

**Comment by muldjord** [comment]
I just tested this on my own setup and it works just fine for me through the retropie_setup.sh script. Added the command to the main section of config.ini, enabled refresh and scraped videopac games with screenscraper. Skyscraper shows:
```
Cache output:
Video conversion: Success!
```
And the video files are located in the cache as expected.

You neglected to add the terminal output. There's information on the video conversion in it if it's enabled. Please add that. And as the docs mention, you can get further information with the `--verbosity=3` CLI option. You can also set it in config.ini under `[main]` with `verbosity="3"`.

And just to be sure, you did install ffmpeg, right?

**Comment by bagerard** [comment]
Thanks for having a look, yes ffmpeg is installed but I ll double check later today and provide the output

**Comment by bagerard** [comment]
Argh... I figured out I was actually running v3.5.2. Shame on me.... Just upgraded and it now works like a charm. Thanks for the quick help and sorry for wasting your time on this 

And a big THANK YOU for the scraper, it's a really cool tool!

**Comment by muldjord** [comment]
Glad you got it working. :) Have fun!
