### ISSUE TITLE
Media files don't copy if artwork path uses $HOME

### ISSUE THREAD

**Issue by spilinek** [muldjord/skyscraper#245]
I've successfully scraped nes data from screenscraper. I can see the media files in skyscraper cache. When I generate a nes game list for attract mode frontend the games list is generated, but the media files never get copied from the cache. No errors are reported (tried verbosity set to 3).

Eventually I figured out the problem is with the emulator cfg file. I created $home/.attract/emulators/NES.cfg as a copy of $HOME/.attract/emulators/templates/nestopia.cfg. The nestopia.cfg template uses $HOME in the artwork paths. 

I updated NES.cfg replacing $HOME with the absolute path. Now when I generate the games list the media files are copied from the skyscraper cache.

I'm using Skyscraper v3.5.2

**Comment by muldjord** [comment]
Does Attract-mode support using the `$HOME` variable? Please post your `NES.cfg` file so I can see what I need to work with.

**Comment by spilinek** [comment]
Attract Mode supports using the **$HOME** variable. I originally scraped media for Emulationstation and now I'm trying out Attract Mode. In **NES.cfg** I had:

```
# Generated by Attract-Mode v2.6.1
#
executable           /opt/retropie/supplementary/runcommand/runcommand.sh
args                 0 _SYS_ nes "[romfilename]"
rompath              $HOME/RetroPie/roms/nes/
romext               .7z;.nes;.zip;.7Z;.NES;.ZIP
system               Nintendo Entertainment System (NES)
info_source          thegamesdb.net
artwork    flyer           $HOME/RetroPie/roms/nes/media/covers
artwork    marquee         $HOME/RetroPie/roms/nes/media/marquees
artwork    snap           $HOME/RetroPie/roms/nes/media/screenshots
artwork    video           $HOME/RetroPie/roms/nes/media/videos
artwork    wheel           $HOME/RetroPie/roms/nes/media/wheels
```

With the **$HOME** variable the artwork would show up in Attract Mode. 

I made a custom **artwork-attractmode.xml** to change how some of the artwork was created. When I generated the games list with Skyscraper the media wouldn't change. Problem went away once I updated **NES.cfg** replacing **$HOME** with absolute path:
```
# Generated by Attract-Mode v2.6.1
#
executable           /opt/retropie/supplementary/runcommand/runcommand.sh
args                 0 _SYS_ nes "[romfilename]"
rompath              $HOME/RetroPie/roms/nes/
romext               .7z;.nes;.zip;.7Z;.NES;.ZIP
system               Nintendo Entertainment System (NES)
info_source          thegamesdb.net
artwork    flyer           /home/jeremy/RetroPie/roms/nes/media/covers
artwork    marquee         /home/jeremy/RetroPie/roms/nes/media/marquees
artwork    snap            /home/jeremy/RetroPie/roms/nes/media/screenshots
artwork    video           /home/jeremy/RetroPie/roms/nes/media/videos
artwork    wheel           /home/jeremy/RetroPie/roms/nes/media/wheels
```

**Comment by muldjord** [comment]
Great, thanks for the clarification. I will make sure `$HOME` is substituted correctly inside Skyscraper from the next version.

**Comment by muldjord** [comment]
This is now fixed on master if you want to test it out.
