### ISSUE TITLE
Prevent clobbering certain pegasus fields, or otherwise define custom ones to re-add

### ISSUE THREAD

**Issue by TiZ-HugLife** [muldjord/skyscraper#247]
**Describe the feature / request**
At present, if I add custom fields to a metadata.pegasus.txt file, like `ignore-regex` to stop pegasus from snooping in my multi-disc PS1 isos folder, or a custom value to a game's section that Skyscraper doesn't normally care about, they are lost if I regenerate the game list. I don't anticipate I will regenerate the list particularly often, but it's not ideal in cases where I very well may regenerate often, like if I'm still growing certain parts of my collection.

If it was possible to add custom fields per-platform and per-game, this wouldn't be too much of a concern. I can't see any facilities to do that in config.ini or through the cache. I can always just make a script that puts it back in but I think it'd be more elegant to have support for that in Skyscraper itself.

Thanks for your work on this software, it's been lots of help! :)

**Comment by TiZ-HugLife** [comment]
The documentation on the metadata, which lists all the nodes it supports, is [here](https://pegasus-frontend.org/docs/user-guide/meta-files/).

I'm not sure I can answer your question properly without knowing how the other frontends are handled. Which values are retained for Attract-Mode and EmulationStation?

Do they retain values that are kept in the cache and used for generation like name and description, or only values that are meaningful to the frontend but not particularly meaningful to Skyscraper itself? Like... if someone goes and tweaks the name of a game in the game list, even if that game name is different in the cache, does it keep that tweaked name and other manually changed values, or replace them with its own cache entries while leaving alone nodes that it knows are significant but doesn't personally care about? Like, if someone makes a custom node for their scripts or something, does it keep that?

One thing I also wonder about, is if you *remove* a node that it knows about, should it care about that? For example, you can take out the `extensions:` per-collection node and that will cause pegasus to simply not scan a directory on startup--which is particularly useful if you keep all your PC games in one folder--and only use the manually-defined games. (If Skyscraper is generating the metadata file anyways, I'm personally of the mind that it doesn't need to include the extensions node.) If you replace a singular `file:` node on a game section with a `files:` list so that you can manually define a multi-disc game, is that something it should care about?

**Comment by TiZ-HugLife** [comment]
Another example, it seems that Skyscraper seems to be determined to refer to the Sega Genesis as the Megadrive even if USA is at the top of my region preference. If I change the name of the collection to "Genesis", I feel like it should leave that alone too, especially if the current meta for the other frontends is leaving alone manually changed values. And that could make it so you don't really have to implement logic that names platforms based on region.

**Comment by muldjord** [comment]
For ES, the following are retained (copy/paste from my GameEntry class):
```
  QString eSFavorite = "";
  QString eSHidden = "";
  QString eSPlayCount = "";
  QString eSLastPlayed = "";
  QString eSKidGame = "";
  QString eSSortName = "";
```
For Attract-Mode, the following are retained (copy/paste from GameEntry):
```
  QString aMCloneOf = "";
  QString aMRotation = "";
  QString aMControl = "";
  QString aMStatus = "";
  QString aMDisplayCount = "";
  QString aMDisplayType = "";
  QString aMAltRomName = "";
  QString aMAltTitle = "";
  QString aMExtra = "";
  QString aMButtons = "";
```
So basically it differs from frontend to frontend and I can potentially retain anything I decide to include. But the basic rule is this: If a retainable config already exists, it will retain it. If not, it will use the data from Skyscraper. And for configs that doesn't already exist, it will also use the data from Skyscraper.

**Comment by muldjord** [comment]
Just wanted to let you know that I've started work on this and is quite far along. Basically I want to bring the Pegasus module up to speed with the other frontends. This will include retaining all data from an existing Pegasus game list (probably even including any custom ones you might have added) and also allow you to skip existing game list entries when scraping or creating a game list. It should be good once it's finished. I'll update here when I have something.

**Comment by TiZ-HugLife** [comment]
Hey there, I was literally just typing up a reply when yours popped up! I'll go ahead and finish what I'm saying in case it proves useful to you. Thank you very much for your time!

Looks like pegasus does have a sort-by field in line with attract-mode and ES. Alternate forms sort_title and sort_name are also accepted. There are several ignore-* fields that I think should either be retained, and/or have excludeFiles adapted to them. excludeFiles uses asterisk patterns while ignoreRegex uses perl regex. The workdir/cwd fields aren't supported by Skyscraper and should thus also be retained. And lastly, pegasus does allow for extension keys starting with x-, and I feel like we also shoud retain those.

**Comment by muldjord** [comment]
Thank you for this information, it will prove useful as I work my way through it. I think I will end up parsing this in two badges. First there's the game list-related variables. And then there's the game-related variables. For each there are some that Skyscraper will output. And then there's others that Skyscraper doesn't know about. For the unknowns I will just retain them as they are without touching them. For the known ones I will retain them as well unless it only makes sense to regenerate them. So I think I have a battleplan for it. Currently I'm working on a Pegasus game list parser that will load all of the information. It's pretty straightforward, but will need a lot of testing once it's done. I'll keep you posted.

**Comment by TiZ-HugLife** [comment]
I will be very happy to test! Thank you!

**Comment by muldjord** [comment]
This is now implemented and on master. It will be in 3.5.6, but testing would be appreciated. Remember to build from master to test it. It's not part of the current 3.5.5 release.

So how does it work?
It parses the Pegasus game list files in two parts: Header and games. Both sections can have as many custom key-value pairs as you like. So, for instance, you can add an `ignore-regex: VALUE` to the header, and it won't be overwritten when the game list is later regenerated. Same goes for any custom key-value pairs for a game.

Header fields that Skyscraper will export itself (eg. `command: VALUE`, `short-name: VALUE` etc.) will be created when generating a Pegasus game list with Skyscraper initially. But if they already exist inside an existing game list file, they will be preserved *as is*.

For the game listings it's a bit different. Any user-defined fields will be preserved. But for the fields that Skyscraper exports, they will only be preserved if Skyscrapers own entry has that particular field empty.

Let me know if you do test this out and have any questions.

**Comment by TiZ-HugLife** [comment]
Hey there. I gave it a shot and it seems to work for the most part. It preserves ignore- field. And it preserves custom fields per-game. It does not preserve deletion of the extensions field. This is kind of important because in my setup steamapps is a subdirectory of where metadata.pegasus.txt is located, which causes it to recursively scan for files and never finish. Unfortunately it looks like no exclusions are actually effective at stopping it from recursing. That said, it's simple enough to automate deletion of the extensions field on my end.

The new version makes it much more efficient to add games to Pegasus! :)

**Comment by muldjord** [comment]
Do you know if the extensions field is even necessary? I mean, isn't it only used so it can locate games that aren't on the list? In that case I can just as well remove it entirely. I only add it because I thought it was a requirement.

EDIT: Thank you for testing by the way! I have tested it myself of course, but my experience with Pegasus is quite limited, so it's great to have someone more knowledgeable test it out. :+1:

**Comment by muldjord** [comment]
I just tried removing the `extensions` variable altogether. It doesn't seem to be needed, as long as the games are listed in the file. So I'll just remove it and release a `3.5.7` version that doesn't use it.

**Comment by muldjord** [comment]
3.5.7 out now without `extensions`. I also made the Pegasus string conversion more robust by implementing regular expressions.

**Comment by TiZ-HugLife** [comment]
Awesome. Confirmed extensions is gone from the metadata. Yeah, we don't really need to define extensions since the whole point of Skyscraper is to make the process of creating a defined list much smoother. Good call. :)

If I add the extensions key manually it will keep it on regeneration, but it won't put it back if I take it out. Very nice! :D

**Comment by muldjord** [comment]
Awesome, glad it works!
