### ISSUE TITLE
Add no-intro game name options for gamelist generation

### ISSUE THREAD

**Issue by miaoanbang** [muldjord/skyscraper#248]
**Describe the feature / request**
I have recently tried to scrape medias in retropie for fbneo roms. It came to my attention that when there is no scraping, fbn game list is displaying the full no-intro game names without any issue. However, after scraping the game names of parent and child roms become the same and there is no way for skyscraper to reuse the old no-intro game names to help differentiate the games. Can anyone help add a option to allow no-intro game name for gamelist generation so that different parent and child roms can be easily identified?

**Comment by muldjord** [comment]
I don't understand what you mean. Please provide examples of anything you are trying to describe.

> It came to my attention that when there is no scraping...

Do you mean when the scraping modules don't provide a result?

> there is no way for skyscraper to reuse the old no-intro game names to help differentiate the games

Where did this game name come from then? If it's the filename, just use `--flags forcefilename` and regenerate the game list.

> Can anyone help add a option to allow no-intro game name for gamelist generation so that different parent and child roms can be easily identified?

I have no idea what this means, sorry.

**Comment by muldjord** [comment]
I just found [this](https://retropie.org.uk/forum/topic/26699/fbn-scraper-display-same-name-for-parent-child-roms). I think that might be what you mean, but I'm not sure.

**Comment by muldjord** [comment]
I just realized that is probably you.

**Comment by miaoanbang** [comment]
Yes its me. Can you help to add an option in the script to disable name override?
I believe that the default rom display names for at least fbneo games are from the dats files.

**Comment by muldjord** [comment]
If it's about the RetroPie-Setup script for Skyscraper you should ask on the RetroPie forums. I am not currently active on working on the script and recently (yesterday) also seized work on implementing new features into Skyscraper due to wanting to pursue other projects after working on Skyscraper for 3 years straight.

**Comment by miaoanbang** [comment]
ok noted. I am closing this feature request.
