### ISSUE TITLE
Windows version 

### ISSUE THREAD

**Issue by blc29seb** [muldjord/skyscraper#249]
Hi 
First thanks for your job 
i never used github it's for that i write this message :)
I modified the code for use with screenscraper and emulationstation on windows
the others features are also included but i haven't tested them
i made several modifications  (request feature) 
- change the home directory to where is skyscraper.exe 
- I modified the platform.cpp (platformcsv.cpp) file to use an external csv file (easy add platform for screenscraper just add it in csv file   format :    "platform";"extensions";screenScraperId  )
- I modified the relative path for emulationstation frontend (add frontendFolder config variable)

I put the source files here (search  blc29 to find the modifications): 
https://drive.google.com/file/d/1CzMYcpkO7IdD6g8YQN9Xj8XLHi1lzA_-/view?usp=sharing

and the compiled version (static) here : 
https://drive.google.com/file/d/1KFZZ5muxPhIN202Urc7vRz2EgL7AVSLa/view?usp=sharing
just unzip and modify the ./skyscraper/config.ini   (PS : i desactived the scripter)

Sorry for my bad english and thanks again for your code 
best regards

**Comment by muldjord** [comment]
This is a PR (pull request). Please see the README.md for contributions. Thanks.
