### ISSUE TITLE
There is no Mame...

### ISSUE THREAD

**Issue by mchaos** [muldjord/skyscraper#25]
This works great, but has nothing for Mame...

**Comment by muldjord** [comment]
Can you elaborate a bit on this please? I am not sure what you mean. You can scrape mame roms using any of the arcade platforms such as 'arcade', 'neogeo' or 'fba'.

**Comment by mchaos** [comment]
There is no option to scrape mame emulator. Unless I am missing it. I don't
see it in the list and typing mame, or mame4 all etc doesn't work. I also
tried, arcade. Doesn't work. I have a lot of games on mame4all and I like
the way your scraper works.

**Comment by muldjord** [comment]
If you add your mame zipped roms to the 'arcade' folder in RetroPie, it will scrape them. Just tested it and it works fine.

**Comment by mchaos** [comment]
So I have to move all 3000 mame games to a different folder that mame4all
doesn't use.... to scrape them? Doesn't make sense. How do I get it to use
mame4all folder? I tried telling it where it was and doesn't work.

**Comment by muldjord** [comment]
You can set the input folder with '-i'. Please check the output of '--help' for all available options.

**Comment by muldjord** [comment]
'mame-advmame', 'mame-libretro' and 'mame-mame4all' now added as platforms using the folders described in the official RetroPie documentation here: https://github.com/retropie/retropie-setup/wiki/MAME

Please update to 2.4.9 to get this functionality and use the '-p mame-mame4all' platform when scraping from the '/home/pi/RetroPie/roms/mame-mame4all' folder. [Check here](https://github.com/muldjord/skyscraper#updating-skyscraper) on how to update.

**Comment by mchaos** [comment]
Brand new install, most up to date on all....

**Comment by muldjord** [comment]
I just updated Skyscraper to 2.4.9 a couple hours ago, so please upgrade to that if you want the mame platforms included.

**Comment by mchaos** [comment]
Will do.

Thanks
