### ISSUE TITLE
MSDos scraping

### ISSUE THREAD

**Issue by gordonfreemanhr** [muldjord/skyscraper#251]
It’s not really an issue - a question morelike: I managed to achieve a decent number of scraper on all of my ~40 platforms, with the exception of DOS. I get 20/400 matches at best from all sources, mainly the evergreen titles such as Doom or Alone In The Dark - and not a single one from Screenscraper, which is odd. The whole thing seems kind of irregular.

I’m scraping .conf files only.

Is that a known issue? Is there any workaround? Thanks!

**Comment by muldjord** [comment]
Please keep this to bug reports and feature requests only, thanks. :) I've answered your inquiry on the RetroPie forums, which is the correct place to ask these questions.

**Comment by gordonfreemanhr** [comment]
Thanks and sorry. I will :)
