### ISSUE TITLE
Support .m3u files for Gamecube and Dreamcast

### ISSUE THREAD

**Issue by spilinek** [muldjord/skyscraper#252]
The .m3u file extension is used for mult-disc games. 

CONFIGINI.md mentions reporting file extensions that should be supported by default. Currently I'm using in config.ini:

**[gamecube]
addExtensions=*.m3u
[dreamcast]
addExtensions=*.m3u**

After making this change I was able to generate gamelists with .m3u. I found the change needs to be made in platform.cpp in order to support .m3u by default.

**Comment by muldjord** [comment]
Added, will be in 3.5.6 soon.
