### ISSUE TITLE
ExcludeFiles doesn't work with --cache report:missing

### ISSUE THREAD

**Issue by spilinek** [muldjord/skyscraper#254]
I've added a couple file patterns to exclude in my config.ini. These are MAME BIOS files.

[arcade]
emulator="Arcade"
artworkXml="artwork-arcade.xml"
excludeFiles="cchip.zip,namco*"

I run below command:
**Skyscraper -p arcade --onlymissing -s screenscraper**

The BIOS files were not scraped. I also verified the BIOS files were not added to quickid.xml and db.xml. I believe this confirms my excludeFiles setting in config.ini is working.

Next I ran below command:
**Skyscraper -p arcade --cache report:missing=releasedate**

The resulting report includes the BIOS files that are ignored with excludeFiles="cchip.zip,namco*".

**Comment by muldjord** [comment]
Thanks, this will be fixed in 3.5.6.

EDIT: It's now on master

**Comment by muldjord** [comment]
3.5.6 (and 3.5.7 actually) out now where this is fixed. Gonna close this now. Let me know if you experience issues, then I can reopen it.
