### ISSUE TITLE
Amiga WHDLoad scraping problem

### ISSUE THREAD

**Issue by Villemann** [muldjord/skyscraper#256]
I have encountered strange problem during scraping Amiga games (WHDLoad lha files).
For example:
I have Dynablaster files (versions 1.2, 1.3, 1.4, 1.5 and 1.6). Versions from 1.2 to 1.4 are scraped correctly. Scraping versions 1.5 and 1.6 gives no results (game not found). All files are present in WHDLoad XML and have correct sha1 control sum. Is this problem with scraper program or screenscraper database?

**Comment by Villemann** [comment]
Ok, screenscraper dosent have this release in the database - scraper works fine. Case closed.

**Comment by muldjord** [comment]
Scraping the WHLoad files I can recommend using the `openretro` source in Skyscraper. It is specialized for the WHLoad files. Try it out, should give you great results.
