### ISSUE TITLE
neo geo cd import

### ISSUE THREAD

**Issue by AndyG482** [muldjord/skyscraper#257]
can you add neogeo (chd) import?

chd files in neogeo folder without any subdirs.

**Comment by muldjord** [comment]
`neogeocd` in Skyscraper already supports `*.chd` so I'm not really sure what you mean.

**Comment by AndyG482** [comment]
i put my chd files in neogeo folder. i dont use subfolders in neogeo folder.
import screenshots from local import folder doesnt work

show successfully processed 0 games, but i have 65 chd files in neogeo folder
all other systems works fine

**Comment by muldjord** [comment]
You should use the `neogeocd` platform instead, please try that. The `neogeo` platform doesn't support CD images. If you insist on using it, you can add the extension manually https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md#addextensionszst-smt

**Comment by AndyG482** [comment]
thx. if i use neogeocd folder then its works fine.
