### ISSUE TITLE
non-default directories not showing up

### ISSUE THREAD

**Issue by taylorn84** [muldjord/skyscraper#262]
Hi,
Admittedly, I am not an expert but I have read all the guides and looked around for a solution but I can't for the life of me figure this one out.  

I have changed the config.ini in ./home/[user]/.skyscraper/config.ini to point to an external hard drive which houses my roms.  It simply does not show up and currently the only way I can scrape any game is by putting it in the retropie/roms folder - which isn't possible with the size of my collection.  

below is the my config. (have changed my actual username with "[user]"

[main]
inputFolder="/media/[user]/External/roms"
gameListFolder="/home/[user]/RetroPie/roms"
gameListBackup="false"
mediaFolder="/home/[user]/RetroPie/roms/media"
cacheFolder="/home/[user]/.skyscraper/cache"
cacheResize="false"
nameTemplate="%t [%f], %P player(s)"
jpgQuality="95"
cacheCovers="true"
cacheScreenshots="true"
cacheWheels="true"
cacheMarquees="true"
importFolder="/home/[user]/.skyscraper/import"
unpack="false"
frontend="emulationstation"
emulator=""
launch=""
videos="true"
videoSizeLimit="42"
videoConvertCommand="ffmpeg -i %i -y -pix_fmt yuv420p -t 00:00:10 -c:v libx264 -crf 23 -c:a aac -b:a 64k -vf scale=640:480:force_original_aspect_ratio=decrease,pad=640:480:(ow-iw)/2:(oh-ih)/2,setsar=1 %o"
videoConvertExtension="mp4"
symlink="false"
brackets="true"
maxLength="10000"
threads="2"
pretend="false"
unattend="false"
unattendSkip="false"
interactive="false"
forceFilename="false"
verbosity="1"
skipped="false"
maxFails="30"
lang="en"
region="wor"
langPrios="en,de,es"
regionPrios="eu,us,ss,uk,wor,jp"
minMatch="0"
artworkXml="artwork.xml"
relativePaths="false"
addExtensions="*.zst"
hints="false"
subdirs="true"
spaceCheck="true"

Please help!!

**Comment by muldjord** [comment]
Make sure you have the roms in the required subfolders below the mountpoint. So `n64` roms should be placed in `/media/[user]/External/roms/n64` and so on. Don't just add them to the `/media/[user]/External/roms` folder. That won't work with the `config.ini` you posted.

I just tested this on my own setup with a USB disk mounted at path similar to yours. It works just fine, so if the above doesn't fix your problem I'm guessing it's a permission problem.

EDIT: Btw, I would remove the following from your `config.ini`:
```
gameListFolder="/home/[user]/RetroPie/roms"
```
Your `gameListFolder` variable doesn't do anything since it already defaults to the same as `inputFolder`.

Another quick note: A lot of your remaining config variables are unnecessary as they are set at the defaults and only clutter your config.ini. You should only ever set a config variable if you specifically need it to be changed.

**Comment by taylorn84** [comment]
Thanks for the reply but unfortunately it still isn't working.  I thought maybe permissions were the issue but even if I point to different path in my home folder (with a test rom in there of course) it doesn't pick up anything.  All it continues to show are the default directories (/home/[user]/RetroPie/roms) instead of where I'm pointing to in the config.ini 

I'm using Ubuntu 18.04 if that makes any difference or if you can think of another reason why it might not be working

Appreciate the help and I didn't mention before but amazing work on this!!  Apart from this tiny issue, Skyscraper has worked perfectly!  👍

**Comment by muldjord** [comment]
Did you see my comment about the subfolders?

Try renaming your current config.ini to config.ini.bu or something. Then create a new one with just the following:
```
[main]
inputFolder="/media/[user]/External/roms"
```
Then create a folder for one of the platforms you have roms inside that folder. For instance:
```
/media/[user]/External/roms/snes
```
And put a rom in that folder, so the final path is:
```
/media/[user]/External/roms/snes/romfile.zip
```
Then run:
```
Skyscraper -p snes -s thegamesdb --refresh
```
Be sure to check that the `Input folder` is set. Skyscraper will tell you this when it starts. So look for that and verify that it's found your config and set it to `/media/[user]/External/roms/snes`.

Lastly, make sure your paths have the 100% matching casing. Linux is case-sensitive (some Windows users don't know this, and I don't know if you know, so now you know if you didn't know).

I just tested this procedure on Ubuntu 20.04 and it works.

Good luck!

**Comment by taylorn84** [comment]
oh ok!  So this only works through command line and not through retropie_setup.sh?  

Thanks for the above - it now all works but silly me wasn't using command line and was only using retropie

**Comment by muldjord** [comment]
Glad you got it working. Yes, this only works for commmand-line. The RetroPie scripts forces a different input folder with the `-i FOLDER` option that corresponds to the setting you have chosen in the script menu. So it will ignore your config.ini entry. 👍
