### ISSUE TITLE
Empty Json on Screenscrapper Api v2

### ISSUE THREAD

**Issue by navyseai** [muldjord/skyscraper#264]
**Describe the bug**
When gathering resources  it says the Json is empty (report bug)

**To Reproduce**
Gather resources for pc using  ScreenScrapper 

**Terminal output**
"Screencrapper APIv2 returned invalid / empty Json"

**Technical information**
 - Skyscraper version: 3.5.8
 - Internet connection: cable
 - OS: RetroPie

**Comment by muldjord** [comment]
This is because the screenscraper service has been down. It will work again when they have their API up and running again (which they might already).

**Comment by jserrafindster** [comment]
sorry my ignorance, just wondering, shouldn't we add a online validation for the service before starting the scrapper? rather than ask the user to open a bug?

**Comment by navyseai** [comment]
sorry my ignorance, just wondering, shouldn't we add a online validation for the service before starting the scrapper? rather than ask the user to open a bug?

**Comment by muldjord** [comment]
That would be optimal, yes. But I'm not currently working on Skyscraper. I will add it to the roadmap though.
