### ISSUE TITLE
ScreenScraper APIv2 returned invalid / empty Json

### ISSUE THREAD

**Issue by sublinn** [muldjord/skyscraper#265]
Terminal is reporting:
The erroneous answer was written to '/home/USER/.skyscraper/screenscraper_error.json'. Please create a bug report at 'https://github.com/muldjord/skyscraper/issues' and attach that file.
[screenscraper_error.json.txt](https://github.com/muldjord/skyscraper/files/5402946/screenscraper_error.json.txt)

**Comment by muldjord** [comment]
This is because the screenscraper service has been down. It will work again when they have their API up and running again (which they might already).

**Comment by muldjord** [comment]
Leaving open due to duplicates of this being reported right now.

**Comment by sublinn** [comment]
Thank you for the awareness. I'll post back if/when I see the issue resolved. Please let me know if there's anything I can do to help. - Adam

**Comment by sublinn** [comment]
This issue can be closed.

**Comment by sublinn** [comment]
Closing issue.

**Comment by muldjord** [comment]
This is still an issue, keeping open. Their API is still unstable / down and results in this error.

**Comment by muldjord** [comment]
Seems this is fixed on their end now.
