### ISSUE TITLE
"screenscraper.fr" website is down

### ISSUE THREAD

**Issue by sublinn** [muldjord/skyscraper#267]
**Describe the bug**
Attempting to scrape without using username or password prompts:
Forcing 1 threads as this is the anonymous limit in the ScreenScraper scraping module. Sign up for an account at https://www.screenscraper.fr and support them to gain more threads. Then use the credentials with Skyscraper using the '-u user:password' command line option or by setting 'userCreds="user:password"' in '/home/USER/.skyscraper/config.ini'.

the issue is that the website the terminal message above is directing us to "https://www.screenscraper.fr" is either down, or the link is incorrect - in either case it's not a website that any of my computers/browsers can navigate to. This prohibits me from creating an account because the website or link is down/incorrect.

**To Reproduce**
Scrape without a username and password.

**Terminal output**
Forcing 1 threads as this is the anonymous limit in the ScreenScraper scraping module. Sign up for an account at https://www.screenscraper.fr and support them to gain more threads. Then use the credentials with Skyscraper using the '-u user:password' command line option or by setting 'userCreds="user:password"' in '/home/USER/.skyscraper/config.ini'.

**Technical information**
 - Skyscraper version: Skyscraper by Lars Muldjord (3.5.8)
 - Internet connection: Cable
 - OS: Skyscraper on RetroPie on Linux Mint
 - OS Version: Linux Mint 19.3 Cinnamon

**Comment by muldjord** [comment]
Hi, their website is down right now. The link is correct. They have been having issues for the last couples of weeks and it seems they haven't fixed all of it yet.

**Comment by APGRoboCop** [comment]
Website is back online!
