### ISSUE TITLE
Error from screenscraper when sending a query

### ISSUE THREAD

**Issue by ferarias** [muldjord/skyscraper#269]
**Describe the bug**
Trying to send a direct query returns an error from the API

**To Reproduce**
Skyscraper -p gba -i /mnt/emu/roms/gba -s screenscraper -u xxxx:yyyy --query "The+Incredibles" /mnt/emu/roms/gba/Incredibles.zip

**Special circumstances**
I'm using WSL, but everything else works fine.

**Terminal output**
`------------------------------------------
Running Skyscraper v3.6.1 by Lars Muldjord
------------------------------------------
Platform:           'gba'
Scraping module:    'screenscraper'
Input folder:       '/mnt/emu/roms/gba'
Game list folder:   '/mnt/emu/roms/gba'
Covers folder:      '/mnt/emu/roms/gba/media/covers'
Screenshots folder: '/mnt/emu/roms/gba/media/screenshots'
Wheels folder:      '/mnt/emu/roms/gba/media/wheels'
Marquees folder:    '/mnt/emu/roms/gba/media/marquees'
Cache folder:       'cache/gba'

DID YOU KNOW: You can enable Skyscraper's interactive mode by setting the flag '--flags interactive'. When this is set Skyscraper will ask the user to choose the best entries when using a search based scraping module.

Fetching limits for user 'xxxx', just a sec...
Setting threads to 1 as allowed for the supplied user credentials.

Reading and parsing quick id xml, please wait... Done!
Reading and parsing resource cache, please wait... Done!
Successfully parsed 1618 resources!

Looking for optional 'priorities.xml' file in cache folder... Found!
Priorities loaded successfully!

Trying to parse and load existing game list metadata... Success!

Starting scraping run on 1 files using 1 threads.
Sit back, relax and let me do the work! :)

ScreenScraper APIv2 returned invalid / empty Json
The erroneous answer was written to '/home/USER/.skyscraper/screenscraper_error.json'. Please create a bug report at 'https://github.com/muldjord/skyscraper/issues' and attach that file.
#1/1 (T1) Pass 1 ---- Game 'Incredibles' not found :( ----

#1/1, (0/1)
Elapsed time   : 00:00:01
Est. time left : 00:00:00

---- Resource gathering run completed! YAY! ----
Writing quick id xml, please wait... Done!
Writing 1618 (0 new) resources to cache, please wait... Done!

---- And here are some neat stats :) ----
Total completion time: 00:00:01

Total number of games: 1
Successfully processed games: 0
Skipped games: 1 (Filenames saved to '/home/USER/.skyscraper/skipped-gba-screenscraper.txt')
`

**Technical information**
 - Skyscraper version: 3.6.1
 - Internet connection: adsl
 - OS: Ubuntu Linux (WSL2)
 - OS Version Ubuntu 20.04 + Windows 10 19041.572

**Additional context**

The contents of the screenscraper_error.json

`Il manque des champs obligatoires dans l'url`

**Comment by muldjord** [comment]
Please see here: https://github.com/muldjord/skyscraper/issues/265

**Comment by muldjord** [comment]
Seems this is fixed on their end now.
