### ISSUE TITLE
use users real homedir instead of hardcoding to /home/pi

### ISSUE THREAD

**Issue by CreasaBE** [muldjord/skyscraper#27]
Hi,

I've tried running the script, but my home folder is not /home/pi as I don't want any default users on my boxes.
Hence the scraper fails as it cannot find /home/pi/...
I tried hacking src/attractmode.cpp and src/emulationstation.cpp and changing the hardcoded /home/pi/ to ~/
That does a bit more as the Input folder is now correctly identified, but then before starting it fails on the input folder again

```
Running Skyscraper v2.4.9 by Lars Muldjord

Platform:           'nds'
Scraper module:     'openretro'
Input folder:       '~/RetroPie/roms/nds'
Game list folder:   '~/RetroPie/roms/nds'
Covers folder:      '~/RetroPie/roms/nds/media/covers'
Screenshots folder: '~/RetroPie/roms/nds/media/screenshots'
Wheels folder:      '~/RetroPie/roms/nds/media/wheels'
Marquees folder:    '~/RetroPie/roms/nds/media/marquees'
Local db folder:    'dbs/nds'

Looking for optional 'priorities.xml' file in local db folder... Found!
Priorities loaded successfully!

Input folder '/home/xxxx/.skyscraper/~/RetroPie/roms/nds' doesn't exist or can't be seen by current user. Please check path and permissions.
```

I think it would be an improvement of the scraper used the users real home directory instead of hardcoding it.

**Comment by muldjord** [comment]
Hi, thanks for reporting this. I just released 2.4.10 in which '/home/pi' is now no longer hardcoded anywhere in Skyscraper and will instead always use current users' homedir. If you have /home/pi in some of the attractmode exports after updating, it is not related to Skyscraper but instead to your Attractmode emulator files. Do not be distracted by the commented code sections in attractmode.cpp where you will still see /home/pi. These lines are commented and only there for my own reference. Please check Attractmode documentation on how to change those in your own emulator files.

To update to 2.4.10, please follow the update procedure in the documentation here: github.com/muldjord/skyscraper

Please let me know if you have further Skyscraper related problems concerning this issue.

**Comment by CreasaBE** [comment]
sweet! I'll give it a go, thanks!

**Comment by CreasaBE** [comment]
Thank you it is working!
Thanks for the quick resolution!
Loving the tool so far (been running it the last few hours after manually hacking the source code and inputting my homedir ;) )
keep up the good work!
