### ISSUE TITLE
Some artwork will not copy from cache

### ISSUE THREAD

**Issue by Whoremoan** [muldjord/skyscraper#271]
I've recently switched from Retropie built on a PC using Ubuntu 18.04 to a fresh install with Attract Mode, also on Ubuntu 18.04
I installed Skyscraper and compiled from source from the github.
I'm using the config.ini file, which I have adjusted to how I have things set up.
When I run Skyscraper, everything runs fine. The directories assigned to each image file is how I have set them and screen scraper downloads everything as expected to the cache.
However, when I move them from the cache to the propper directories, everything copys over, apart from the wheels and covers.
No matter what I do, I cant get these to move over.
Skyscraper creates the directory, but it's empty.
I've tried changing the directory names in the AM emulator cfg file and leaving the directory blank in the AM emulator config file, but the same result.
Each time I change the directory in the AM emulator config file, they change to match in the list of assigned directorys when you run Skyscraper, so I know I am changing the correct file.
Skyscraper reports it has downloaded them in the summary when Skyscraper has finished and if I go to the cach directory, the files are there, but obviously not yet named correctly.
If I change one of the files in the wheels or covers cache directory to .jpg or .png, I can open the file and it displays correctly.

What could be causing this?

**Comment by Whoremoan** [comment]
Ahh, I think I see what is happening. It's adding those elements to the screenshot.
I guess I need to read the artwork.xml docs!!

**Comment by muldjord** [comment]
Exactly! :D Have fun
