### ISSUE TITLE
Is it possible to NOT crop the black space on screenshots ?

### ISSUE THREAD

**Issue by ghost** [muldjord/skyscraper#272]
**Describe the feature / request**
Not sure if this is already possible but is there a way to NOT crop the black space on screenshots ? I'm getting some very strange aspect ratios particularly on Amiga ones that are quite often NTSC. Or honour the aspect ratio for things like Gameboy.

I am importing my own screenshots that are at the correct aspect ratio.

**Comment by muldjord** [comment]
Not possible in the current version, but I have just added the option in the next release. It will be accessible both via command-line using the `--flags nocropblack` flag and it can also be set with the `cropBlack="false"` config.ini option in either a `[main]`, `[FRONTEND]` or `[PLATFORM]` section. It will be in the upcoming 3.6.5 release which will probably be released sometime this week.

**Comment by ghost** [comment]
Your scraper is brilliant, thanks man !

**Comment by muldjord** [comment]
Glad you like it! :) 3.6.5 out now

**Comment by ghost** [comment]
Works great, thanks!
