### ISSUE TITLE
Scraping from existing ES gamelist.xml doesn't work

### ISSUE THREAD

**Issue by c0d3h4x0r** [muldjord/skyscraper#273]
Skyscraper 3.6.5 reports it cannot find each ROM in its corresponding gamelist.xml, which is clearly not right, as most of mine are already fully populated and work fine with EmulationStation.

It appears Skyscraper may be looking for each ROM filename (sans extension) inside the `<name>` fields, which it is of course never going to find, as that field contains the cleaned-up names, not the filenames.  Skyscraper may need to instead be looking for each ROM filename inside the `<path>` fields, which is the field containing the actual filename.

**Comment by c0d3h4x0r** [comment]
Example output snippet:
```
70/478, (0/470)
Elapsed time   : 00:00:00
Est. time left : 00:00:00

#471/478 (T1) Pass 1 ---- Game 'Yoshi (U) [!]' not found :( ----


#471/478, (0/471)
Elapsed time   : 00:00:00
Est. time left : 00:00:00

#472/478 (T3) Pass 1 ---- Game 'Zen - Intergalactic Ninja (U)' not found :( ----


#472/478, (0/472)
Elapsed time   : 00:00:00
Est. time left : 00:00:00

#473/478 (T2) Pass 1 ---- Game 'Yoshi's Cookie (U) [!]' not found :( ----
```

**Comment by c0d3h4x0r** [comment]
Been perusing the code, and my initial suspicion about where this is going off the rails appears to be incorrect.

**Comment by muldjord** [comment]
Can you provide a single entry in your gamelist.xml that doesn't work please? Then I can test it.

**Comment by c0d3h4x0r** [comment]
I now suspect something is going off the rails in `QString NameTools::getCacheId()`, where it generates the cache ID from the ROM filename.  I'm using relative paths in my `gamelist.xml`, but based on my reading of the code thus far, that function will generate a cacheID using the absolute path (forced by code in `XmlReader::addEntries()`).

Here's an entry corresponding to one of the above output snippets:
```
   <game>
     <path>./Yoshi (U) [!].zip</path>
     <name>Yoshi</name>
     <desc>In Yoshi, the player is tasked with clearing monsters from the on-screen playing field. The monsters fall in from the top of the screen to build vertical stacks; the player must prevent a stack from growing too high such that it exits      the play field. In order to so, the player swaps and moves the stacks about such that falling monsters collide with identical monsters stationed atop the stacks, causing them to be removed from play.</desc>
     <image>/home/pi/.emulationstation/downloaded_images/gb/Yoshi (U) [!]-image.jpg</image>
     <releasedate>19920701T000000</releasedate>
     <developer>Game Freak</developer>
     <publisher>Nintendo</publisher>
     <genre>Puzzle</genre>
   </game>
```

(This is for ROM file `/home/pi/RetroPie/roms/gb/Yoshi (U) [!].zip`.)

**Comment by muldjord** [comment]
Thanks for the pointers, I'll look into it.

**Comment by muldjord** [comment]
Well, this is odd. I've just tested it here, with the exact same entry and the exact same filename. And it works just fine...
```
#4/4 (T2) Pass 1 ---- Game 'Yoshi (U) [!]' found! :) ----
Scraper:        esgamelist
From cache:     NO
Search match:   100 %
Compare title:  'Yoshi'
Result title:   'Yoshi' ()
Platform:       'gb' ()
Release Date:   '1992-07-01' ()
Developer:      'Game Freak' ()
Publisher:      'Nintendo' ()
Players:        '' ()
Ages:           '' ()
Tags:           'Puzzle' ()
Rating (0-1):   '' ()
Cover:          NO ()
Screenshot:     NO ()
Wheel:          NO ()
Marquee:        NO ()

Description: ()
'In Yoshi, the player is tasked with clearing monsters from the on-screen playing field. The monsters fall in from the top of the screen to build vertical stacks; the player must prevent a stack from growing too high such that it exits      the play field. In order to so, the player swaps and moves the stacks about such that falling monsters collide with identical monsters stationed atop the stacks, causing them to be removed from play.'
```
Can you post your /home/USER/.skyscraper/config.ini as well, please?
And can you also post the command you use to initialize Skyscraper, please?

**Comment by c0d3h4x0r** [comment]
`/home/pi/.syscraper/config.ini` (with passwords sanitized):

```
# --------------------------------------------------------------------
# Skyscraper by Lars Muldjord (https://github.com/muldjord/skyscraper)
# --------------------------------------------------------------------

# This is an example config file for use with Skyscraper. Use it as a template for creating
#   your own. If you copy this file to 'config.ini' it will be used per default.
#   You can always copy config.ini.example to a filename of your choice and make Skyscraper
#   use it with the '-c CONFIGFILE' command line option.

# You can have several platform sections in one config file. Further down is an example of
#   a generic platform setup. Check '--help' for more info on supported platforms.

# You can have several scraping module sections in one config file. Further down is an example
#   of a generic module setup. Check '--help' for more info on supported modules.

# Remember that most of these settings can also be set as command line options. Doing so
#   will overrule the options seen here except for the scraping module configs which
#   overrules everything else.
# Platform specific configs overrules main configs.

# Uncomment the sections and lines you wish to use:

[main]
##Setting input, gamelist or media folder here, will automatically append '/[platform]' to path.
##If you need better control, use the same variables under a [<platform>] section instead.
#inputFolder="/home/pi/RetroPie/roms"
#excludeFiles="*[BIOS]*"
#includeFiles="Super*"
#gameListFolder="/home/pi/RetroPie/roms"
#gameListBackup="false"
#mediaFolder="/home/pi/RetroPie/roms"
#cacheFolder="/home/pi/.skyscraper/cache"
#cacheResize="false"
#nameTemplate="%t [%f], %P player(s)"
#jpgQuality="95"
#cacheCovers="true"
#cacheScreenshots="true"
#cacheWheels="true"
#cacheMarquees="true"
#importFolder="/home/pi/.skyscraper/import"
#unpack="false"
#frontend="emulationstation"
#emulator=""
#launch=""
#videos="false"
#videoSizeLimit="42"
#videoConvertCommand="ffmpeg -i %i -y -pix_fmt yuv420p -t 00:00:10 -c:v libx264 -crf 23 -c:a aac -b:a 64k -vf scale=640:480:force_original_aspect_ratio=decrease,pad=640:480:(ow-iw)/2:(oh-ih)/2,setsar=1 %o"
#videoConvertExtension="mp4"
#symlink="false"
#brackets="true"
#maxLength="10000"
#threads="2"
#pretend="false"
#unattend="false"
#unattendSkip="false"
#interactive="false"
#forceFilename="false"
#verbosity="1"
#skipped="false"
#maxFails="30"
#lang="en"
#region="wor"
#langPrios="en,de,es"
#regionPrios="eu,us,ss,uk,wor,jp"
#minMatch="0"
#artworkXml="artwork.xml"
relativePaths="true"
#addExtensions="*.zst"
#hints="false"
#subdirs="true"
#spaceCheck="true"
#scummIni="/full/path/to/scummvm.ini"

#[<PLATFORM, eg 'amiga'>]
#inputFolder="/home/pi/RetroPie/roms/amiga"
#excludeFiles="*[BIOS]*"
#includeFiles="Super*"
#gameListFolder="/home/pi/RetroPie/roms/amiga"
#mediaFolder="/home/pi/RetroPie/roms/amiga/media"
#cacheFolder="/home/pi/.skyscraper/cache/amiga"
#cacheResize="false"
#nameTemplate="%t [%f], %P player(s)"
#jpgQuality="95"
#cacheCovers="true"
#cacheScreenshots="true"
#cacheWheels="true"
#cacheMarquees="true"
#importFolder="/home/pi/.skyscraper/import/amiga"
#unpack="false"
#emulator=""
#launch=""
#videos="false"
#videoSizeLimit="42"
#symlink="false"
#brackets="true"
#lang="en"
#region="wor"
#langPrios="en,de,es"
#regionPrios="eu,us,ss,uk,wor,jp"
#minMatch="0"
#maxLength="10000"
#threads="2"
#startAt="filename"
#endAt="filename"
#pretend="false"
#unattend="false"
#unattendSkip="false"
#interactive="false"
#forceFilename="false"
#verbosity="1"
#skipped="false"
#artworkXml="artwork.xml"
#relativePaths="false"
#extensions="*.zip *.uae *.adf"
#addExtensions="*.zst *.rom"
#subdirs="true"

#[<FRONTEND, eg 'pegasus'>]
#excludeFiles="*[BIOS]*"
#includeFiles="Super*"
#artworkXml="artwork.xml"
#emulator=""
#launch=""
#gameListFolder="/home/pi/RetroPie/roms/amiga"
#gameListBackup="false"
#mediaFolder="/home/pi/RetroPie/roms/amiga/media"
#skipped="false"
#brackets="true"
#videos="false"
#symlink="false"
#startAt="filename"
#endAt="filename"
#unattend="false"
#unattendSkip="false"
#forceFilename="false"
#verbosity="1"
#maxLength="10000"

[screenscraper]
userCreds="keithfkelly:********"
#threads="4"
#minMatch="0"
#maxLength="10000"
#interactive="false"
#cacheResize="false"
#jpgQuality="95"
#cacheCovers="true"
#cacheScreenshots="true"
#cacheWheels="true"
#cacheMarquees="true"
#videos="false"
#videoSizeLimit="42"
#videoConvertCommand="ffmpeg -i %i -y -pix_fmt yuv420p -t 00:00:10 -c:v libx264 -crf 23 -c:a aac -b:a 64k -vf scale=640:480:force_original_aspect_ratio=decrease,pad=640:480:(ow-iw)/2:(oh-ih)/2,setsar=1 %o"
#videoConvertExtension="mp4"
##The following option is only applicable to 'screenscraper'
#videoPreferNormalized="true"

[thegamesdb]
userCreds="keith.f.kelly:********"

[openretro]
userCreds="c0d3h4x0r:********"
```

**Comment by c0d3h4x0r** [comment]
I'm using the `retropie_setup.sh` configuration menus to launch skyscraper, so it is generating the command.  Do you know how I can see the command it constructed?  Is it logged anywhere?

**Comment by muldjord** [comment]
I think it is logged somewhere but I can't remember where. It is also shown for a couple of seconds just after the scraping has finished.

**Comment by muldjord** [comment]
I've tried with your config as well, and it still works perfectly for me. Could you try running it from terminal with the following:
```
Skyscraper -p gb -s esgamelist --refresh
```
If it can't find the Skyscraper executable, you need to use the full path to where RetroPie has installed it. I can't remember where that is either. But somewhere in /opt/retropie

**Comment by c0d3h4x0r** [comment]
Okay, here's the command line that `retropie_setup.sh` is generating:

```
/opt/retropie/supplementary/skyscraper/Skyscraper -p gb -g /home/pi/.emulationstation/gamelists/gb -o /home/pi/.emulationstation/downloaded_media/gb -s esgamelist --refresh --flags unattend,skipped,onlymissing
```

**Comment by muldjord** [comment]
Works fine for me with that command, but I see something that might break it.

Is your gamelist.xml located here?
```
/home/pi/RetroPie/roms/gb/gamelist.xml
```
And is your rom located here?
```
/home/pi/RetroPie/roms/gb/Yoshi (U) [!].zip
```
I think they need to be. The relative path is pointing to the input folder. But if your gamelist.xml is located at that other location, it of course won't find the file.

**Comment by c0d3h4x0r** [comment]
No, I do not keep my gamelists underneath my `roms` folder.  I keep them in the RetroPie-default location of `/home/pi/.emulationstation/gamelist/`.

**Comment by muldjord** [comment]
Then that is probably the reason. Your gamelist is pointing to a relative path/file that doesn't exist since your rom is not located at /.emulationstation/gamelist/

**Comment by c0d3h4x0r** [comment]
That is the correct and default way that RetroPie sets things up.  It sounds like you are assuming users will be using some non-default RetroPie configuration.  And EmulationStation works fine with it (both reading the gamelists, and using its built-in scraper to populate them).

**Comment by muldjord** [comment]
Might be, but you can see what I mean, right?

**Comment by c0d3h4x0r** [comment]
Sure.  But this really ought to work out of the box with the default RetroPie settings.

**Comment by muldjord** [comment]
I don't think I've said I wouldn't change it, have I? We're merely finding the culprit here.

**Comment by c0d3h4x0r** [comment]
Sorry, it sounded like you were arguing for me to change my configuration in order to get this to work.  I don't want to totally change how I've got things set up, as I've already sunk hundreds of hours into it.

**Comment by muldjord** [comment]
I was just trying to get you to test if that was in fact the reason. I'll look into it. Thanks for testing and reporting it.

**Comment by c0d3h4x0r** [comment]
Okay... can I test it by temporarily establishing a folder symlink?  I'm happy to help you validate your hypothesis.

**Comment by muldjord** [comment]
You could try simply copying the `gamelist.xml` into the `roms/gb/` folder (or symlinking it, should also work). That should make it work I think.

**Comment by muldjord** [comment]
Ok, I'm sure that's it now (just created your exact setup), and the fix is simple. `esgamelist.cpp`, change line 35 to:
```
baseUrl = config->gameListFolder + (config->gameListFolder.right(1) != "/"?"/":"");
```
That should fix it. I will add it to 3.6.6. I will release it when I've done a bit of testing, maybe tonight or tomorrow.

**Comment by muldjord** [comment]
I went ahead and tested both locations for the `gamelist.xml` and it works as expected now. 3.6.6 released. You can update through the RetroPie script (update from source) and it should work now without changing any config on your end.

**Comment by c0d3h4x0r** [comment]
Oh awesome!  I'll pull it down and give it a try and verify.

**Comment by c0d3h4x0r** [comment]
It works!  That was a great find and fix.  Thank you!!

**Comment by muldjord** [comment]
No problem, and thank you for helping debug it!
