### ISSUE TITLE
Add *.rvz support to Wii and Gamecube

### ISSUE THREAD

**Issue by tcamargo** [muldjord/skyscraper#274]
**Describe the feature / request**
Add *.rvz support to Wii and Gamecube

**Additional context**
RVZ is a new high compression storage format designed for Dolphin.
https://dolphin-emu.org/blog/2020/07/05/dolphin-progress-report-may-and-june-2020/

**Comment by tcamargo** [comment]
Btw, rvz file scrape successfully if I tell Skyscraper to consider *.rvz.

> [wii]
> extensions="*.rvz"

**Comment by muldjord** [comment]
Sure, I'll add it. Thanks for reporting it.
