### ISSUE TITLE
Is regionPrios supposed to override region name in brackets in filename?

### ISSUE THREAD

**Issue by laurastephsmith** [muldjord/skyscraper#275]
I have Europe region ROMs, but I'd like to scrape the US region artwork from Screenscraper, because in the UK the NES artwork was more like the US verions than the Europe versions. I've got
```
regionPrios="uk,wor,us,eu,jp,ss"
```
set in config.ini. Is that supposed to override the region in the ROM filename? It doesn't appear to be. For example, a ROM called "Tennis (Europe).nes" is still giving the European artwork instead of the US artwork.

Thank you!

**Comment by muldjord** [comment]
If the filename has `europe` or `(e)` in it, it will always prepend `eu` to the region priorities list with one exception: If you have set a forced region with `region="us"` it will adhere to that instead. And it will append the `regionPrios="1,2,3"` to the list *after* the one set with `region="REGION"`. And if `regionPrios="1,2,3"` *isn't* set, it will append the internal region priorities list instead. But still keep the one set with `regio="REGION"` as the first priority.

It's a little messy, I know, but it should work if you simply set `region="us"` in your `config.ini`.

**Comment by laurastephsmith** [comment]
Thank you, that's worked perfectly! And I'll take "working" over "not messy" any day ;-). And thanks for an amazing bit of software, by the way!

**Comment by muldjord** [comment]
You are most welcome, glad it worked. :) Have fun!

**Comment by laurastephsmith** [comment]
Me again... :) I've run into a situation where I want a different region priority order for different games within the same platform. Can you think of a sensible way to work around this? I've been having a think but can't come up with anything! Manually editing the files after scraping is fine, but every time I re-scrape it will overwrite it... Thanks for your help!

**Comment by muldjord** [comment]
You could look into putting it in the filenames. Skyscraper should use that as first priority as long as you haven't configured it manually with `region="REGION"`. You can see what it looks for [here](https://github.com/muldjord/skyscraper/blob/90a200438f0214fd8c78d89093d3373438055720/src/abstractscraper.cpp#L529). I can't remember if ScreenScraper has them somehow hardcoded though, it's been a long time since I've messed with that code.

But you can try it.

**Comment by laurastephsmith** [comment]
I think that's exactly the idea I was looking for, thank you! I'll try it out tomorrow. You see, in the UK in the 90s, Teenage Mutant Ninja Turtles were just far too edgy, so in my childhood we had Teenage Mutant _Hero_ Turtles :).
