### ISSUE TITLE
Skyscraper breaks Runcommand launch menu art

### ISSUE THREAD

**Issue by laurastephsmith** [muldjord/skyscraper#276]
Runcommand expects launch menu art to be saved as:
/opt/retropie/configs/all/emulationstation/downloaded_images/ROM_NAME-image.png (or .jpg) (this is the location used by RetroPie's built-in scraper)
or
~/RetroPie/roms/nes/images/SYSTEM_NAME/ROM_NAME-launching.png (or .jpg) (this is the location [described by the RetroPie docs)](https://retropie.org.uk/docs/Runcommand/#adding-custom-launching-images).

**To Reproduce**
- Ensure any artwork downloaded by the built-in scraper has been removed (by deleting the contents of /opt/retropie/configs/all/emulationstation/downloaded_images).
- Use the RetroPie setup script to access the Runcommand script and to enable launch menu art (option C, option 831, option 2).
- Use Skyscraper to gather resources and gemerate game lists as usual.
- Launch a game that Skyscraper has scraped, and observe the black screen where the Runmenu launch art should be.

**To Manually Overcome the Issue**
- Copy the images from /opt/retropie/configs/all/emulationstation/downloaded_media/SYSTEM_NAME/covers into /opt/retropie/configs/all/emulationstation/downloaded_images/ or ~/RetroPie/roms/nes/images/SYSTEM_NAME/
- Rename the copied files to CURRENT_NAME-image.EXT or CURRENT_NAME-launching.EXT (depending on which location you put them).
- Launch a game and see the Runcommand launch menu art appear.

**Special circumstances**
Runcommand launch menu art is disabled by default, so the issue is only relevant if the launch menu art has been enabled by the user.

**Technical information**
 - Skyscraper version: 
 - Internet connection: ADSL
 - OS: RetroPie
 - OS Version 4.7.1
 - System: rpi4 (armv7l) running on Raspberry Pi OS Buster
 - EmulationStation v2.9.6RP

**Additional context**
- I think it's reasonable to use the "cover" art as the runcommand artwork, without giving options for other cached resources. It's what the built-in scraper does.
- I don't know whether to recommend that Skyscraper should copy the cover art to /opt/retropie/configs/all/emulationstation/downloaded_images/ROM_NAME-image.png or ~/RetroPie/roms/nes/images/SYSTEM_NAME/ROM_NAME-launching.png. The first would be consistent with the built-in scraper, but the second would be consistent with the documentation. The advantage of doing the same as the built-in scraper is that there won't be any issues with duplicated files if the user switches between the built-in scraper and Skyscraper.

**Comment by muldjord** [comment]
I don't know how the RetroPie fork of EmulationStation's internal scraper works, but Skyscraper is only an EmulationStation game list exporter, not a runcommand exporter. runcommand is just *one* way to launch games, which RetroPie uses. Skyscraper is closely related to RetroPie, but has many users outside that ecosystem. So it won't be tied up to runcommand like you request.

Instead I suggest creating a simple script which symlinks the exported media to the correct folder. :)

**Comment by laurastephsmith** [comment]
I don't think the internal scraper has anything to do with Runcommand - it just sticks the media it's creating anyway in the place where Runcommand expects it. But I've only been using RetroPie and EmulationStation for a week, so I might be wrong! :) Anyway, yes, a script to do it is where I'll end up - thank anyway
