### ISSUE TITLE
Systems missing from the Vacuum list

### ISSUE THREAD

**Issue by gordonfreemanhr** [muldjord/skyscraper#277]
I have 9 systems on my Pi Zero, all previously succesfully scraped with Skyscraper. I deleted bunch of roms from each, so my goal is to:

a. vacuum the systems
b. regenerate the gamelists

The problem is, most of the systems are for some reason missing from the Vacuum list. Still, they are present in the Generate Gamelist menu, however at this point generating a gamelist is pointless.

I tried scraping the systems again with the „only missing” flag. No changes.

I’m aware I can probably rescrape all the systems, but I’d rather avoid that, having already the full cache down.

What do I do?

**Comment by muldjord** [comment]
I assume you mean to do this from the RetroPie script? I don't use the script myself so I don't know what the issue might be there.

But from command-line you can do it with:
```
Skyscraper -p PLATFORM --cache vacuum
```

Please read [this](https://github.com/muldjord/skyscraper/blob/master/docs/CLIHELP.md) for detailed information on how to use the Skyscraper command-line options.

**Comment by gordonfreemanhr** [comment]
Yes, for some reason I forgot to mention it. The command line works. Thanks!
