### ISSUE TITLE
3do chd support.

### ISSUE THREAD

**Issue by ghost** [muldjord/skyscraper#278]
**Describe the feature / request**
Can .chd support be added for 3DO.

**Additional context**
3DO scrapes fine if I change my files to .cue

**Comment by muldjord** [comment]
Sure, it will be in the next release. In the meantime, you can add it manually with `addExtensions="*.chd"` in `/home/USER/.skyscraper/config.ini` like so:
```
[3do]
addExtensions="*.chd"
```
