### ISSUE TITLE
"Removed 'extensions' when generating Pegasus game list, as it isn't required" fails

### ISSUE THREAD

**Issue by jaildesigner** [muldjord/skyscraper#279]
Pegasus won't parse metadata.txt if 'extensions' is missing, it says "game does not belong to any collections, ignored"

**Comment by muldjord** [comment]
So it fails to load it at all? Or just those games that don't have an entry? `extensions` shouldn't be needed as long as the games are listed separately in the list. It was removed for that very reason.

**Comment by muldjord** [comment]
I found the discussion on this. It's here: https://github.com/muldjord/skyscraper/issues/247#issuecomment-666897743

**Comment by muldjord** [comment]
Due to the differing opinions on this I can't really make a call to put it back in by default. But you can always add it manually, since it's just that one line. And it should preserve it for re-generations once you've added it once manually.

**Comment by jaildesigner** [comment]
Ok, no problem. I just wanted to inform. I've made a bashscript to solve my needs. Thanks for the hard work! :)
