### ISSUE TITLE
Curl command - Clean Install - Permission Denied line 7

### ISSUE THREAD

**Issue by 2play** [muldjord/skyscraper#28]
I tried to run clean install. 
curl command give below:

sudo curl https://raw.githubusercontent.com/muldjord/skyscraper/master/update_skyscraper.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1074  100  1074    0     0   4142      0 --:--:-- --:--:-- --:--:--  4146
bash: line 7: VERSION: Permission denied
bash: line 9: VERSION: No such file or directory
--- Fetching Skyscraper v.2.4.10 ---
--2018-06-14 15:17:42--  https://github.com/muldjord/skyscraper/archive/2.4.10.tar.gz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/muldjord/skyscraper/tar.gz/2.4.10 [following]
--2018-06-14 15:17:43--  https://codeload.github.com/muldjord/skyscraper/tar.gz/2.4.10
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1832434 (1.7M) [application/x-gzip]
2.4.10.tar.gz: Permission denied

Cannot write to ‘2.4.10.tar.gz’ (Permission denied).

**Comment by muldjord** [comment]
Thank you for the detailed output, it helps me understand the issue. First of all, you are running the command with sudo, which is not what you are supposed to do. This will mess up your permissions, which is exactly what has happened. You need to run the following commands, then start over with the installation instructions. Until you do so it won't work.
$ cd
$ sudo rm -Rf skysource
This will completely remove the skysource folder which has broken permissions. Then follow the installation instructions EXACTLY as they are described. Don't use sudo unless you are told to do so. As I said, it will mess up your permissions which causes problems like this.

**Comment by 2play** [comment]
tx Lars! Ill try it.

**Comment by 2play** [comment]
All good Lars! Thank you!
Ive got also a little gift for your followers. Ill post it in the features :-)
You can close this one.
