### ISSUE TITLE
request for screenscraper system ids and extenstions (openbor and model3)

### ISSUE THREAD

**Issue by hahnmt** [muldjord/skyscraper#280]
request to add systems and extensions for the following

openbor
*.pak
screenscraper system id 214

sega model 3
*.zip
screenscraper system id 55

I have made a fork and test compile of each.  It was simple chang to add the system ids, aliases and extensions.  Requesting these be added upstream to avoid a PR.

**Comment by muldjord** [comment]
Thanks. I've added OpenBOR. It makes sense as it is somewhat supported by RetroPie already.
I won't add Model 3. It's a sub-arcade platform which is a road I don't wanna walk down (there are many, many of these). It's already supported through the 'arcade' platform and other mame-related platforms.

'openbor' will be in the next release.
