### ISSUE TITLE
ScreenScraper not scraping Atari ST

### ISSUE THREAD

**Issue by gordonfreemanhr** [muldjord/skyscraper#284]
**Describe the bug**
Skyscraper not scraping from Screenscraper the data for the Atari ST roms. The error message: APIv2 returned invalid / empty Json

**To Reproduce**
Latest Skyscraper version (as for Feb 9th 2021) running on 4.7.1 Retropie. Atari ST roms running from an external USB, all in .zip format.

**Terminal output**
APIv2 returned invalid / empty Json

**Technical information**
 - Skyscraper version: 3.6.7
 - Internet connection: wifi
 - OS: Retropie
 - OS Version 4.7.1

**Additional context**
I have a very similar issue to this one:
https://github.com/muldjord/skyscraper/issues/158
however regarding Atari ST.

**Comment by muldjord** [comment]
Most likely a ScreenScraper server issue (this happens quite a lot as the similar issue also shows). Please try again in a few days and report back if it persists.

**Comment by muldjord** [comment]
Just tested it and their servers are indeed having issues. Nothing I can do on my end, you'll just have to wait until they fix their service. Closing.

**Comment by gordonfreemanhr** [comment]
Ok, thanks!
