### ISSUE TITLE
Retropiemenu Skyscraper Script (install & update) by 2Play!

### ISSUE THREAD

**Issue by 2play** [muldjord/skyscraper#29]
Please find a retropiemenu script for installing and updaring Skyscraper!

Steps:
- Unzip .sh file
- Copy to your Retropie retropiemenu directory
- Check the permissions and make executable if needed by `sudo chmod 755 skyscraper.sh`
- Start or restart your ES and you should see the new entry.
Concept-Creation by me, Skyscraper by Lars of course!
[skyscraper.zip](https://github.com/muldjord/skyscraper/files/2103230/skyscraper.zip)

**Comment by muldjord** [comment]
Cool, thank you for making this. If it is well-tested, you should consider submitting it to the retropie menu project.

**Comment by 2play** [comment]
I ve tested it multiple times.
So here it is:  
https://github.com/2play/Skyscraper
Enjoy!
