### ISSUE TITLE
Only copies 2 media assets per type

### ISSUE THREAD

**Issue by SirBossJam** [muldjord/skyscraper#294]
**Describe the bug**
When running the scrape and list generation process, the end result is always the first 2 media assets only being copied to the output directories

**To Reproduce**
Here are the commands I run to reproduce the issue.
```
Skyscraper -p snes -i /home/user/Pegasus/pegasus/config/metafiles/snes/roms -s screenscraper -m 100 --flags unattend,skipped,videos,nocropblack,noresize,nomarquees -u hidden:hidden
Skyscraper -p snes -i /home/user/Pegasus/pegasus/config/metafiles/snes/roms -g /home/user/Pegasus/pegasus/config/metafiles/ -o /home/user/Pegasus/pegasus/config/metafiles/snes -f pegasus -m 100 --flags unattend,skipped,nobrackets,videos --cache report:missing=all
```

**Terminal output**
The terminal indicates that everything runs successfully with thousands of assets being scraped and cached. If you need anything specific, just let me know.

**Technical information**
 - Skyscraper version: 3.6.7
 - Internet connection: Cable 300 UP/ 20 Down
 - OS: Manjaro/Arch Linux
 - OS Version: Manjaro 20.2.1 Nibia

**Additional context**
All the cached assets are present in ".skyscraper/cache/snes", but they are not being copied to my output folder, except the first 2.

I have completely removed skyscraper (and the .config and cache directories), reinstalled and ran again from a fresh start, but see the same results.

**Comment by muldjord** [comment]
I'm not sure I understand you correctly. Skyscraper only exports screenshot and marquee per default since it is optimized for the RetroPie Emulationstation look. If this is what you are referring to, then you need to configure your artwork as documented [here](https://github.com/muldjord/skyscraper/blob/master/docs/ARTWORK.md).

**Comment by SirBossJam** [comment]
Sorry if I was not clear. What I mean is, instead of it exporting all the media assets, it just stops after the first 2. So, for example instead of all covers being saved to my media output folder, I get the first 2 only. See screenshot. Also, here's my artwork.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- This example simply exports the raw unedited versions of each artwork type coming directly from the scraping source -->
<artwork>
  <output type="cover"/>
  <output type="screenshot"/>
  <output type="wheel"/>
  <output type="marquee"/>
</artwork>
```
![Screenshot_2021-03-12_10-43-42](https://user-images.githubusercontent.com/66538223/110971389-ba3c4100-8352-11eb-984e-07266ebc990c.png)

**Comment by muldjord** [comment]
Why do you have `--cache report:missing=all` in the second command? That will create a report and exit. Please read [this](https://github.com/muldjord/skyscraper/blob/master/docs/CLIHELP.md) to better understand the settings you are using.

So I'll go out on a limb and conclude that this is not a bug, but a misconfiguration on your end. I would ask you to please go to the RetroPie forums and ask the question there. There's plenty of users on there who can help you and I might answer myself there as well. Thanks.

**Comment by SirBossJam** [comment]
Well, I feel dumb. I guess I expected it to do both. It's working now without the --cache report option. Thanks for you help, and sorry for the hassle.

Keep up the good work. This is an amazing tool!

**Comment by SirBossJam** [comment]
Well, I feel dumb. I guess I expected it to do both. It's working now without the --cache report option. Thanks for you help, and sorry for the hassle.

Keep up the good work. This is an amazing tool!
