### ISSUE TITLE
no login with screenscraper module

### ISSUE THREAD

**Issue by johnvk-dev** [muldjord/skyscraper#297]
Using version 3.6.9 on debian based distro.

When trying to scrape with the screenscraper module i get this error:

`Fetching limits for user 'xxxx', just a sec...`
`ScreenScraper login error! Please verify that you've entered your credentials correctly in '/home/USER/.skyscraper/config.ini'. It needs to look EXACTLY like this, but with your USER and PASS:`
`[screenscraper]`
`userCreds="USER:PASS"`
`Continuing with unregistered user, forcing 1 thread...`

The username/pass works when login into the https://www.screenscraper.fr/ site.

Both using the config.ini entry:

`Skyscraper -p snes -s screenscraper -u user:pass`

and using the commandline:

`[screenscraper]
userCreds="user:pass"`

result in this error.

**Comment by muldjord** [comment]
It works fine, just tested it. Have you had it working at some point? Maybe it's some special characters it doesn't like, that's my best guess.

Btw, you switched the descriptions of your output and it's missing newlines. Can you fix this, it's hard to debug your output when it's incorrect from the get-go. Thanks.

**Comment by johnvk-dev** [comment]
I'm very sorry to report that I made a typo in the initial password on the site and it logged me in after account creation so I did not notice it. Everything is good now! Apologies.
