### ISSUE TITLE
Terminal GUI

### ISSUE THREAD

**Issue by fOmey** [muldjord/skyscraper#3]
Title is self explanatory,  would be great for a terminal GUI similar to sselphs scraper.

**Comment by fOmey** [comment]
I guess this would be more on the retropie setup script side of the business...

**Comment by muldjord** [comment]
I am planning to implement an option that will start Skyscraper in "create-a-script" mode (probably started just by typing 'Skyscraper' with no arguments), which basically asks you a bunch of questions which turns into a script it will then execute for you. This will make it a lot easier for newbies to use. It's of high priority, but I am currentl focused on other projects, so it won't be until sometime in 2018. On that note, merry christmas and happy new year!

**Comment by muldjord** [comment]
2.1.0 released with new 'simple mode' that acts as a "gui". Try it out. :)
