### ISSUE TITLE
Unable to set relative paths to media files in gamelist.xml

### ISSUE THREAD

**Issue by jimnarey** [muldjord/skyscraper#300]
**Describe the bug**

Using Skyscraper 3.6.10 I am unable to create a gamelist.xml with relative paths to media files if the root media folder is outside the root rom folder. This happens using either the config.ini media root setting or using --flags relative on the command line. These options still set relative paths to rom files, as expected. The same behaviour happens with at least the psx and snes platforms. 

**To Reproduce**

'psx' and 'snes' folders are in the rom root, set in config.ini under [main].
Root media folder is set on the same level as the root roms folder, within the same parent folder, in config.ini.

1. Download assets:

Skyscraper -p psx -s screenscraper 
Skyscraper -p snes -s screenscraper

2. Create gamelists:

Skyscraper -p psx --flags relative
Skyscraper -p snes --flags relative

OR

...with relativePaths="true" in config.ini

Skyscraper -p psx
Skyscraper -p snes

OR
...with relativePaths not set in config.ini

Skyscraper -p psx
Skyscraper -p snes

3. In none of these cases are the paths to any media files in the resulting gamelist.xml relative. In the first and second cases the paths to rom files are relative.

4. I have tried setting/not setting -o in the CLI; setting/not-setting -f emulationstation; setting the frontend in confiig.ini; setting a relative path to my desired root media folder in the CLI; doing the same in config.ini. The result unchanged by any.

**Special circumstances**
None

**Terminal output**
All terminal output is as expected.

**Technical information**
 - Skyscraper version: 3.6.10
 - Internet connection: Fibre ADSL
 - OS: Ubuntu
 - OS Version 20.04.02

**Additional context**
I am using Skyscraper via SSH from another Ubuntu 20 machine.

**Comment by muldjord** [comment]
This has been discussed before and the essence of it is this (it's on purpose btw): Media folder is only relative if `-o` (media folder) is below the input folder. You could potentially set it to `/tmp/media` in which case the relative path would end up being `../../../tmp/media`. That's not a useful relative path, and makes much more sense to have as absolute path.

If the media is placed below the inputFolder path, it will be relative.
