### ISSUE TITLE
Add platform support for Channel F, PC Engine CD / Turbo Grafx CD, and Atari Jaguar CD

### ISSUE THREAD

**Issue by XenuIsWatching** [muldjord/skyscraper#302]
# Describe the feature / request

Add Support for the Channel F, PC Engine CD / Turbo Grafx CD, Atari Jaguar CD, and the Nintendo 64DD.

## Channel F

Channel F has been added to retropie with the emulator `lr-freechaf`, this has the platform name of `channelf`

##  Atari Jaguar CD

Although you can throw the atari jaguar cd image files into the `atarijaguar` folder. It can't scrape them as this has a seperate id through screenscraper fr. Although, I find it odd that emulation station does have a platformid for this for it's built-in scraper...
https://github.com/RetroPie/EmulationStation/blob/e6f5880da0b2dbc042557a6c3b3a6fd6adbcd4bc/es-app/src/PlatformId.cpp#L22

## PC Engine CD / Turbo Grafx CD

*same reasoning as above*

# Additional context

## Appendix

| Skyscraper Platform           | Platform Name                  | File Extensions              | Screenscraper fr ID |
| ----------------------------- | ------------------------------ | ----------------------------- | ------------------- |
| Atari Jaguar CD               | atarijaguarcd                  | \*.cue (\*.chd?)              | 171                 |
| PC Engine CD / Turbo Grafx CD | pcenginecd | \*.cue, \*.chd, \*.ccd        | 114                 |
| Channel F                     | channelf                       | \*.bin, \*.rom, \*.zip, \*.7z | 80                  |

**Comment by muldjord** [comment]
Thank you for providing detailed info, it makes it a lot easier for me to add them (not to mention motivated to do so). All 3 platforms added. Will be in 3.6.11.

EDIT: 3.6.11 out now.

**Comment by XenuIsWatching** [comment]
Test and Verified building from source!!! Thanks for the very prompt enhancement ~~~~!!!!
