### ISSUE TITLE
Purge All Platforms cache

### ISSUE THREAD

**Issue by 2play** [muldjord/skyscraper#304]
hi @muldjord 
Would it be easy to add a purge all cache instead each platform?
Something like ` Skyscraper --cache purge:all`

**Comment by muldjord** [comment]
Hi, you can just remove the `/home/USER/.skyscraper/cache` folder. That is what Skyscraper would do if I implemented this. Is that too cumbersome, or is there some other reason you want this implemented? I'm not against it per se, but it's time I need to spend and I'm not developing new Skyscraper features right now.

**Comment by 2play** [comment]
hi @muldjord 
No very easy. I wanted to verify with you!
Thank you!
