### ISSUE TITLE
Cannot make from source Ubuntu 21.04 Gnome40 debian

### ISSUE THREAD

**Issue by hhtien1408** [muldjord/skyscraper#305]
I can install QT5 as guide well but I cannot make install skyscraper with widget bash (url seems oudated). Even I update url for correct address for update script

error
line 7: syntax error near unexpected token `newline' <!DOCTYPE html> 

If I install skyscraper from source inside retropie-setup, it will tell cannot find qt5-default 7zip full even qt5 is fully installed.
Hope you could help resolve! Thanks!

**Comment by muldjord** [comment]
This is something on your end. You write that you installed qt5 correctly. I don't think that's the case. Please read the note about Ubuntu 21.04 in the readme.

**Comment by hhtien1408** [comment]
> This is something on your end. You write that you installed qt5 correctly. I don't think that's the case. Please read the note about Ubuntu 21.04 in the readme.

I followed your guide strictly especially for Ununtu 21.04 but if I run retropie script to select opt packages to install from source. It tells no dependencies of qt5-default. So strange. 

Morever, if use wget -o as your guide, it give error as I mentioned line 7: syntax error near unexpected token `newline' <!DOCTYPE html> . Could you check this command line one more? I am very interested in your skyscraper.

**Comment by muldjord** [comment]
You need to run this:
```
sudo apt install build-essential qtbase5-dev qt5-qmake qtbase5-dev-tools
```
Then [follow the installation instructions](https://github.com/muldjord/skyscraper#download-compile-and-install). Do not try installing it from the RetroPie script. It won't work for Ubuntu 21.04 right now.

**Comment by muldjord** [comment]
The `wget` command works just fine on my Ubuntu 21.04. I have no idea why it won't work on your end.

**Comment by hhtien1408** [comment]
> The `wget` command works just fine on my Ubuntu 21.04. I have no idea why it won't work on your end.

sudo apt install build-essential qtbase5-dev qt5-qmake qtbase5-dev-tools
—> OK (no issue)

The url in wget is right? I just get stuck in wget bash. 

$ cd
$ mkdir skysource
$ cd skysource
$ wget -q -O - https://raw.githubusercontent.com/muldjord/skyscraper/master/update_skyscraper.sh | bash

  
 So sad!

**Comment by muldjord** [comment]
It must be something on your local system. Maybe it has configured newlines in a weird way, I can't know.

You can download the latest version though and just unzip it and compile it:
```
$ cd
$ wget https://github.com/muldjord/skyscraper/archive/refs/tags/3.6.11.zip
$ unzip 3.6.11.zip
$ cd skyscraper-3.6.11
$ qmake
$ make
$ sudo make install
```
This will install Skyscraper, but you probably won't be able to update it using the update script either, so if you want to update it later on, you need to do in the same way as above.

**Comment by hhtien1408** [comment]
> It must be something on your local system. Maybe it has configured newlines in a weird way, I can't know.
> 
> You can download the latest version though and just unzip it and compile it:
> 
> ```
> $ cd
> $ wget https://github.com/muldjord/skyscraper/archive/refs/tags/3.6.11.zip
> $ unzip 3.6.11.zip
> $ cd skyscraper-3.6.11
> $ qmake
> $ make
> $ sudo make install
> ```
> 
> This will install Skyscraper, but you probably won't be able to update it using the update script either.

Wow, I used to follow all steps above and successfully install from source.

After command sudo make install, I get /user/local/etc/skyscraper folder. But I see no script in this folder. How to use script?
Please check the link for image
[https://ibb.co/2M1QJQ9](url)
How to use script integrated  within retropie as bezel project?

**Comment by muldjord** [comment]
If you want to use the RetroPie script, you need to edit it to not try to install `qt5-default` and install the other packages as per the Ubuntu 21.04 note instead. But that's kind of outside the scope of the support I want to go into.

**Comment by hhtien1408** [comment]
> If you want to use the RetroPie script, you need to edit it to not try to install `qt5-default` and install the other packages as per the Ubuntu 21.04 note instead. But that's kind of outside the scop of the support I want to go into.

I appreciate your support. But I successfully do all your command lines til “sudo make install”.
After that I get folder skyscraper as attached picture, how to use it?
Could you help explain me? Thanks!

**Comment by muldjord** [comment]
No, I am not going to explain how to use Skyscraper. This is for bug reports and feature requests. If you need support on how to use Skyscraper, first read the documentation. Then, if you still have questions, you should ask them on the RetroPie forums.

**Comment by hhtien1408** [comment]
> No, I am not going to explain how to use Skyscraper. This is for bug reports and feature requests. If you need support on how to use Skyscraper, first read the documentation. Then, if you still have questions, you should ask them on the RetroPie forums.

I mean that I install all as you guided. Sudo make install ok. I just asked your support to tell me which file in folder skyscraper to execute for use?

**Comment by muldjord** [comment]
None of them. The files in `/home/USER/.skyscraper` are resource files. It is all documented. The executable is installed in `/usr/local/bin/Skyscraper`. Read the [use case](https://github.com/muldjord/skyscraper/blob/master/docs/USECASE.md). Don't run it without command line parameters. This will start Skyscraper in Simple Mode which is currently broken.

**Comment by hhtien1408** [comment]
> None of them. The files in `/home/USER/.skyscraper` are resource files. It is all documented. The executable is installed in `/usr/local/bin/Skyscraper`. Read the [use case](https://github.com/muldjord/skyscraper/blob/master/docs/USECASE.md). Don't run it without command line parameters. This will start Skyscraper in Simple Mode which is currently broken.

That seems my installation has not completed. I just got this. The last line in picture: Artwork, resources…
https://ibb.co/pb3BvqQ

**Comment by muldjord** [comment]
Yes it has. I am going to close this now. Read the use case, it will explain what you need to use it.

**Comment by hhtien1408** [comment]
> None of them. The files in `/home/USER/.skyscraper` are resource files. It is all documented. The executable is installed in `/usr/local/bin/Skyscraper`. Read the [use case](https://github.com/muldjord/skyscraper/blob/master/docs/USECASE.md). Don't run it without command line parameters. This will start Skyscraper in Simple Mode which is currently broken.

I made it working well. Thanks for your support!
