### ISSUE TITLE
Vacuum Chosen Platform Is Broken

### ISSUE THREAD

**Issue by Rocknroller1985** [muldjord/skyscraper#306]
I updated to your newest version the other day and Vacuum chosen platform is dead. It tells me "Unknown option "unattend""
Took me 10 minutes to figure out how to contact you on here. Sheesh.

**Comment by muldjord** [comment]
Please mind your language if you want my help. It is not broken, but you are using a deprecated option. `unattend` is deprecated and has been for over a year. You need to use the `--flags unattend` option.
