### ISSUE TITLE
Default name for media folder when in the roms system folder causes a signficant load time for ES

### ISSUE THREAD

**Issue by XenuIsWatching** [muldjord/skyscraper#307]
The default name for the media folder is `media`. When emulation station starts, it recurses in the folder structure of the roms folder including the `media` folder and all the screenshot, videos, and etc folders increasing the startup time of emulation station checking all the files and folders wasting it's time. However, if emulations station sees a `.` in front of the folder name, it will ignore. I would propose the the default name be changed to `.media` rather than `media` to prevent emulation station from searching inside of the directory for games.

**Comment by muldjord** [comment]
Good catch, I think that probably makes sense. Only downside I can think of is users who haven't turned hidden files on and being confused about their "missing" media files. Did you perhaps make a comparison of loading times? I would be interested in knowing the actual difference in loading times between the two scenarios.

**Comment by muldjord** [comment]
Thank you for the info. I'll look into it, and probably change it for the next release. I do not control it if you're using the RetroPie script though, only if you use it on command line. So that change will have to come from RetroPie as it is hardcoded into the script I believe (not 100% sure about this though, it might work).

**Comment by muldjord** [comment]
It is now on master (not released, so you need to clone it or download the master branch zip). Could you please test it?

**Comment by XenuIsWatching** [comment]
I was going to test by just editing the retropie script to pull the master branch rather than the latest tag...

What I found was that it still tried to write to `/media`. I did some more digging found that the retropie script is specifing the output folder to be `/media`. I submitted a pull request to move this.
https://github.com/RetroPie/RetroPie-Setup/pull/3342

**Comment by muldjord** [comment]
I've been thinking about this for a bit, and I've decided not to make this the default behaviour. The main reason being that users will end up with double files if they regenerate gamelists with a `.media` folder. So it won't alleviate the problem unless users actually remove their old `media` folders. On top of that I don't quite feel good about hiding the files from the users. Many users aren't used to Linux and I foresee a support issue when users start mistaking their old `media` folders for being the "correct" folder, even though those files are now just taking up space on their harddrives.

Instead, I will introduce a config option, something like
```
[emulationstation]
mediaFolderHidden="true"
```
that the user can decide to set if they have a setup where it makes sense, such as your network setup.

EDIT: This is now on master and works as described above.

**Comment by XenuIsWatching** [comment]
Yeah... I was thinking about your implementation earlier and noted that could be a potential issue. I think having a configuration option would be the ideal option.

Thanks for being prompt and taking this into consideration.
