### ISSUE TITLE
Cannot purge

### ISSUE THREAD

**Issue by DeltaGemini** [muldjord/skyscraper#308]
**Describe the bug**
I've cleared out a number of games and need to clear the cache and delete the extra media files. However, when I try to purge I only see the error "Unknown option: unattend" and it doesn't clear anything.

**To Reproduce**
Choose "Purge All Platforms", "Yes" and the error appears immediately.

**Special circumstances**
[Replace this text with any special circumstances you might have set up on your system that could interfere with how Skyscraper works.]

**Terminal output**
Unknown option: unattend
<img width="570" alt="Screenshot 2021-05-25 at 09 13 45" src="https://user-images.githubusercontent.com/1402197/119456704-3c75b800-bd3b-11eb-8788-e920eec7efaf.png">

**Technical information**
 - Skyscraper version: 3.6.12
 - Internet connection: WIFI
 - OS: Retropie
 - OS Version 4.7.11

**Additional context**
[Replace this text with any additional context that might help understand this issue better. Optional.]

**Comment by muldjord** [comment]
Thank you, this is a problem with the RetroPie script. I've created a pull request at their repository which will fix this.

**Comment by DeltaGemini** [comment]
Awesome, thank you. Is there any fix I can apply in the meantime? Also, is there a known issue with Screenscraper.fr login credentials? I've put mine in the skyscraper config.ini but I'm still being forced onto single thread despite having 6 available on screenscraper.

**Comment by DeltaGemini** [comment]
Awesome, thank you. Is there any fix I can apply in the meantime? Also, is there a known issue with Screenscraper.fr login credentials? I've put mine in the skyscraper config.ini but I'm still being forced onto single thread despite having 6 available on screenscraper.

**Comment by muldjord** [comment]
You probably entered it incorrectly, I get that a lot. Enter it **exactly** like this, but with your `USER:PASSWORD` of course:
```
[screenscraper]
userCreds="USER:PASSWORD"
```

A temporary fix is to edit the script manually with the changes from the pull request https://github.com/RetroPie/RetroPie-Setup/pull/3344

EDIT: Deleted double comment

**Comment by DeltaGemini** [comment]
Thank you! I'll look at the pull request.

As for the screenscraper info, I'm sure I have my details correct. My
Screenscraper username is DeltaGemini and I've double-checked the password.
I assume both username and password are case sensitive?
This is from the bottom of my config file, is it the correct placement?:

#[<SCRAPING MODULE, eg 'screenscraper'>]
userCreds="DeltaGemini:CorrectPassword"
threads="6"
#minMatch="0"
#maxLength="10000"
#interactive="false"
#cacheResize="false"

**Comment by muldjord** [comment]
Your details are correct, but you did not enter them as I mentioned. Please read my previous comment, and remove the `threads="6"` line, it is not needed.

**Comment by DeltaGemini** [comment]
Thank you, it's working now

**Comment by muldjord** [comment]
The fix has now been merged into the official RetroPie repository. Please update the script through RetroPie and it should now work.

**Comment by DeltaGemini** [comment]
Brilliant, thank you for letting me know.
