### ISSUE TITLE
Add support for the PC Engine SuperGrafx and Nintendo 64DD

### ISSUE THREAD

**Issue by XenuIsWatching** [muldjord/skyscraper#309]
# Describe the feature / request

Add support for the PC Engine SuperGrafx and Nintendo 64DD

## PC Engine SuperGrafx

Although you can throw the SuperGrafx image files into the `pcengine` folder. It can't scrape them as this has a seperate id through screenscraper fr (only 5 games tho...)

## Nintendo 64DD

same as above...

# Additional context

## Appendix

| Skyscraper Platform           | Platform Name                  | File Extensions              | Screenscraper fr ID |
| ----------------------------- | ------------------------------ | ----------------------------- | ------------------- |
| PC Engine SuperGrafx               | supergrafx                  |  \*.pce \*.zip              | 105                 |
| Nintendo 64DD               | n64dd                  |  \*.ndd              | 122                 |

**Comment by muldjord** [comment]
Hi, just looked into this. The Nintendo 64DD platform is already a subplatform of 'n64' when using Screenscraper. I scrape n64dd games just fine with the current version of Skyscraper. Do you have any examples of this not working? I'm thinking it's a problem with your files simply not being matched to their database or similar issue.
```
<systeme>
	<id>122</id>
	<parentid>14</parentid>
	<noms>
		<nom_eu>Nintendo 64DD</nom_eu>
```
The above shows the id and parentid from the API. This ensures that all subplatforms for the id Skyscraper contains, will also be considered when returning results. It's a tree structure that includes subplatforms from the parentid.

The same should be the case for the Supergrafx platform, as you can see here:
```
<systeme>
	<id>105</id>
	<parentid>31</parentid>
	<noms>
		<nom_eu>PC Engine SuperGrafx</nom_eu>
```

**Comment by XenuIsWatching** [comment]
*Sorry for getting back to you late, I somehow missed your comment*


Ah, I had these within a separate folder within the directory, I like to keep each with its own theme within emulation station 😉 . A while ago, I went ahead and implemented it myself here: https://github.com/XenuIsWatching/skyscraper/tree/platforms-n64dd-supergrafx

**Comment by muldjord** [comment]
Thanks, I'll close this issue.
