### ISSUE TITLE
Relative paths for images + roms

### ISSUE THREAD

**Issue by otherguy** [muldjord/skyscraper#31]
If I understand the `gamelist.xml` format correctly, relative paths to the rom and the media files are supported. It would be nice if Skyscraper supported that, either by default or with a command line switch.

The reason is that I (like others I suppose) use Skyscraper on a different device (I use it on both my Mac and a Synology) and the paths in the resulting `gamelist.xml` need to be fixed manually in order to work on my portable RetroPie console.

**Comment by muldjord** [comment]
What should it be relative to? The rom files? So it would output "<path>./romname.d64</path>"? And "<image>./media/screenshots/romname.png</image>" for the image and so on?

It won't be default, but I might implement it with an option, no promises.

**Comment by otherguy** [comment]
@muldjord interesting, I got the notification for both comments at the same time 🤔 

Yes, that's exactly what I mean. On my Mac, the rom path is `/Users/otherguy/roms/<system>/` and since that is where I point Skyscraper, this paths ends up in the `gamelist.xml`. 

Now obviously my RetroPie installation on my Raspberry has no notion of that path because its roms are in `/home/pi/RetroPie/roms/<system>`. Since relative paths are supported by EmulationStation, that would make my life a lot easier because I don't have to manually correct the path in the resulting XML. It's just a call to `sed` but still...

> It won't be default, but I might implement it with an option, no promises.

Absolutely. For most people, an absolute path is fine. It would be a nice option though.

**Comment by muldjord** [comment]
Thank you for the reponse, I might cook something up and add a '--relative' option or something like that. :)

**Comment by otherguy** [comment]
@muldjord sweet, thanks 😄 My C++ skills are a bit rusty unfortunately, else I would take a stab at a PR.

**Comment by muldjord** [comment]
2.5.1 is now released with a '--relative' option that forces relative paths in the EmulationStation gamelist.xml. If you can, please test it and see if it works as expected. Thanks!

**Comment by otherguy** [comment]
@muldjord sweet! That was fast. I will test it once I'm home tonight. Thank you ❤️ That will make my life easier!

**Comment by otherguy** [comment]
@muldjord I know it's been a while but I just wanted to let you know that the `--relative` option works flawlessly! I'm very grateful that you added it, since I've built 3 systems in the meantime and I can just copy my rom library to all of them (one portable system actually `rsync`s the roms from my NAS and the other 2 systems are not portable so they just access it from SMB).

Thanks for building an awesome piece of software!

**Comment by muldjord** [comment]
Thanks for letting me know that it works well for you in your use case. I appreciate it!
