### ISSUE TITLE
Add <platform> tag to gamelist generator

### ISSUE THREAD

**Issue by gerosil** [muldjord/skyscraper#310]
**Describe the feature / request**
the arcade/mame-scraper scrapes platform info like:

Platform:       'Sega Classics'

but after gamelist-generation, there is no <platform>-tag in the xml file.
The definitions.dat.example-files have no ###PLATFORM###-tag, too

It would be nice to use emulationstations built-in filter for platforms (if possible)

**Comment by muldjord** [comment]
> the arcade/mame-scraper scrapes platform info like:
> Platform: 'Sega Classics'

I don't know what that means, please be more specific.

> but after gamelist-generation, there is no -tag in the xml file.

I don't know what a '-tag' means, please be more specific.

> It would be nice to use emulationstations built-in filter for platforms (if possible)

Yes, but I need very specific examples of how this works. Please provide more information overall.

**Comment by gerosil** [comment]
sorry, misspelled. it should say:
but after gamelist-generation, there is no **platform**-tag in the xml file.

like

```
<game>
  <title>###TITLE###</title>
  <description>###DESCRIPTION###</description>
  <developer>###DEVELOPER###</developer>
  <publisher>###PUBLISHER###</publisher>
  <players>###PLAYERS###</players>
  <rating>###RATING###</rating>
  <ages>###AGES###</ages>
  <genre>###TAGS###</genre>
  <releasedate>###RELEASEDATE###</releasedate>
  THIS IS NEW: <platform>###PLATFORM###</platform>
</game>
```

I could imagine, that there would be something like that in gamelist.xml:

```
<game>
..
<platform>Sega Classics</platform>
</game>
```

and emulationstation can filter by that

**Comment by muldjord** [comment]
> I could imagine, that there would be something like that in gamelist.xml: `<platform>Sega Classics</platform>`

Can you please provide documentation for this tag. I haven't heard about this before, so I need documentation before I can add it.

**Comment by muldjord** [comment]
Closing due to lack of response.
