### ISSUE TITLE
Add chd extension to atomiswave platform

### ISSUE THREAD

**Issue by smeegoan** [muldjord/skyscraper#314]
Add chd extension to atomiswave platform because this extension is supported

**Additional context**
Requires 1 line change in platform.cpp

**Comment by muldjord** [comment]
Thanks. This has now been added and will be in the next release (no eta currently). In the meantime, you can add it manually to `~/.skyscraper/config.ini` with:
```
[atomiswave]
addExtensions="*.chd"
```
