### ISSUE TITLE
Any unclosed quote in comments causes skyscraper to always log in as `anonymous` on `screenscraper.fr`

### ISSUE THREAD

**Issue by keks24** [muldjord/skyscraper#316]
**Describe the bug**
Any unclosed quote in comments causes `skyscraper` to always log in as `anonymous` on `screenscraper.fr` I could also reproduce this with different comments.

I have not tested this for `other scraping sources`, yet.

**To Reproduce**
1. Open the configuration file `/home/pi/.skyscraper/config.ini`
2. Append the following information for `screenscraper.fr`:
```ini
[screenscraper]
userCreds="<some_username>:<some_password>"
interactive="false"
cacheCovers="true"
cacheScreenshots="true"
cacheWheels="true"
cacheMarqees="true"
```
3. Start `gathering resources` via`skyscraper` via `retropie_setup.sh`: `sudo /home/pi/RetroPie-Setup/retropie_setup.sh`
3.1. Go to `Configuration / tools - skyscraper - Gather resources`
3.2. Mark `gbc` using the `space key`
3.3. Move the cursor to `<Start>` and press the `Enter key`
3.4. Move the cursor to `<Proceed>` and press the `Enter key`
3.5. Immediately, gracefully abort the process by pressing `CTRL+C` once
4. Do a `backward search` in the `terminal buffer` and search for the string `Fetching limits for user '<some_username>'`:
```no-highlight
Fetching limits for user '<some_username>', just a sec...
Setting threads to 1 as allowed for the supplied user credentials.
```
5. Repeat `step 1`
6. Navigate to the comment `#videoConvertCommand="ffmpeg -i %i [...]"`
7. Remove one quote sign like so: `#videoConvertCommand=ffmpeg -i %i [...]"`
8. Repeat `step 3`
9. Search for the string `anonymous`:
```no-highlight
Forcing 1 threads as this is the anonymous limit in the ScreenScraper scraping module. Sign up for an account at https://www.screenscraper.fr and support them to gain more threads. Then use the credentials with Skyscraper using the '-u use
r:password' command line option or by setting 'userCreds="user:password"' in '/home/USER/.skyscraper/config.ini'.
```

For `step 6 and 7`: Any other comments can be used as well.

**Special circumstances**
None.

**Terminal output**
See above.

**Technical information**
 - Skyscraper version: `3.6.15` (compiled `from source`)
 - Internet connection: `wifi`
 - OS: `RetroPie 4.7.15 (Commit a78526b8, 8 weeks ago)`
 - OS Version: `Raspbian Buster (Debian 10)`

**Additional context**
None.

-Ramon

PS: `HTML comments` (`<!-- -->`) can be used to hide instructions for the issue template. :)

**Comment by keks24** [comment]
`ini comments` (`;`) are ignored properly, so the following is not affected in the `config.ini`:
```ini
; something "text
```

This means, that using the correct comment characters will fix this.

**Comment by muldjord** [comment]
Both hash and semicolon are correct comment characters, so I would argue against semicolon being the correct one as you state. Hash are more widely used. Semicolon are used, but less so. I don't feel like this edge case is sufficient cause to change it to the lesser used semicolon. Thanks anyway.

**Comment by muldjord** [comment]
Reopening, I read up on the actual ini file format, and it seems you are correct. I will consider changing this. Thanks.

**Comment by muldjord** [comment]
Fixed, closing.

**Comment by keks24** [comment]
> Reopening, I read up on the actual ini file format, and it seems you are correct. I will consider changing this. Thanks.

Sure thing! :)

> Fixed, closing.

Awesome!

But now I ask myself, why the configuration file was parsed in a semi-wrong way? We may never know, he he.

**Comment by muldjord** [comment]
It seems like using hash in an ini file actually has some sort of functionality in conjunction with lines that have variable definitions. That would somewhat explain the behaviour as those lines would be parsed differently and ends up just looking like "odd behaviour".
