### ISSUE TITLE
List / delete scraped roms without screenshots

### ISSUE THREAD

**Issue by petershaw23** [muldjord/skyscraper#319]
I am trying to scrape a huge PC98 romset. About half of the roms get recognized, but don't have any entries, (except the name). I don't want to keep roms that don't have a screenshot.
Is there any way to list / delete such roms, similar to the "skipped-*.txt" function?

**Comment by muldjord** [comment]
Hi, Skyscraper can't delete roms, that is not something it is capable of. But you can easily export a report containing all of the files that don't have a screenshot, and then feed that into the Linux `rm` command.

But before you do so, I would recommend creating a backup of the Skyscraper cache, just in case. You can do so by simply copying the entire `~/.skyscraper/cache` folder to somewhere else.

Then, you can create the report using:
```
$ Skyscraper -p pc98 --cache report:missing=screenshot
```
This will create a file in `~/.skyscraper/reports` with all of those files.

When you've remove the roms, you can consider vacuuming the Skyscraper cache for the platform, which will then remove any cached resources that were connected to the now removed roms:
```
$ Skyscraper -p pc98 --cache vacuum
```

**Comment by petershaw23** [comment]
Thank you! Worked perfectly. Managed to move the files to another directory by using this bash command:
`sed 's/^ *//' < report-pc98-missing_screenshot-20210929.txt | xargs -d '\n' mv -t \temp-dir\`
