### ISSUE TITLE
TheGamesDB.net scraper not working

### ISSUE THREAD

**Issue by crash123** [muldjord/skyscraper#32]
TheGamesDB.net scraper is not working. Nothing is being scraped. It looks like they may have fully depreciated their old API.

**Comment by crash123** [comment]
Oops... looks like you already know.

**Comment by muldjord** [comment]
Thanks for the heads up anyways. I was aware of the new api, but not that they had switched over completely. So I'll need to look into this soon'ish.

**Comment by muldjord** [comment]
2.5.0 released with updated 'thegamesdb' api. Unfortunately it is pretty useless, since the guys over at TheGamesDb have implemented some very low limits. There's nothing I can do about this, and they don't seem to be willing to work with us on this at this moment.

**Comment by crash123** [comment]
Thanks for that. I saw your post on their forum they appear to have made some unusual/poor decisions regarding API request limits without thinking about who their target demographic is. It is frustrating to say the least.

**Comment by muldjord** [comment]
Yes, it is unfortunate that they have hooked themselves onto this "mirror is everything" approach. In practice I don't see it ever being used by anyone. Time will tell if I'm right.
