### ISSUE TITLE
What about supporting Thomson computers ("moto" in Retropie)?

### ISSUE THREAD

**Issue by Yserra** [muldjord/skyscraper#322]
I know you don't have time to implement new features, so it's like a bottle thrown into the sea.

**Describe the feature / request**
Support Thomson "moto" machines (MO5, MO6, TO7, TO8, TO9...), with extensions ".k7", ".sap", ".fd", ".m5", ".m7", ".rom"

I would suggest something like "-p moto"

**Additional context**
This platform is supported on screenscraper:
https://screenscraper.fr/romsinfos.php?plateforme=141&alpha=0&numpage=0

And on Retropie:
https://retropie.org.uk/docs/Thomson-MOTO/

Many thanks for your time and your great software.

**Comment by muldjord** [comment]
You're welcome. 'moto' platform has now beed added and will be in 3.6.16. Thanks for the suggestion.

**Comment by Yserra** [comment]
You're fantastic! Thank you so much!! I'm so happy!

**Comment by muldjord** [comment]
I'm glad! :) 3.6.16 is out now. Please test the 'moto' platform if you can. I don't have any roms for it, so I can't really test it that well.

**Comment by Yserra** [comment]
Yes!! It works perfectly! I just scraped 400+ MOTO Roms (from screenscraper.fr). Everything runs as expected.
A big thank you!

**Comment by muldjord** [comment]
Awesome! Thank you for testing. Closing ticket.
