### ISSUE TITLE
Implement support for scraping EasyRPG platform on Screenscraper

### ISSUE THREAD

**Issue by ghost** [muldjord/skyscraper#325]
The screenscraper.fr site has added a platform known as EasyRPG, used by RPG Maker 2000/2003 games. Adding support for it should allow us to sync metadata as well as the media images stored there.

Site: https://www.screenscraper.fr/systemeinfos.php?plateforme=231&alpha=0&numpage=0

Platform number needed by screenscraper.cpp: 231

**Comment by muldjord** [comment]
This platform has now been added as 'easyrpg' in the newly releaed 3.7.0. Closing.
