### ISSUE TITLE
set video=true in config.ini but not seeing videos in commandline output.

### ISSUE THREAD

**Issue by Bboy486** [muldjord/skyscraper#334]
I assume I am supposed to see a video flag when scraping but I do not. 

#35/6354 (T4) Pass 1 ---- Game 'kotm2' found! :) ----
Scraper:        screenscraper
From cache:     NO
Search match:   100 %
Compare title:  'King of the Monsters 2 - The Next Thing'
Result title:   'King Of The Monsters 2 - The Next Thing' ()
Platform:       'Neo-Geo' ()
Release Date:   '1992-01-01' ()
Developer:      'SNK' ()
Publisher:      'Takara' ()
Players:        '2' ()
Ages:           '' ()
Tags:           'Beat'em Up' ()
Rating (0-1):   '0.75' ()
Cover:          YES ()
Screenshot:     YES ()
Wheel:          YES ()
Marquee:        YES ()

config.ini

[main]
;inputFolder="/home/pi/RetroPie/roms"
;excludePattern="*[BIOS]*"
;includePattern="Super*"
;excludeFrom="/home/pi/.skyscraper/excludes.txt"
;includeFrom="/home/pi/.skyscraper/includes.txt"
;gameListFolder="/home/pi/RetroPie/roms"
;gameListBackup="false"
;mediaFolder="/home/pi/RetroPie/roms"
;cacheFolder="/home/pi/.skyscraper/cache"
;cacheResize="false"
;nameTemplate="%t [%f], %P player(s)"
;jpgQuality="95"
;cacheCovers="true"
;cacheScreenshots="true"
;cacheWheels="true"
;cacheMarquees="true"
;importFolder="/home/pi/.skyscraper/import"
;unpack="false"
;frontend="emulationstation"
;emulator=""
;launch=""
;videos="true"
;videoSizeLimit="42"
;videoConvertCommand="ffmpeg -i %i -y -pix_fmt yuv420p -t 00:00:10 -c:v libx264 -crf 23 -c:a aac -b:a 64k -vf scale=640:480:force_original_aspect_ratio=decrease,pad=640:480:(ow-iw)/2:(oh-ih)/2,setsar=1 %o"
;videoConvertExtension="mp4"
;symlink="false"
;brackets="true"
;maxLength="10000"
;threads="2"
;pretend="false"
;unattend="false"
;unattendSkip="false"
;interactive="false"
;forceFilename="false"
;verbosity="1"
;skipped="false"
;maxFails="30"
;lang="en"
;region="wor"
;langPrios="en,de,es"
;regionPrios="eu,us,ss,uk,wor,jp"
;minMatch="0"
;artworkXml="artwork.xml"
;relativePaths="false"
;addExtensions="*.zst"
;hints="false"
;subdirs="true"
;spaceCheck="true"
;scummIni="/full/path/to/scummvm.ini"

; The following is an example of configs that only affect the 'screenscraper' scraping module.
;[screenscraper]
;userCreds="xxx:xxxx"
;threads="1"
;minMatch="0"
;maxLength="10000"
;interactive="false"
;cacheResize="false"
;jpgQuality="95"
;cacheCovers="true"
;cacheScreenshots="true"
;cacheWheels="true"
;cacheMarquees="true"
;videos="true"
;videoSizeLimit="42"
;videoConvertCommand="ffmpeg -i %i -y -pix_fmt yuv420p -t 00:00:10 -c:v libx264 -crf 23 -c:a aac -b:a 64k -vf scale=640:480:force_original_aspect_ratio=decrease,pad=640:480:(ow-iw)/2:(oh-ih)/2,setsar=1 %o"
;videoConvertExtension="mp4"
;;The following option is only applicable to 'screenscraper'
;videoPreferNormalized="true"

[esgamelist]
cacheRefresh="true"

[import]
cacheRefresh="true"

[convert]
videoConvertCommand="videoconvert.sh %i %o"

**Comment by muldjord** [comment]
Yes, you need to remove the `;` in front of the line. Unless you do so it will be seen as a comment and ignored.

**Comment by Bboy486** [comment]
Thank you. Do you know what this error means?

Video conversion: Failed! (set higher '--verbosity N' level for more info)
