### ISSUE TITLE
Scrapes in Windows but not Linux

### ISSUE THREAD

**Issue by devanteweary** [muldjord/skyscraper#339]
Hello,

I have an issue scraping...

So I run Skyscraper on my Windows 10 PC and it grabs the images but doesn't follow any flags I put in.
For instance, --flags forcefilename

So I gave up and installed Ubuntu on Virtual Box and now when I try it, it won't even find the files and/or connect to the DB.
I'm using ArcadeDB.

I've verified I can get to websites on the Ubuntu install.

Here's what I get in Virtual Ubutnu

![image](https://user-images.githubusercontent.com/29805497/163699553-4165aa32-607d-4ff4-b93d-ce5b93a2f4fb.png)

But on the same laptop, in Windows, it downloads the images but ignores flags and even ignores anything I put in the config.ini

Does anyone know what could be happening with the Linux version?

Thank you!

**Comment by muldjord** [comment]
Please post this on the RetroPie forums or the Reddit RetroPie subreddit. Thanks.

**Comment by devanteweary** [comment]
OK. Just confirming though since this isn't RetroPie related at all, I should still post over there?

**Comment by muldjord** [comment]
It's the most official places to get help using Skyscraper, so I'd say yes.
