### ISSUE TITLE
Support for extra extension(s)

### ISSUE THREAD

**Issue by herbymachine** [muldjord/skyscraper#34]
First of all great work. Your scarper is extremely useful!

To make it even better, could we have extra file extension support and not just the build in file types?
I usually use zstd to compress my roms and the scrapper ignores them.

Something like --extraextension < file extension >

**Comment by herbymachine** [comment]
I am using a wrapper to decompress my roms on the fly and thanks to the speed of zstd it is very fast. The extension for zstd is zst. However, ztsd adds a file extension to the existing extensions, e.g. .bin.zst , iso.zst ,.... hence there could be a ton of different file extensions for a system. That's why I thought to add custom file extensions on the command line would give Skyscraper more usefulness. I can wait if you need more time, no problem. :)

**Comment by muldjord** [comment]
2.5.3 released with '--allowext' option and 'allowExtension' you can use in config.ini. :)

**Comment by herbymachine** [comment]
Just tested it and it works great! Thank you for doing it in this release already! Really appreciate your work!
