### ISSUE TITLE
Add Pico8 platform to Screenscraper

### ISSUE THREAD

**Issue by ghost** [muldjord/skyscraper#345]
The screenscraper.fr site has added a platform known as pico8, a fantasy microconsole. Adding support for it should allow us to sync metadata as well as the media images stored there.

[Site: https://www.screenscraper.fr/systemeinfos.php?plateforme=234&alpha=0&numpage=0]

Platform number needed by screenscraper.cpp: 234

**Comment by muldjord** [comment]
3.7.6 released with 'pico8' now supported. Only works with 'screenscraper' though, as none of the other sites seem to have Pico-8 games. Just keep that in mind when using it.
