### ISSUE TITLE
SegaCD scans ignore .m3u files

### ISSUE THREAD

**Issue by bmn001** [muldjord/skyscraper#347]
**Describe the bug**
My entire CD library consists of either .chd files or - if it's a multi-game CD - .m3u files that contain lists of .chd files.

Skyscraper is able to scrape metadata and screenshots across all of them without a problem, **except** when it comes to Sega CD M3Us.  Sega CD .chd files are scanned and listed properly.  M3Us are seemingly ignored.

**To Reproduce**
Scan a directory with Sega CD .chd and .m3u files, then generate a  list.  The m3u files will appear in Emulation Station with no art and no metadata.

**Special circumstances**
n/a

**Terminal output**
n/a

**Technical information**
 - Skyscraper version: 3.7.6
 - Internet connection: Cable 
 - OS: RetroPie
 - OS Version 4.8.2

**Additional context**
This was brought up in the RetroPie forums and a fix was found: https://retropie.org.uk/forum/topic/32915/skyscraper-and-sega-cd-m3us

Adding `--addext *.m3u` to the scrape and build commands from the cli was all it took to get this working.

A more permanent fix would be to add *.m3u as an accepted format to the segacd platform https://github.com/muldjord/skyscraper/blob/00240a9cb58c1196f6d46a0d959cc3b94facee4c/src/platform.cpp#L506-L507=

I hope this helps - and thanks for the great app!

**Comment by muldjord** [comment]
This now included in 3.7.7. Thanks.
