### ISSUE TITLE
Scraping with mobygames just hangs 

### ISSUE THREAD

**Issue by LimeyGeeza** [muldjord/skyscraper#36]
Just trying to clean up some c64 roms that didn't scrape with Moby Games database, but when I run the command nothing happens.

**Describe the bug**
Scraping using $ Skyscraper -p c64 -s mobygames, just hangs in the terminal - it doesn't scrape or pull any results. I can scrape with all the other db's just fine.

Given the message below and it just hangs.
Starting scraping run on 4648 files using 1 threads.
Sit back, relax and let me do the work! :)

**To Reproduce**
Skyscraper -p c64 -s mobygames

**Special circumstances**
No - Vanilla retropie build

**Terminal output**
If applicable, add terminal output to help visualize your problem.

**Technical information**
 - Skyscraper version: 2.5.3
 - Internet connection: wifi
 - OS: Retropie with Emulationstation
 - OS Version 4.4

**Comment by muldjord** [comment]
Mobygames is not yet fully implemented I'm afraid so that's the reason. The supported scraping modules can be seen with '--help' look for the '-s' option. :)

I was working on it about 2 month's ago, but got distracted, and I haven't had time to look into it since. But it will work eventually, in a future version.

**Comment by muldjord** [comment]
Btw, just out of curiosity, how did find out that the 'mobygames' module exists? I don't have it listed anywhere to my knowledge.

**Comment by LimeyGeeza** [comment]
I read in your release notes that you had implemented it for manual mode only. Now I see that it is ‘still unimplimented’. So my bad trying something before you have released!

Great scraper by the way, love what you have done! Keep up the good work :)

**Comment by muldjord** [comment]
Ah, yes. I can see why that would be confusing. Thank you, glad you like it. :)
