### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by jpunzel** [muldjord/skyscraper#39]
I can think of a few situations in which it would be handy to use a proxy when scraping. It would be nice to see a command line option to specify a SOCKS proxy, or possibly just have Skyscraper obey the `http(s)_proxy` environment variables.

I was able to paste some very boilerplate `QNetworkProxy` setup code in the `NetComm` class constructor and it seemed to work OK with my simple localhost SOCKS proxy that I created with `ssh -D8080 <myremotehost>`. I think it would be relatively straightforward to make this a configurable option.

**Comment by muldjord** [comment]
I assume you would use this to change the IP to circumvent the limits in the scraping modules. I'm not sure if you're aware of it, but the relationship between the scrapers (me and others) and the sources (thegamesdb and others) is imperative for this software to keep working. And trying to avoid their limits would completely break that bond. So with that in mind, I have absolutely no interest in supporting this. And please do not use Skyscraper for this at all. It uses my API key, and if they see it being used like this, they will cut off usage immediately. Not just for you, but for all users and you would have rendered my software useless with that module. So please don't do this. :) Thank you.
