### ISSUE TITLE
Option to scrape all platforms

### ISSUE THREAD

**Issue by fOmey** [muldjord/skyscraper#4]
Title is self explanatory.

**Comment by muldjord** [comment]
Not planned. Skyscraper is meant to be run per platform. If you plan to scrape more than one platform, I suggest scripting multiple runs. It was designed for this.

**Comment by fOmey** [comment]
Yeah I've been using a bash script to accomplish this.. however I still think it would be a good idea to bake the functionality right into the scraper for new users.

**Comment by retrobit** [comment]
At least, I think it could be explicitly mentioned in the documentation, to save some time and confusion. Also, doesn't throw any error when omitting the "-p" option, making the user think it's attempting such a function by default.

**Comment by Lalarian** [comment]
True! Just trying Skyscrasper the firt time and I had to first research for finding that Skyscraper sinply cannot scrape all platforms at once.
Also I now have to search/make a bash script for processing the surely most normal task: Scraping my whole new games directory.

**Comment by retrobit** [comment]
Do check out https://github.com/Gemba/skyscraper. It's the latest official fork with fixes, more features, and great documentation.

Specifically for this feature, it hasn't been added. I also haven't checked on if the documentation has been improved or not.

However, you can get the same/similar effect by chaining commands with && and ||, or scripting.
