### ISSUE TITLE
Specify allowed extensions for each platform

### ISSUE THREAD

**Issue by twiginteractive** [muldjord/skyscraper#40]
Hi - 

This is a great tool (way better than the built GamesDB in Emulation Station! However for the Amiga emulator setup I have on RetroPie/UAE4ARM, I need two files (minimum) per game - the ADF(s) and the UAE config. This means Skyscraper scrapes (at least) 2x more files than it needs too - or at least it reports 2x the number of files during the scrape.

Would it be possible to add a filter to the config.ini under [platform] for 'accepted-extensions' or something similar? Then for Amiga, I could just use ".uae".

**Comment by muldjord** [comment]
2.5.4 out now, which now supports the 'extensions=' in the platform sections of config.ini. It will completely overwrite the default extensions allowing you to put in, for instance, 'extensions="*.this *.that"'

Enjoy! :)

**Comment by twiginteractive** [comment]
Amazingly quick turnaround! Thanks
