### ISSUE TITLE
PSX ROMs scrape no data or null data

### ISSUE THREAD

**Issue by justinmcrp** [muldjord/skyscraper#41]
Attempting to run Skyskraper from the command line and Skyskraper -p psx both result in the same outcome. Games are either not found or are found but scrape no valuable data; there are no images, genre/date/player count is unknown, and there is no description. Essentially, scraping for PSX won't return values from any scraping source.

ROM file types: bin/cue, img, pbp
ROM file names: versions of Game Name, Game Name (region), and Game Name (SLUS-1234)
RetroPie version: 4.4
Skyscraper version: latest release (installed 2 days ago)
internet: 20 mb/s DSL
machine: no special circumstances or modifications, ROMs run from local microSD
commands: both Skyscraper and Skyscraper -p psx experience the issue
scrape settings: default paths, default matching percentage, not scraping video, have tried adjusting the other few options with no effect

**Comment by muldjord** [comment]
Please try "Skyscraper -p psx -s thegamesdb --updatedb" and "Skyscraper -p psx -s screenscraper --updatedb" and post the intitial output from that plus the first game output.

**Comment by justinmcrp** [comment]
It managed to pull data for a number of games, but there are still about 20% of the file list missing at least one major element (description, screencap, box art). There's no rhyme or reason as to what acquired scraped data and what did not.

**Comment by muldjord** [comment]
It is normal for games to be missing some data. It is a community driven effort, so manu games are missing certain pieces of data which needs to be filled in by the community. You can do this yourself if you want to by creating an account at screenscraper.fr, finding the games, and adding the info. :)
