### ISSUE TITLE
Dreamcast - scrapes return same information for all roms

### ISSUE THREAD

**Issue by richarnd** [muldjord/skyscraper#42]
I've successfully scraped a wide range of systems. I'm now trying to scrape Dreamcast roms and Skyscraper is behaving strangely.

If I scrape in --pretend --updatedb mode, everything works fine. But in any "real" (i.e. not "pretend") mode, Skyscraper copies the same information (title, description, video, etc) to ALL of my roms. Which game it chooses seems random. For example, in my most recent run all roms scraped information related to "Virtua Tennis". Sometimes it's even I game I don't have (D-2) that shouldn't be in my local db at all! 

Exact command that led to the behavior:

Skyscraper -u xxx:yyy -s screenscraper --videos --nobrackets -p dreamcast

I've tried purging the db, even deleting the "dreamcast" folder under ~/.skyscraper/dbs. Nothing seems to change the behavior. Again, other systems work fine. 

I did update all packages on my pi today, but I was able to scrape other systems successfully after the update, so I don't think it's related.

**Comment by muldjord** [comment]
Does it also do it with: Skyscraper -u xxx:yyy -s screenscraper --videos --nobrackets -p dreamcast --updatedb?

Could you give me examples of one or two of the EXACT dreamcast filenames it scrapes?

I have a hunch that it's related to the id of the files. I use the sha1 checksum to link rom files to content from the local database cache. But if the contents of any of your rom files is a script and they contain the same data for 2 or more of them, they will be matched to the same game even though they have differing filenames.

**Comment by richarnd** [comment]
That worked for all but one game. I'm not sure why the error happened originally. I know hash checking likely won't work as I compressed these roms to *.chd myself.

One game, "Crazy Taxi (USA).gdi" (123,891,451 bytes) does still scrape as "D-2", a game I don't own. Maybe this is a problem with Screenscraper's archive, though?

**Comment by muldjord** [comment]
If it does this with the '--updatedb' flag, then it seems like it's a problem with screenscraper. With the '--updatedb' flag in use, nothing is used from the local cache and as such will only show data from the source. So maybe they are having some issues. Not sure. I've never seen this problem myself.

And if your files are chd's all of them, then it's not a sha1 issue either as none of those files are the same and thus gives back different checksums.

**Comment by muldjord** [comment]
Can' reproduce, closing. Let me know if this issue persists and you find a way to reproduce it.
