### ISSUE TITLE
Screenscaper fails for specific PSX title

### ISSUE THREAD

**Issue by jdcrensh** [muldjord/skyscraper#43]
I can't get the screenscaper module to work for a specific title. Running with latest version of Skyscraper. All other titles scrape without issue.

```
$ uname -a
Linux retropie 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux
```

Metal Slug X (USA).cue
```
$ md5sum roms/psx/Metal\ Slug\ X\ \(USA\).cue
3f7584d4de401e140f26a63ffbf74d11  roms/psx/Metal Slug X (USA).cue
$ sha1sum roms/psx/Metal\ Slug\ X\ \(USA\).cue
3c4b2b6f58c8c9d9dddb72d755d19587550e1787  roms/psx/Metal Slug X (USA).cue
```

Listing at screenscraper:
https://www.screenscraper.fr/rominfos.php?romid=275439&zone=rominfosgenerales

Output with `--verbosity 3`

```
#1/1 (T1) Pass 1 Pass 2 Pass 3 Pass 4 ---- Game 'Metal Slug X (USA)' not found :( ----


Debug output:
Tried with sha1, md5, filename: 'Metal%20Slug%20X%20%28USA%29.cue', '3C4B2B6F58C8C9D9DDDB72D755D19587550E1787', '3F7584D4DE401E140F26A63FFBF74D11'
Platform: psx
Tried with sha1: 3C4B2B6F58C8C9D9DDDB72D755D19587550E1787
Platform: psx
Tried with md5: 3F7584D4DE401E140F26A63FFBF74D11
Platform: psx
Tried with name: Metal%20Slug%20X%20%28USA%29.cue
Platform: psx

Elapsed time: 00:00:01
Estimated time left: 00:00:00
```

As you can see, the name, md5, and sha1 all match up with the screenscraper listing for this file.

**Comment by muldjord** [comment]
This is because the rom is known by screenscraper, but it hasn't been mapped to a specific set of data. Try clicking the "Assignation Rom > Jeu" button. It doesn't show any game connections. I think you can do this by creating an account on their page and requesting that file to be linked to the game.

**Comment by muldjord** [comment]
I just signed it and did the association. It did look like the association was there when I signed in though, so not sure what is going on. Either way, this is related to the screenscraper database, and not Skyscraper. :)

**Comment by muldjord** [comment]
I found the error with this one. 'screenscraper' has the region of this particular .cue file set to 'ss' which is noted as 'screenscraper' so I guess that's some sort of default one for games they don't have a region for. In the current Skyscraper version I don't recognize that region. I just added it, and now it works. This fix has just been released in 2.5.5.

Could you test it out and report back if you have any more similar issues?

**Comment by jdcrensh** [comment]
@muldjord now works perfectly, thanks!

**Comment by muldjord** [comment]
Awesome!
