### ISSUE TITLE
<video> tags are removed from gamelist.xml when entries are skipped

### ISSUE THREAD

**Issue by ozy24** [muldjord/skyscraper#46]
Hello.

Here are the steps I followed to reproduce this issue:

1) Run skyscraper.sh with the following lines:

```
#!/bin/bash
Skyscraper -p arcade --nobrackets --videos --unattend -s screenscraper --pretend
Skyscraper -p arcade --nobrackets --videos -s localdb
```

Skyscraper generates correct XML with <video> lines such as:
`<video>/home/pi/RetroPie/roms/arcade/media/videos/bublbobl.mp4</video>`

2) Re-run same skyscraper.sh script
3) When asked the question `'gamelist.xml' already exists, do you want to overwrite it (y/N)? `I select "y"
4) When asked the question `Do you wish to skip existing entries (y/N)?`, I select "y" (I like to make custom changes/corrections that I don't want overwritten)

Result: gamelist.xml should remain the same for existing entries but instead all `<video>` lines are removed

**Technical information**
 - Skyscraper version: 2.6.0
 - Internet connection: ADSL
 - OS: RetroPie
 - OS Version 4.4

Regards,

Chris

**Comment by ozy24** [comment]
Great! Thank you very much. :)

**Comment by muldjord** [comment]
2.7.0 out now with this fixed. :) Please update.
