### ISSUE TITLE
Command line switch to always skip existing entries

### ISSUE THREAD

**Issue by ozy24** [muldjord/skyscraper#47]
I tried to find this option in help but couldn't see it so apologies if I missed something.

Instead of responding to the question each time skyscraper.sh is run, it would be useful to have a switch to always skip existing entries in case there is a need to preserve custom entries in gamelist.xml. 

Cheers,

Chris

**Comment by muldjord** [comment]
Hmm, yeah. I have the opposite which is '--unattend' and never skips. I'll add an '--unattendskip' option or something. Will be in 2.7.0 aswell soon. :)

**Comment by ozy24** [comment]
OK that's great many thanks. It's the default behaviour in sselph's scraper so thought it would be nice to include it in Skyscraper as well. :)

**Comment by muldjord** [comment]
2.7.0 out now with the '--unattendskip' flag included. Please update :)
