### ISSUE TITLE
Needs updating documentation for Mac installation

### ISSUE THREAD

**Issue by abritinthebay** [muldjord/skyscraper#48]
Long story short, based on my new mac, the installation steps need to include:

```
$ brew install wget
$ brew link qt5 --force
```
Small detail but important 😄

**Comment by muldjord** [comment]
I will add the "brew install wget" command, thank you.
The brew link command I am not too sure about. It seems to only be needed
when forcing symlinks for software installed in what they call the Cellar.
Which seems to be software you've compiled yourself. This should not be
necessary as qt5, as I understand it, is an official brew package, right?

**Comment by muldjord** [comment]
Actually, now that I think about it, why does it need wget? I don't think I
use it anywhere.

**Comment by muldjord** [comment]
Did some further investigating into this. Seems like the "brew link qt5
--force" is needed because it doesn't actually do that itself. Only the Qt4
package does so automaticall, which seems really silly to me. Now the
question remains about wget. What is requiring wget exactly? Thank you.

**Comment by abritinthebay** [comment]
Something in the script I guess? It failed to run it due to that and said "wget not found" so...

**Comment by abritinthebay** [comment]
yup - in the install script it calls:

`wget -N https://github.com/muldjord/skyscraper/archive/${LATEST}.tar.gz`

**Comment by abritinthebay** [comment]
(unrelated random question - what is being used to preview the artwork generated by the xml in that video in the docs? It's great, and I'd love to do that myself 😂)

**Comment by muldjord** [comment]
Ah, of course! I thought I had used curl for the install script.

The "realtime preview" I have in the video demonstrating the artwork xml is
actually just a Skyscraper being run with --unattend repeatedly on a single
rom using the watch -n1 command. I then just open the image it exports and
it gets reloaded every time the new ones is generated. :) You should be
able to do something similar on OSX.

**Comment by muldjord** [comment]
OSX documentation updated and proper credit given. :) Thank you for letting me know.
