### ISSUE TITLE
<marquee> location removed from gamelist.xml when re-scraping with -unattendskip

### ISSUE THREAD

**Issue by ozy24** [muldjord/skyscraper#49]
Hello!

I found a bug with 2.70, reproduced as follows:

Copy artwork.xml.example2 to artwork.xml (to download raw/unaltered images)
Run Skyscraper with `Skyscraper -p arcade --nobrackets --videos --unattendskip -s localdb ` options

All marquee data is correct and present in gamelist.xml ie. `<marquee>/home/pie/retropie/roms/pang.png</marquee>`

Edit a title manually in gamelist.xml and save the file
Re-run `Skyscraper -p arcade --nobrackets --videos --unattendskip -s localdb ` 
 
All `<marquee> `lines are changed to  `<marquee />` with no other data.

Cheers,

Chris

**Comment by muldjord** [comment]
Thank you for noticing, it has been fixed and will be in the next release.
