### ISSUE TITLE
Download box art instead of screenshots by default

### ISSUE THREAD

**Issue by ozy24** [muldjord/skyscraper#51]
Hello again,

I have a preference to use raw box art instead of in-game screenshots for use in EmulationStation.  By default Skyscraper will only download in game screenshots to the "screenshots" subfolder. Is there any way to override this behaviour to download box art to here instead?

Cheers,

Chris

**Comment by muldjord** [comment]
Have you checked the artwork documentation? It's all in there. You need an ```<output type="screenshot" width="640" height="480">``` node with a nested layer that contains the cover artwork. Then just center align that or whatever you want and it'll export a screenshot with the cover artwork. Don't concern yourself with the files in the dbs folders, those are not meant to be changed.

**Comment by ozy24** [comment]
OK I see thank you for the information!

**Comment by ozy24** [comment]
I've just tried this and there seems to be a limitation doing it this way. Arcade covers/flyers are often different dimensions than 640x480 so squeezing them into a box of this size makes for some very ugly viewing. If I leave the height and width out it seems to crop it weirdly instead. Right now i've got around the problem by copying the media/covers folder into the screenshots folder, overwriting the content.

**Comment by muldjord** [comment]
```
<output type="screenshot" width="640" height="480">
    <layer resource="cover" height="480" align="center" valign="middle"/>
</output>
```
Try this. I haven't tested it, but it should work.

**Comment by ozy24** [comment]
That worked great thanks a lot.
