### ISSUE TITLE
Add resulting title tags to textual data definitions

### ISSUE THREAD

**Issue by ozy24** [muldjord/skyscraper#52]
Hi it would be great if you could something like ##RESULTTITLE## tags so a custom resulting title can be imported into the DB.

Resulting titles are not always consistent in Screenscraper (for example some use : as separators and some as -). Sometimes I have got around this by changing the region but it's very reliant on the screenscraper contributors.

**Comment by muldjord** [comment]
Yes, this is something I want to do and has been on my todo list for along time. There's a simple reason I haven't done that yet, but I won't bore you with the details. I will take note and look into it when I get the time.

**Comment by muldjord** [comment]
I've added this now, it will be in 2.7.2. The tag is simply ###TITLE### and works just like the other tags. Remember to also add it to your definitions.dat file.

**Comment by muldjord** [comment]
2.7.2 out now. Please update and test. :)

**Comment by ozy24** [comment]
Maybe I was doing something wrong but I couldn't get this to work. I created definitions.dat as follows:

```
<game>
  <title>###TITLE###</title>
  <description>###DESCRIPTION###</description>
  <developer>###DEVELOPER###</developer>
  <publisher>###PUBLISHER###</publisher>
  <players>###PLAYERS###</players>
  <rating>###RATING###</rating>
  <ages>###AGES###</ages>
  <genre>###TAGS###</genre>
  <releasedate>###RELEASEDATE###</releasedate>
</game>

```
And hsf2.xml in the textual subfolder:

```
<game>
    <title>Hyper Street Fighter 2: The Anniversary Edition</title>
</game>
```

When I run `Skyscraper -p arcade -s import --updatedb /home/pi/RetroPie/roms/arcade/hsf2.zip` I see the below output.

```
#1/1 (T1) ---- Game 'hsf2' found! :) ----
Scraper:        import
Search match:   100 %
Compare title:  'hsf2'
Result title:   '' ()
Platform:       'arcade' ()
Release Date:   '' ()
Developer:      '' ()
Publisher:      '' ()
Players:        '' ()
Ages:           '' ()
Tags:           '' ()
Rating (0-1):   '' ()
Cover:          NO ()
Screenshot:     NO ()
Wheel:          NO ()
Marquee:        NO ()
Video:          NO ()
```

As the result title is "" the new name does not show up.

**Comment by muldjord** [comment]
I think you're doing something wrong. I just tested with that exact setup down to the exact filenames and it gives me the title I have in the xml file just fine.

**Comment by muldjord** [comment]
~/.skyscraper/import/definitions.dat
```
<game>
  <title>###TITLE###</title>
  <description>###DESCRIPTION###</description>
  <developer>###DEVELOPER###</developer>
  <publisher>###PUBLISHER###</publisher>
  <players>###PLAYERS###</players>
  <rating>###RATING###</rating>
  <ages>###AGES###</ages>
  <genre>###TAGS###</genre>
  <releasedate>###RELEASEDATE###</releasedate>
</game>
```
~/.skyscraper/import/textual/hsf2.xml
```
<game>
  <title>Test title</title>
</game>
```
Result
```
#1/1 (T1) ---- Game 'hsf2' found! :) ----
Scraper:        import
Search match:   100 %
Compare title:  'hsf2'
Result title:   'Test title' ()
Platform:       'arcade' ()
Release Date:   '' ()
Developer:      '' ()
Publisher:      '' ()
Players:        '' ()
Ages:           '' ()
Tags:           '' ()
Rating (0-1):   '' ()
Cover:          NO ()
Screenshot:     NO ()
Wheel:          NO ()
Marquee:        NO ()
Video:          NO ()
```

**Comment by muldjord** [comment]
Ah, I see the error now. You have differing indentations on the ```<title>```tag. You need those to be EXACTLY the same for the definitions.dat version and the xml version. So make sure you use spaces in both and the EXACT same number of spaces.

**Comment by muldjord** [comment]
A little background on how this works. The import module looks for a pre-tag and a post-tag. And in-between is the ###TITLE### tag. And this happens per line, including the spaces, not just the tag. That's why you can also make a format of, for examples:
```
title: ###TITLE###
developer: ###DEVELOPER
```
And so on. Skyscraper doesn't actually understand that this is xml, it just reads the text. But for readability I've used xml as the example format, as it's really easy to decipher for humans.

So in this particular case, your pre-tag is ```<title>``` with 2 spaces in front of it but in the xml file you have ```<title>``` with 4 spaces in front of it. In other words, it's not a match and doesn't get recognized.

**Comment by muldjord** [comment]
What I always do myself, is to copy the definitions.dat into another file, and insert the data there. That way I am sure the format is correct as I just copied it.

**Comment by muldjord** [comment]
Maybe it was a tab instead of spaces. Looks the same, but as characters it's entirely different.

You're welcome, enjoy! :)

**Comment by muldjord** [comment]
Yes, you need to add the ...
```
  <order type="title">
    <source>import</source>
  </order>
```
... nodes to the ```~/.skyscraper/dbs/[platform]/priorities.xml``` for that resource. It's not in there by default as it's new :) I've added this to new installations, but as you have used it before, it won't overwrite the one you have with the new default one. Take a look at the example here: ```~/.skyscraper/dbs/priorities.xml.example``` and check out the title node

**Comment by ozy24** [comment]
I added that line to priorities.xml and ran the -s import command. This fixed the names for the roms in the xml files but it also changed the names of other roms (seemingly at random). For example, the below game did not have an xml file in the import folder but the name was changed by the import scraper. 

```
#43/43 (T4) ---- Game 'wof' found! :) ----
Scraper:        localdb
Search match:   100 %
Compare title:  'Warriors of Fate'
Result title:   'wof' (import) <-----
Platform:       'arcade' (import)
Release Date:   '1992-01-01' (screenscraper)
Developer:      'Capcom' (screenscraper)
Publisher:      'Capcom' (screenscraper)
Players:        '3' (screenscraper)
Ages:           '' ()
Tags:           'Beat'em Up' (screenscraper)
Rating (0-1):   '0.6' (screenscraper)
Cover:          YES (import)
Screenshot:     YES (import)
Wheel:          YES (screenscraper)
Marquee:        YES (screenscraper)
Video:          YES (screenscraper)

```

As soon as I remove the title line from the priorities line and re-scrape the name is correct again.

**Comment by muldjord** [comment]
Ah, yes, I think I know why it does this. This happens when importing screenshots for any game. Not only does it import the screenshot, but it also set the title as the file name if none is provided in textual. And that title is also saved. I will see if I can get around this and fix it in 2.7.3. Thanks for reporting it.

**Comment by muldjord** [comment]
2.7.3 out now with this fixed, please update and test. There is a small caveat. Since the dummy titles are already in your localdb cache, you'll need to either remove them manually from the db.xml files for each platform, or purge all of the titles inserted by 'import' using the '--purgedb' option like so:
```
$ Skyscraper -p [platform] --purgedb m:import,t:title
```
The caveat being that this will also remove the correct titles you imported earlier, so you'll have to re-import those from your xml files.

**Comment by ozy24** [comment]
That was quick. :)

I'll give this a go a bit later and come back to you with the results.

**Comment by muldjord** [comment]
Awesome, you're welcome! :)

**Comment by markxma1** [comment]
Hi, I try to add some missing description on raspberry pi with import. covers and screenshots works, but marquees it not on the image and it don't load textual information.

here is copy of textual file (have tried with and without ###, Filename: Final Fantasy III.txt, Game name: Final Fantasy III.iso Marquee Name: Final Fantasy III.png):

----------------------------
```
Title      : Final Fantasy III
Description: First released in 1990, FINAL FANTASY III was the first title in the FINAL FANTASY series to become a million-seller, establishing once and for all that Square Enix&apos;s classic RPG saga was here to stay. This full 3D remake, originally released in 2006 for the Nintendo DS, duplicated the original&apos;s success by also selling over a million copies worldwide. FINAL FANTASY III was a hallmark of innovation for the entire series, introducing the job system, which lets characters change classes at any time, as well as the ability to summon powerful creatures such as Shiva and Bahamut. In FINAL FANTASY III, players take control of four ordinary youths when darkness falls and the land is robbed of light. Chosen as defenders of the crystals, they journey far and wide to obtain the strength needed to banish the darkness and usher in a new era of light for the world. The Android edition of FINAL FANTASY III features new and improved 3D visuals and story sequences not included in the original Nintendo DS version of the remake. Touch controls have also been implemented for compatibility with today&apos;s smartphones and other mobile devices. Additionally, the Job Mastery Cards, unlocked when a character obtains the maximum level in a job, now feature new and improved art.
Developer  : Squaresoft
Publisher  : Squaresoft
Players    : 1
Rating     : 3.4
Ages       : 12
Genre      : Role-playing
Date       : 1994

```
--------------------------
Out:
Search match:   100 %
Compare title:  'Final Fantasy III'
Result title:   '' ()
Platform:       'psx' ()
Release Date:   '' ()
Developer:      '' ()
Publisher:      '' ()
Players:        '' ()
Ages:           '' ()
Tags:           '' ()
Rating (0-1):   '' ()
Cover:          YES ()
Screenshot:     YES ()
Wheel:          NO ()
Marquee:        YES ()
Video:          NO ()

[Final Fantasy III.txt](https://github.com/muldjord/skyscraper/files/2896136/Final.Fantasy.III.txt)

have tried with RetroPie menu and with 
./opt/retropie/supplementary/skyscraper/Skyscraper -p psx -s import '/home/pi/RetroPie/roms/psx/Final Fantasy III.iso' 
(--updatedb says Unknown option 'updatedb'.)

**Comment by muldjord** [comment]
Please read the import and artwork documentaton. You have probably forgotten to create a definitions.dat. Your marquees are imported just fine, but you need to make use of them in the artwork compositor.

If you have further questions, please use reddit or the retropie forums for them, thanks. This is only for bugs or feature requests.

**Comment by markxma1** [comment]
thank you for help. I have wrong understand the definitions part (thought it is some example for text.) and because  it saves all game names images in marquees I thought  marquees are "game names images". In artwork was used the wheel. I can steel not finde the definition of marquees and wheel ( wheel  = car wheel so I thought  CD print)
