### ISSUE TITLE
Unable To Import Screenshots

### ISSUE THREAD

**Issue by Squydy** [muldjord/skyscraper#53]
I've recently update my retropie and seeing what's new. I found the scraper in the regular menu no longer functions. I did a quick search an found this was a favorite of the community. I really like as well it works wonders, but some of my games come up without any screenshots. I have been trying to import them following the documentation and through other trail and error ways and they've all failed. I honestly don't know what I'm doing wrong if someone could point me in the right direction to fix this problem it'd be much appreciated. Thank you!

**Comment by muldjord** [comment]
Please try asking these general questions on the sub-reddit (https://www.reddit.com/r/RetroPie/) or on the RetroPie forums (https://retropie.org.uk/forum/topic/11826/versatile-c-game-scraper-skyscraper/718). It's a bit much for me to try and answer all these myself.

What you need to do is copy your desired screenshot to the ```~/.skyscraper/import/screenshots``` folder. The filename of the screenshot must match the base name of your rom EXACTLY. Example: 'Bubble Bobble.nes' will import images with a filename of 'Bubble Bobble.jpg' or 'Bubble Bobble.png' or other image formats.

Then run the command:
```
$ Skyscraper -p [platform] -s import --refresh
```
And lastly, run:
```
$ Skyscraper -p [platform]
```
Which will combine all of your cached data, including the screenshots. And you're done!

**Comment by muldjord** [comment]
I see you've already asked this on the subreddit. It works, I know it does (I just used it yesterday), so I'm guessing there's something with how you name your files or where you place them. It is imperative that you have the exact same base names, otherwise it won't find them.

**Comment by Squydy** [comment]
Yes I did post in the subreddit and that's why I don't understand what I'm doing wrong. I have followed all of your instructions, which are very well documented, but I can't seem to be able to import anything. I just reinstalled retropie again so I'll try it out again.

**Comment by Squydy** [comment]
After cursing outy retropie and telling it what a piece of garbage it is, I reinstalled retropie. I still couldn't import anything but now everything works. It just works and I don't know why or how. So thank you for this wonderful tool and sorry to bother you.
