### ISSUE TITLE
default background color for png alpha channel

### ISSUE THREAD

**Issue by chipsnblip** [muldjord/skyscraper#54]
i noticed someone was having an issue with screenscraper's artwork ([link to reddit thread](https://old.reddit.com/r/RetroPie/comments/9djmye/runcommand_rom_launch_art_is_working_butpng_files/)) but only later did i notice they were referring to *screen*scraper, not *sky*scraper.  :oops:

but it got me thinking, maybe having Skyscraper setting the alpha channel's background color to black wouldn't be such a bad idea after all (instead of the default #C0C0C0).  or would this be better handled within the artwork.xml?

**Comment by muldjord** [comment]
Hi man, thank you for spreading the word, as always, I appreciate that :)

Setting the color for the alpha in PNG's is only really relevant for indexed PNG's, as they have a binary alpha channel (either 100% transparent or 100% opaque) and so needs a color to "fade to" when reaching the alpha borders. 24bit PNG's don't have this issue, as they have 255 levels of alpha per pixel and just blends to whatever background color is behind the image. For indexed PNG's the "fade to alpha" color is set on export time (for instance in Gimp) and hardcoded into the pixels so I can't really change it, without having the original non-indexed image (this is the exact issue 'ruffdaddysmooth' has with the Gimp example he posted). With that said, I haven't once seen any of the sources return an indexed PNG with alpha as they aren't really used anymore anywhere, probably because of the binary alpha issue (it looks really, really bad, no matter what fade color you set). If they are, they need to be fixed at the source as I don't have the required pixel info to do so. :)

**Comment by muldjord** [comment]
Or do you mean replacing the alpha entirely with black so it becomes non-transparent?

**Comment by chipsnblip** [comment]
sorry for any confusion, as i don't really understand the underlying technical aspects of what it is i'm asking.

Skyscraper by default output images that have a white 'canvas' which is 100% transparent.  at first i thought it was #C0C0C0, but it is in fact white; with image magick, one can view this info using `identify -verbose artwork.png | egrep 'Background color'`. and this bg color is only visible when the image is displayed using fbi or fim etc, but this color is never shown when viewing the image in most modern viewers/editors.

as an extreme example, the bg color can be changed with imagemagick's `convert input.png -background '#ef6bff' output.png`

before:
https://i.imgur.com/J4FLeKE.png
after:
https://i.imgur.com/5P2O9DR.png

both look exactly the same with fully transparent backgrounds until viewed in fbi/fim/etc, which exposes this bg color:

screenshot:
https://i.imgur.com/BAAaI3Q.png

so i propose (if at all possible) that Skyscraper somehow sets the color to black by default in all exported artwork with transparency. that way, in the event that the artwork Skyscraper generates were to be used as [custom launching images](https://github.com/RetroPie/RetroPie-Setup/wiki/runcommand#adding-custom-launching-images) or otherwise, it would already have a black background and therefore be seemlessly integrated.

either way, it's not a big deal, since converting the bg color can be easily scripted.  in fact, the more i write about it, the more petty it seems :)

i hope some of this made sense.  maybe i'm missing something obvious, if so please disregard all the noise.

always happy to help spread the word about Skyscraper, this really is an amazing project.

**Comment by muldjord** [comment]
I had no idea non-indexed PNG's had a background color, but I guess it makes sense if it is rendered without anything below it. I have found a way to do this, but I am unsure if I wish to add this, as it will require that I do this for all images and I am unsure if the method I've found will cause other issues that I can't really figure out. And as it doesn't seem to be a problem under normal circumstances, it does seem a bit excessive to do this as it will also slow down the composition process inside Skyscraper. Not by much, but still... So I'm not diregarding the idea, it's just that it seems to be a borderline case.

**Comment by chipsnblip** [comment]
understood, and thanks. after all, it's been an interesting topic of discussion.
this can be safely filed under the "if it's not broken, don't fix it" category :)

**Comment by muldjord** [comment]
I'm actually looking into this as I write after all. :D So stay tuned! If I can find a fix I'm happy with, I'll include it. I've tried coloring it with RGBA 0, 0, 0, 0, which is black + 100% alpha. But it still goes grey when I check it out in my browser... If I can't figure out why it does that, I can't do it. :( But we'll see. Currently investigating.

EDIT: It seems that no matter what color I fill the image with, it just keeps saying "Background color: White" with identify. So it seems like this is a PNG specific thing that is being set upon saving the image. And Qt doesn't seem to support any way of setting that manually. :S It doesn't seem related to the actual values of the pixels. It's more of an attribute in the PNG that I don't have access to.

**Comment by muldjord** [comment]
I just tried setting this on a bitlevel, and it still doesn't change the background color. So it's clearly an attribute in the PNG header. So I'll need to look into manually editing the header. This is turning into an interesting little project.

**Comment by muldjord** [comment]
Yes, as I expected, it's called the bKGB chunk and for 24bit images contain an RGB value for the background color. Qt simply saves this as #FFFFFF by default and has no way of changing it. But if I can save the image to an internal buffer before saving it, I might be able to change it...

**Comment by muldjord** [comment]
So I've looked into this further, and it seems the "setBackgroundColor" isn't properly implemented where I need it so the solution I had hoped would work, won't. So I'm gonna close this for now.
