### ISSUE TITLE
dbFolder config.ini setting ignored

### ISSUE THREAD

**Issue by HumanRob** [muldjord/skyscraper#55]
**Describe the bug**
As the dbs folder uses a lot of space, I'd like to store it on a usb hard drive connected to my pi. I've moved the contents of the dbs folder to the hard drive (/media/usb0/skyscraper/dbs). If I specify the dbs folder via the command line '-d /media/usb0/skyscraper/dbs' , skyscraper uses it as expected. However if I set this in the config.ini file the default dbs folder is used instead. The file is called config.ini and exists in ~/.skyscraper/ and the only uncommented lines are as follows:
dbFolder="/media/usb0/skyscraper/dbs"
importFolder="/media/usb0/skyscraper/import"

I haven't explicitly told Skyscraper to use this config.ini via the command line but as I understand it this isn't necessary as the config.ini file is stored in the default location.

**To Reproduce**
Set the dbFolder in config.ini to point to an external folder. 
Run skyscraper in simple mode.
The default dbs folder is used

**Special circumstances**
The only thing I can think of that's unusual is that the dbs folder is stored on a usb hard drive. However, skyscraper doesn't seem to have a problem with this when told to use the folder using the command line options.

**Technical information**
 - Skyscraper version: 2.7.3
 - Internet connection: wifi
 - OS: Retropie
 - OS Version 4.4

**Comment by muldjord** [comment]
These settings cant exist outside sections in tje config.ini. you need to
also uncomment the [main] line, then it'll work

**Comment by HumanRob** [comment]
My mistake, I didn't realize that. Thank you, it works fine now!

**Comment by muldjord** [comment]
You're welcome :)
