### ISSUE TITLE
More advanced artwork sizing?

### ISSUE THREAD

**Issue by Vynce** [muldjord/skyscraper#59]
Providing a width and a height for a layer stretches the resource to fill that space. I don't think that looks good with wheel images. Specifying just the width or height maintains the aspect ratio of the resource, but I'm still running into issues with various resources ending up too big or too small due to very different aspect ratios.

For example, if I limit the wheel height to 120:
```
<?xml version="1.0" encoding="UTF-8"?>
<artwork>
  <output type="screenshot" width="640" height="480">
    <layer resource="screenshot" height="420" align="center" valign="bottom">
      <rounded radius="25"/>
      <stroke width="5"/>
    </layer>
    <layer resource="wheel" height="120" align="center">
      <shadow distance="5" softness="3" opacity="80"/>
    </layer>
  </output>
</artwork>
```
very wide resources run off the sides:
![wide wheel img](https://user-images.githubusercontent.com/377567/45731716-81b2b680-bb9e-11e8-803f-72314d8a51f0.png)

but narrow resources end up tiny:
![tiny wheel img](https://user-images.githubusercontent.com/377567/45732337-79a84600-bba1-11e8-9fd8-f29144b72356.png)

If I limit the wheel width to 400 instead:
```
<?xml version="1.0" encoding="UTF-8"?>
<artwork>
  <output type="screenshot" width="640" height="480">
    <layer resource="screenshot" height="420" align="center" valign="bottom">
      <rounded radius="25"/>
      <stroke width="5"/>
    </layer>
    <layer resource="wheel" width="400" align="center">
      <shadow distance="5" softness="3" opacity="80"/>
    </layer>
  </output>
</artwork>
```
narrower resources fill up most of the vertical space and look ridiculous:
![narrow wheel img](https://user-images.githubusercontent.com/377567/45731934-9b083280-bb9f-11e8-9412-7836e25cb34a.png)

One option that might help is to add an attribute to maintain a fixed aspect ratio even when a width **and** height are specified and then fit the resource within that bounding box. Playing around with sizes a bit, I'm not sure that's really going to solve the issue, but might help a bit. This could at least prevent wide resources from scaling off the sides of the output like in the first example.

Another option that could be worth a try is specifying an area instead of a width/height. If you specify an area of 50,000 pixels, a narrower resource might be scaled to 200x250, whereas a wider resource might be scaled to 500x100. This mode would have to maintain the aspect ratio to work. It might take a bit of testing to see if it produces good results in most cases, but it feels like it should.

**Comment by muldjord** [comment]
I somewhat like the idea of the "area" solution. I'll take note of it.

**Comment by muldjord** [comment]
I've now implemented a 'mpixels' attribute for both the output and layer nodes in artwork.xml. It will resize according to a desired number of megapixels instead of width or height. Please update and test if you get the time. Details can be found in the artwork documentation for the relevant nodes: https://github.com/muldjord/skyscraper/blob/master/ARTWORK.md#mpixels-attribute-from-v278-optional-1
