### ISSUE TITLE
bad_alloc error with specific game

### ISSUE THREAD

**Issue by richarnd** [muldjord/skyscraper#60]
I've got a single ScummVM game that will not scrape. When I try to scrape "The Black Cauldron" (bc.scummvm), Skyscraper exits with an error of:

`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
`
All other games and systems seem to work fine. I was also able to scrape this game in the past without any problems. I get the error whether I use the localdb only, screenscraper, or thegamesdb. Forcing a refresh (--refresh) of the local db doesn't help. Purging the whole scummvm system or even just deleting the scummvm folder from the local db doesn't fix it either!

Initially I thought there might be a problem with some of the media files on screenscraper or in my localdb for this game. There was an earlier bug report of a super-large image for a specific game causing a problem. But this doesn't seem to be the case here. I don't understand why I get the error for every scraping module.

I've even tried swapping in a different Raspberry Pi to make sure I didn't have a hardware problem. No change.

It's not a major issue - I can temporarily delete this game, scrape the system, then add it manually. But it's very weird.

Running Skyscraper v2.7.4 on Retropie 4.4, emulationstation frontend.

**Comment by muldjord** [comment]
Thank you for the detailed description. I've just added this game to my own Pi and tried scraping it using the same filename. It scrapes fine (Skyscraper 2.7.4) with both openretro, thegamesdb and screenscraper. So I can't reproduce the error. bad_alloc's happen when Skyscraper tries to allocate memory but can't (Pi is probably out of memory). You probably guessed that already.

The fact that it happens with all modules tells me that it probably isn't related to the actual data you recieve from the modules, but rather something else.

My only idea at this point is to check your SD card (did you also swap that between testing with different Pi's?). It's a longshot as it seems to be memory related and not slow-storage related, but I can't come up with anything else.

**Comment by richarnd** [comment]
Tried a new SD card (backed up the image and wrote to a new card) - same result. It's very weird. 

Another thing I can rule out is the file itself. *.scummvm files are just a line of plain text, but I suppose its still possible for one to be corrupted. I copied the single line into a new file, renamed it "bc.scummvm", and got the same result.

You're very likely right that the problem is specific to my setup but it's still puzzling!

**Comment by richarnd** [comment]
File, in case it's useful:

[bc.zip](https://github.com/muldjord/skyscraper/files/2403581/bc.zip)

**Comment by muldjord** [comment]
Just tried putting that file in instead of my own and rescraped my 'scummvm' games. It still works just fine... This is seriously weird. I can't come up with a single thing that could cause this for you knowing what you've tried already. I'd really like to figure this out in case it IS a Skyscraper bug.
