### ISSUE TITLE
Retropie psx scraping problem

### ISSUE THREAD

**Issue by Deddao** [muldjord/skyscraper#61]
**Describe the bug**
Skyscraper can't scrape ONLY psx folder roms. Other platforms are correctly scraped

**To Reproduce**
Using Skyscraper in simple mode, it can't scrape only "psx" platform. The "emulationstation" "psx" and question phase is ok, The script is created, but when you run it the system gave this message: "No resources for this platform found in the local database cache"
This doesn't happen if you want to scrape any other platform (Nes, Snes, Mame etc. etc.), ONLY with psx.
Of course psx roms are already in the psx folder
![img_20180921_144041](https://user-images.githubusercontent.com/43472036/45882275-f4de4780-bdad-11e8-8ccf-7cb10a8a00ea.jpg)

**Special circumstances**
Is your system set up in any special manner that could interfere with how Skyscraper works?
No, no Retropie custom image 

**Technical information**
 - Skyscraper version: 2.7.4
 - Internet connection: Wi-Fi
 - OS: Retropie
 - OS Version 4.4.2

**Additional context**
None

**Comment by muldjord** [comment]
Yes, I actually just fixed this for the next release. Here's a workaround until 2.7.5 is released, run the following commands one after the other:
```
$ Skyscraper -p psx -s thegamesdb
$ Skyscraper -p psx -s screenscraper
$ Skyscraper -p psx --nobrackets
```
Let me know how it goes.

**Comment by Deddao** [comment]
Working good, thank you so much
