### ISSUE TITLE
Q*Bert rom not scraping

### ISSUE THREAD

**Issue by ozy24** [muldjord/skyscraper#62]
Hello,

I've had great success with Skyscraper scraping roms but it's unable to find a match for qbert.zip from either MAME 2003 or 2010 no matter what options I set. Weirdly i've tried it from both Screenscraper and Gamesdb with no success on either.

The game is very popular and an entry exists in the Screenscraper database with the same filename but it cannot find it which makes me think it might be a bug..

Skyscraper -p gamesdb --nobrackets --videos -s screenscraper --updatedb /home/pi/RetroPie/roms/arcade/qbert.zip

https://screenscraper.fr/gameinfos.php?plateforme=209&gameid=172110

Running Skyscraper 2.7.5

Regards,

Chris

**Comment by muldjord** [comment]
I assume you made a mistake in the above command. '-p gamesdb' makes no sense to Skyscraper and will certainly not work. :)

Try checking out the new '--query' option. That might help. Read more here: https://github.com/muldjord/skyscraper/releases/tag/2.7.5

**Comment by ozy24** [comment]
Oops, yes that was the wrong entry from console history. :)

It should have been

Skyscraper -p arcade --nobrackets --videos -s screenscraper --updatedb /home/pi/RetroPie/roms/arcade/qbert.zip

I'll check out the query option and come back to you if still an issue..
