### ISSUE TITLE
[Request] Preserve ES metadata tags in the generated gamelists

### ISSUE THREAD

**Issue by cmitu** [muldjord/skyscraper#64]
Emulationstation has a number of tags not related to the metadata/boxart which would be nice to be preserved by Skyscraper when writing the gamelist entries.

 * **Favorite** - Game/ROM has been marked as favorite. Useful to populate the **Favorite** collection.
 * **Hidden** - Game/Rom should be hidden (only works in Kiosk UIMode [1] )
 * **Lastplayed**/ **Playcount**  - used in the **Last Played** collection
 * **Kidgame** - Game/ROM is kid friendly (only has effect in Kid UIMode [1] ). I know Skyscraper generates a kidmode tag when the appropriate age info can be scraped, but if possible to keep it if already set (and no age info is applied).

 I've seen users (and noticed it myself) happen to scrape after adding favorites and then noticing they're gone [2]. The last played date also makes the **Last Played** (automatic) collection lose some entries.  
 
 Note that this happens also with Steven Selph's scraper, I think only the internal ES scraper keeps these medatada tags as they have been set.

 You can find a list of all ES supported metadata tags at
https://github.com/RetroPie/EmulationStation/blob/8c0b00c490a7b315e64e4d499d7a8aee8cc9aa07/es-app/src/MetaData.cpp#L8-L27 .

[1]: Emulationstation UI Modes - https://retropie.org.uk/docs/Child-friendly-EmulationStation/#ui-modes
[2]
  * https://reddit.com/r/RetroPie/comments/9nx4er/favorites_keep_getting_wiped_frustrated/
  * https://retropie.org.uk/forum/topic/15990/all-scraped-data-and-games-in-favorite-list-are-gone-oo/

**Comment by muldjord** [comment]
That is actually a huge issue. I had no idea ES keeps that data in the gamelist.xml itself. A lot of work is needed for Skyscraper to handle this as I'd have to make an internal mapping of each piece of information before even starting the scraping. I currently do this to enable skipping existing entries, but it is a very dumb implementation that doesn't really work for this situation.

I'll let it brew for a bit and figure out if I can implement it in a way that makes sense. No promises, I might not make it at all if it proves too much work.

**Comment by cmitu** [comment]
It's not that huge of a deal. Other scrapers work similarly (i.e. generating a full game entry on scraping) and I don't think anyone has been so aggravated so far to request this change in behavior.
IMHO you could make a decision IF you'll want to implement this at some point and then just leave this issue open as a reminder until you can reconsider for implementation (a long-term plan).

**Comment by muldjord** [comment]
I've been pondering this for a few hours while rehearsing with my band and I actually think I could do some useful stuff with an implementation I have in mind. If I do make this implementation, I could also implement the option to only change certain types in the gamelist.xml. For instance, if you only want to update the "developer" for any entry, you could do that, and the rest would be left alone.

But yeah, it's still a lot of work, but now that I think of the possibilities with this it makes more sense to me to spend time on it.

I'll leave this open.

**Comment by muldjord** [comment]
I've managed to find a decent way of doing this. It will preserve metadata from the original gamelist.xml unless new data is incoming from the scraping run. So 'hidden' and 'favorite' will always be preserved (since Skyscraper doesn't scrape this, it will just be copied over from the old gamelist.xml). Other metadata such as 'players' and 'developer' will also be preserved, but ONLY if the scraping run doesn't provide a result for it.

I'm almost done implementing it and it will be included in the next release. I just need to test it some more. It can be tested on the master branch if anyone is curious.

**Comment by cmitu** [comment]
@muldjord seems to work fine, just tested it briefly and it preserves the `favorite` , `hidden` and `lastplayed`.

**Comment by muldjord** [comment]
Thank you for testing!

**Comment by muldjord** [comment]
Now also preserves AttractMode metadata.

**Comment by muldjord** [comment]
2.8.0 out now with this implemented

**Comment by cmitu** [comment]
Thank you ! I guess we can close this issue.
