### ISSUE TITLE
No images in Wheel or Boxart

### ISSUE THREAD

**Issue by mansanram** [muldjord/skyscraper#65]
Boxart and wheel images are not transferred to their respective folders ($Home/RetroPie/roms/*platform*/media/wheel and /boxart), but are present in localdb. Running in simple mode populates the localdb folders fine, but neither running in simple mode, manual mode, or attempting to import from localdb gives me any files in the media folders.

Initially I run "Skyscraper" no options, after that I have tried "Skyscraper -p gba -s localdb" as well as running "Skyscraper -p gba -s localdb --noscreenshots --nomarquees" but no joy. I have appended a ".bkp" to the media folder to allow Skyscraper to create the directory structure, but still no wheel or boxart images. I get no indication from the terminal that anything is wrong. Not even when running with "--verbosity 2":

```
---- Scraping run completed! YAY! ----
Writing 10415 (0 new) resources to local database, please wait... Success!
Now writing '/home/masr/RetroPie/roms/gba/gamelist.xml'... Success!!!

---- And here are some neat stats :) ----
Total completion time: 00:01:27

Average search match: 100%
Average entry completeness: 80%

Total number of games: 932
Successfully scraped games: 903
Skipped games: 29 (Filenames saved to '~/.skyscraper/skipped-localdb.txt')
```

 - Skyscraper version: 2.7.7
 - Internet connection: Fiber 25/25
 - OS: Antergos x64

**Comment by muldjord** [comment]
This is expected. The default artwork.xml file for Skyscraper does not export either wheel or covers by themselves but instead composits them into a screenshot. You can customize this completely (and export wheel and covers if you want to) by following the documentation here: https://github.com/muldjord/skyscraper/blob/master/ARTWORK.md

**Comment by muldjord** [comment]
Decided to reopen for others to see. Now that Skyscraper is part of RetroPie I expect a lot of questions in regards to artwork.

**Comment by mansanram** [comment]
Ahhhh! I only skimmed the artwork readme and thought it dealt with
customizing the artwork. Thanks for the info and the great tool 👍🏼
