### ISSUE TITLE
TheGamesDB has trouble matching some games

### ISSUE THREAD

**Issue by Vynce** [muldjord/skyscraper#67]
Scraping with `Skyscraper -p genesis -s thegamesdb --pretend` results in some skipped games.
```
'Double Dragon (USA, Europe) (Unl)', No returned matches
'NBA Jam (USA, Europe) (v1.1)', Closest match was 'NBA Jam Tournament Edition' at 26%
'Sonic The Hedgehog (USA, Europe)', No returned matches
```
```
$ cat .skyscraper/config.ini
[main]
unpack="true"
videos="true"
brackets="false"
unattend="true"
region="us"
```
If I try to help it find a match using the `--query` argument, it still only seems to find NBA Jam Tournament Edition:
```
Skyscraper -p genesis -s thegamesdb --pretend --query 'NBA Jam' '/home/pi/RetroPie/roms/megadrive/NBA Jam (USA, Europe) (v1.1).zip'
```
Searching by hand, it definitely exists though:
https://thegamesdb.net/search.php?name=nba+jam&platform_id%5B%5D=18

Same thing with Sonic the Hedgehog:
https://thegamesdb.net/search.php?name=Sonic+The+Hedgehog&platform_id%5B%5D=18

I wonder if Skyscraper is getting confused because searching for "NBA Jam" returns "**NBA Jam**" and "**NBA Jam** Tournament Edition"? Similarly, searching for "Sonic the Hedgehog" returns a whole list of games that all start with the same prefix:
- Sonic the Hedgehog 2
- Sonic the Hedgehog 2 (Beta)
- Sonic the Hedgehog 3
- Sonic the Hedgehog Megamix
- Sonic the Hedgehog

I see the same thing with some SNES games:
```
'Harvest Moon (USA)', No returned matches
'Mega Man X (USA) (Rev 1)', No returned matches
'Samurai Shodown (USA)', No returned matches
```
The Harvest Moon failure is really weird since there's only a single match on the website: https://thegamesdb.net/search.php?name=harvest+moon&platform_id%5B%5D=6
```
Skyscraper -p snes -s thegamesdb --pretend --query 'Harvest Moon' '/home/pi/RetroPie/roms/snes/Harvest Moon (USA).zip'
```
and NES:
```
'Bubble Bobble (USA)', No returned matches
'Castlevania (USA) (Rev A)', No returned matches
'Final Fantasy (USA)', No returned matches
'Legend of Zelda, The (USA) (Rev A)', No returned matches
'Kung Fu (Japan, USA)', No returned matches
'Lode Runner (USA)', Closest match was 'Championship Lode Runner' at 45%
'Mega Man (USA)', No returned matches
'Metal Gear (USA)', No returned matches
'Micro Machines (USA) (Unl)', No returned matches
'Ninja Gaiden (USA)', No returned matches
```
I tried manual queries with all of these.

I'm using Skyscraper 2.7.8.

**Comment by muldjord** [comment]
Could you try with 'megadrive' instead?

**Comment by muldjord** [comment]
Something is seriously wrong with the github cache servers right now. This issue keeps going in and out of existence, half the time giving me a 404.

Anyways, I've looked into this, and as I expected it is because of how thegamesdb handles searching and the returned results. When Skyscraper searches for a game, it doesn't search on a particular platform. And since thegamesdb only returns a few results per page, it simply doesn't find a match among the returned entries.

You can try making it work better by sending the platform id with the query aswell. I can't remember how it works, try checking their API subsite.

**Comment by muldjord** [comment]
And now my old answer is back, fantastic. God dammit github, fix your cache, this is annoying as hell!

**Comment by Vynce** [comment]
That worked. Thanks for the hint 🍺😄
```
Skyscraper -p snes -s thegamesdb --pretend --query 'Harvest Moon&filter[platform]=6' '/home/pi/RetroPie/roms/snes/Harvest Moon (USA).zip'
Skyscraper -p genesis -s thegamesdb --pretend --query 'NBA Jam&filter[platform]=18' '/home/pi/RetroPie/roms/megadrive/NBA Jam (USA, Europe) (v1.1).zip'
```
https://api.thegamesdb.net/#/Games/GamesByGameName

Unfortunately Sonic the Hedgehog got matched incorrectly:
```
$ Skyscraper -p genesis -s thegamesdb --pretend --query 'Sonic the Hedgehog&filter[platform]=18' '/home/pi/RetroPie/roms/genesis/Sonic The Hedgehog (USA, Europe).zip'
Search match:   100 %
Compare title:  'Sonic The Hedgehog'
Result title:   'Sonic & Knuckles + Sonic the Hedgehog' ()
```
I'll probably just modify the Skyscraper source temporarily to search by GameID instead so I can get it to match that one correctly. Everything else worked perfectly.
