### ISSUE TITLE
ROMS on retropie-mount - Duplicated entries

### ISSUE THREAD

**Issue by CsCt00** [muldjord/skyscraper#68]
Hi Muldjord
Before going on, I want to thank you for this awesome scraper, I really love it.
My issue is the following, I have my roms on an external HDD with the retropie-mount method, and whenever I scrap for a system, I get all the media on the USB Drive  as also on the SD card. I've been deleting the media for the .skyscraper folder on the SD card after scraping, and the media works excelent just from the HDD. I wanted to know if there is any way to scrape directly to the External HDD without also being copied to the SD. I tried several several options based on the README file, but with no luck.

Thanks in advance! and keep up this awesome work!

**Comment by muldjord** [comment]
If you want to disable the cache entirely you can do so with '--nolocaldb' but I would strongly advice against that as the cache is really useful for rescrapings. Instead, I would recommend setting the local cache folder to also be on your external HDD, either by setting '-d [base db folder]' or by adding it to the [main] section of the ```~/.skyscraper/config.ini``` file. That way it won't fill up your SD card.

**Comment by CsCt00** [comment]
Thanks so much for your response, that worked like charm!
