### ISSUE TITLE
Removing extra media from deleted roms

### ISSUE THREAD

**Issue by mettamatt** [muldjord/skyscraper#69]
How would I go about cleaning up the media assets (videos, screenshots) when I delete roms I no longer wish to keep? I know how to update the Skyscraper local database with the `--cleandb` parameter, but how I do clean up the media assets Skyscraper moved into place?

**Comment by muldjord** [comment]
This is a feature i want to implement but haven't gotten around to yet.
Basically it will at some point be possible to do this with '--purgedb'.
But at the moment you can't.

**Comment by mettamatt** [comment]
Ah, okay. Good to know. I wrote a one-off bash script for my own cleanup purposes. I'll leave it here for reference with the caveat that I'm not a programmer for my day job. 

https://gist.github.com/mettamatt/c3eade40db081f10df611223dcc326e4

**Comment by muldjord** [comment]
Just had a look at your script and I think I misunderstood your original request. I thought you meant how to clean up the cache so it only contains media relevant to your current romset. This is a feature I want to implement at some point.

Concerning what files are in your roms folder, this is not something Skyscraper will clean up. That is basically up to the user, as it is with any scraper. I really don't want to go around messing with the user files like that as I could end up deleting files that the user has placed there manually.

So a script like the one you created is useful for this. But please note that "vacuuming" the cache will be possible at some point when I get around to it. :)

**Comment by mettamatt** [comment]
That makes a lot of sense that it's probably not a good idea for Skyscraper to be deleting user data in the roms folder. Feel free to close this ticket.
