### ISSUE TITLE
Please add LHA archive support for AMIGA with Amiberry (Retropie)

### ISSUE THREAD

**Issue by Elotoha** [muldjord/skyscraper#70]
Amiberry is an AMIGA emulator. It requires LHA archive for each ROM in order to work properly (not ZIP).
Please add support for not ignoring, and scraping, LHA archives.

**Comment by Elotoha** [comment]
Thank you for your quick answer.   :-)
When I scrap it seems nothing is done, because it's very quick.  
So I thought that "*.lha" files were simply ignored, and that it would be necessary to decompress these archives to compute ROM CRC to be able to find corresponding scrape data. 
But perhaps I didn't understand scraping method correctly.

**Comment by muldjord** [comment]
They are scraped pretty well if you use the following commands one after the other:
```
$ Skyscraper -p amiga -s openretro
$ Skyscraper -p amiga -s screenscraper
$ Skyscraper -p amiga
```
But don't expect great results until the LHA's are better supported in the source databases. As of right now screenscraper only has about 500 of them supported and openretro is having limitation issues that make most games in general scrape badly. But try it out and see how you fare. Good luck!

**Comment by Elotoha** [comment]
I added support for LHA to Universal XML Scraper yesterday (made a Pull Request): Lha archives were ignored and couldn't be uncompressed. That's done now.
But not all games are found, and I think it would be better to improve a scraper that handles many sources like yours.

For source databases, I didn't expect source databases to know each "LHA archive" because I've converted ZIP to LHA myself to make Amiberry work with them, so LHA CRC logically can't be found, but I thought CRC of files inside LHA archive could be found...

Thank you for commands, I'll try this and I'll search further because I certainly didn't understand every aspect of scraping !

**Comment by muldjord** [comment]
It's not the XML Scraper I am talking about. It's the database itself. Not many of the LHA checksums are in their database yet.

But you are out of luck if you are creating the LHA's yourself. I would get the retroplay lha's as they are the most complete and official ones.
