### ISSUE TITLE
[Artwork][XML] - <GameBox /> does nothing

### ISSUE THREAD

**Issue by Flodding** [muldjord/skyscraper#72]
Tryed the Artwork.xml.example to create artwork, but `<gamebox />` doesnt show up anything.

rest works like a charm... 

**Technical information**
 - Skyscraper version: 2.8.1
 - Internet connection: wifi
 - OS: RetroPie (actual version)

**Comment by Flodding** [comment]
Hey ! 
I am trying to use your program.

I downloaded and compiled it correctly. After compile i had a folder named "skyscraper" in "/opt/retropie/supplementary/". 
Now i want to call skyscraper from the console with the following commend:
`./Skyscraper -c "/opt/retropie/supplementary/skyscraper/config.ini" -p snes`

My config.ini looks like this:
#############
[main]
frontend="emulationstation"
threads="2"
lang="de"
region="eu"

[localDb]
covers="true"
screenshots="true"
wheels="true"
marquees="true"

[snes]
inputFolder="/home/pi/RetroPie/roms/snes"
gamelistFolder="/home/pi/test/roms/snes"
mediaFolder="/home/pi/test/roms/snes/media"
dbFolder="/home/pi/test/.skyscraper/dbs/snes"
importFolder="/home/pi/test/.skyscraper/import"
unpack="false"
emulator=""
videos="false"
brackets="true"
scraper="screenscraper"
userCreds="user:password"
minMatch="0"
threads="2"
pretend="false"
unattend="true"
unattendSkip="true"
interactive="false"
forceFilename="false"
verbose="true"
skipped="true"
artworkXml="/opt/retropie/supplementary/skyscraper/artwork-original.xml"
relativePaths="false"
#############

My "artwork-original.xml":
#############
```
<?xml version="1.0" encoding="UTF-8"?>
<artwork>
  <output type="screenshot" width="640" height="480">
    <layer resource="screenshot" x="20" width="520" height="390" align="center" valign="middle">
      <rounded radius="10"/>
      <stroke width="5"/>
    </layer>
    <layer resource="cover" height="250" x="0" y="-10" valign="bottom">
      <gamebox side="wheel" rotate="90"/>
      <shadow distance="5" softness="5" opacity="70"/>
    </layer>
    <layer resource="wheel" width="250" x="-10" align="right">
      <shadow distance="5" softness="5" opacity="70"/>
    </layer>
  </output>
</artwork> 
```
#############

im trying to create a PNG-File like you explained in your Youtube-Video and in your ARTWORK.MD.

This works good. But this part doesnt work at least:
#############
```
<layer resource="cover" height="250" x="0" y="-10" valign="bottom">
      <gamebox side="wheel" rotate="90"/>
      <shadow distance="5" softness="5" opacity="70"/>
</layer>
```
#############

It rotates the "cover"-Image. After that it doesnt create the "wheel" on the side. It also doesnt use files from the "recources"-folder. I tryed absolute and recursive paths.

I hope you are understanding the problem now.

**Comment by muldjord** [comment]
Please create all files in ```~/.skyscraper``` as mentioned in the documentation. If they are placed in the correct folders inside of ```~/.skyscraper``` (eg. ```~/.skyscraper/resources``` and ```~/.skyscraper/config.ini```) and are formatted correctly, it will work.

Concerning your config.ini, please remove all of the variables you don't need. You shouldn't have all of those variables and sections in there unless they aren't the default. For instance, the "[snes]" section you have in there has 'inputFolder="/home/pi/RetroPie/roms/snes"' which is already the default location. So you don't need those lines. They only contribute to bloating your settings. So basically ONLY enable the ones you specifically want to set, and remove the rest.

Concerning your artwork.xml, I see no errors in it, so it's probably because of where you have your files located or missing wheels for the games you are scraping. I assume you have an "output" node around the layer you posted.

**Comment by Flodding** [comment]
Got it working ... 

My fault was that I installed as "root" instead of "pi". Now works fine.

Is there a chance to use METADATA-Infos on the Screenshots like "Developer" or "Name" etc. ?
Didnt find anything in the documentation :(

**Comment by muldjord** [comment]
No, that is not currently possible. But it's an interesting idea. I'll add it to the roadmap. Gonna close this now.

**Comment by lars-goeran** [comment]
I have the same problem and have not found a solution yet. Everything works without problems, metadata, images and videos are downloaded and artwork is created. But only the the generation of the <gamebox> isn't working. As stated above, there is no wheel-image on the side of the gamebox.

For example, the following artwork.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<artwork>
  <output type="screenshot" width="640" height="480">
    <layer resource="cover" height="250" valign="top" align="center">
      <gamebox side="wheel" rotate="90"/>
    </layer>
    <layer resource="wheel" valign="bottom" align="center">
    </layer>
  </output>
</artwork>
```
The result image shows the rotated gamebox above and below the wheel image. The wheel image exists and is therefore used. But it's still missing on the side of the gamebox. I have no idea, whats wrong with my configuration.

I'm using the last git version of skyscraper on my ArchLinux system.

I have attached an example result.

![result](https://user-images.githubusercontent.com/32413991/70468041-a1e1d480-1ac6-11ea-86cc-23cbc98fc94d.png)

**Comment by muldjord** [comment]
I'm not sure what you did, but this works fine on my system and has always worked. I'm guessing it's something local on your end. Permissions, something like that.

**Comment by juliosueiras** [comment]
@lars-goeran is most likely (it doesn't prompt for error) that you are missing the "boxfront.png" and "boxside.png" in the resources folder
