### ISSUE TITLE
sym link for videos from cache

### ISSUE THREAD

**Issue by jonwaland** [muldjord/skyscraper#73]
Would it be possible (and sensible) to be able to create a symbolic link to the cached videos and images rather than duplicate them in the .emulationstation/downloaded_media directory?

(I accept this wont work for where artwork is created by merging multiple images)

**Comment by muldjord** [comment]
It's certainly possible for videos. Don't think it's worth the effort for images. But whether it's something I want to focus on is another thing. I don't have much time to work on Skyscraper at the moment and I have many features that I want in there.

**Comment by muldjord** [comment]
I've added it to the roadmap, so closing this. No promises though - I might remove it again at some point.
