### ISSUE TITLE
Allow ignoring specific media elements via local DB import

### ISSUE THREAD

**Issue by CookiePLMonster** [muldjord/skyscraper#74]
I realize the title is incredibly confusing, so I'll describe it basing on an example right away.

Imported DB entries may be treated as a kind of "I know better than any scraper" measure, allowing users to either add custom games (I used it successfully with romhacks, works great) or overwrite data from online scrapers. However, does it allow telling Skyscraper to **ignore** specific scraped elements, in this case graphical media?

Example:
Scraping `Steam.sh` yields a match with Steam Slug game, whereas it should naturally be Steam, as in Valve's client. Scraping yields game's name, screenshot and boxart (so Skyscraper bakes a 3d boxart out of it).

In the case of title, description and screenshot it can be trivially overriden by imported DB entries. The hard part is, what can be done with the boxart? Theoretically I could make it bake a fake-ish Steam boxart, but ideally I'd like it not to create a boxart for this at all, as if there was no matches on artwork used to bake such.

Is this possible currently? I'm not really interested in requesting it as a feature, since it's a terribly specific use case - but maybe it's possible to do right now.

**Comment by muldjord** [comment]
I would recommend simply editing the db.xml file for the specific platform/game (check the documentation of the "localdb" module) and remove the line with the boxart and wheel altogether. There is no easier way of doing this and I don't really have plans to implement such a feature.

**Comment by CookiePLMonster** [comment]
I see, that makes sense. Then the other idea I have about this - is it
possible to hint to Skyscraper what the game is? As far as I understand,
it's using probabilities of matches on sites (or is that scrapers doing
it?) so if there is a way to hint "this is game X, even though you think
it's Y" then it'd solve the issue, and potentially more similar issues like
this (different games under same name, like Prey on PC).

**Comment by muldjord** [comment]
When it's already in the cache, you need to remove it before you try anything else. Otherwise it'll just keep showing up. When you've removed it, check out the "--interactive" option and the "--query" option (as described here: https://github.com/muldjord/skyscraper/releases/tag/2.7.5). That might help you. I'm gonna close this now.
