### ISSUE TITLE
Symlinking rather than duplicating 

### ISSUE THREAD

**Issue by mettamatt** [muldjord/skyscraper#76]
What about symlinking assets from the cache database to the media folders rather than duplicating content? That would save on disk space, but make sharing cache databases more difficult.

**Comment by muldjord** [comment]
Just did a sanity check on this feature. It's more work than I realized. The thing is; I load the video data at one point, then do a bunch of other stuff, and then save the video data to the destination later on. At that point I don't know the source filename anymore, and I'm not sure I want to do a code rewrite just for this feature. So I'll leave it on the roadmap for now. But I might remove it again later.

**Comment by mettamatt** [comment]
It wasn't me but I appreciate you thinking this one through. It would particularly come in handy for video assets, and I also understand that the scraper wasn't designed this way. Regardless, skyscraper is a great piece of software!

**Comment by mgerhardy** [comment]
Please make this an optional feature. I'm sharing the dbs folder with a few guys and would like to keep the self-contained/shareable.

**Comment by muldjord** [comment]
It will absolutely be an optional feature. I would never make this the default behaviour.

**Comment by muldjord** [comment]
This feature is now implemented and will be in 2.9.2. It's enabled by either using the `--symlink` command line option or by setting the `symlink="true"` variable under either the `[main]` section or any platform section in config.ini.

**Comment by muldjord** [comment]
2.9.5 out now with the `--symlink` option implemented. :) Closing this.
