### ISSUE TITLE
Mobygames scraping for bigger directories

### ISSUE THREAD

**Issue by CookiePLMonster** [muldjord/skyscraper#78]
I was about to ask if it's possible to specify `startat` and `endat` without refreshing so it'd be easier to scrape from Mobygames with its 25 entries limit, but then I realized...

This limit is enforced on entire directories, even if in fact there's far less roms submitted for scraping! In the case where you have 25 games with entries in localdb and 5 new games, only 5 entries are submitted to Mobygames, yet the scraping request gets rejected by a hard limit of 25 roms!

Is this possible to improve? Of course, it can be worked around by moving roms around but there seems to be no reason to be forced to do that. If that was corrected, the only constraint would be that you cannot add more than 25 new/undetected entries to a directory when scraping with Mobygames. Much easier to enforce.

EDIT:
With a flood of tickets I'm sending lately I promise to contribute back somehow soon =)

EDIT2:
It would be even more user friendly if, instead of exiting, scraping bailed out when this limit is reached - and listed remaining roms in `skipped-mobygames.txt`. This way it would be circumvented by "just" kicking off scraping multiple times... unless it's exactly what you are trying to prevent.

**Comment by muldjord** [comment]
The 25 entry limit is one I've imposed. The key I have is for the ENTIRE Skyscraper user base. So if someone else is using it with Skyscraper, others won't be able to. So please don't try to circumvent that limit.

The Mobygames module is supposed to be used for a VERY few entries that other sources don't give good results for. Nothing else. And certainly not for scraping hundreds of roms.

I hope you understand the need for that limit.

**Comment by CookiePLMonster** [comment]
Of course, that makes perfect sense. However, my point partially stands - if localdb already has entries from Mobygames cached, then you're not making any requests for that rom again (unless of course `--refresh` is used) yet the limit is still in place. I'm fine with the limit, just not with the way it's "overprotective" atm.

**Comment by muldjord** [comment]
It is meant to do that. Otherwise you could just run the command again and again. If scraping from cache is your goal, you should use "-s localdb" instead.

**Comment by CookiePLMonster** [comment]
> Otherwise you could just run the command again and again.

Not if it bails out as soon as it finds that there are > 25 **uncached** roms, as opposed to bailing out as soon as it finds that there are > 25 roms.

**Comment by muldjord** [comment]
It doesn't know which roms are cached from the get-go, so this is no easy fix, and certainly not something I want to spend time on. :) I see what you mean, but I don't see a need to fix it as it is basically meant to be used for single games provided on command line. Any other use could / would bother other Skyscraper users who wish to use it.

**Comment by CookiePLMonster** [comment]
Fair enough!

The only problem is that RetroPie-Setup script makes this really non-obvious (it's listed like any other scraper), but this is of course not your fault.

**Comment by muldjord** [comment]
I agree. "mobygames" should be asked to be removed from the script. I'm gonna close this now.

EDIT: I've asked mitu to remove it.
