### ISSUE TITLE
Consider using alternative API for TGDB

### ISSUE THREAD

**Issue by terry-au** [muldjord/skyscraper#8]
TGDB exposes [PlatformGames](http://wiki.thegamesdb.net/index.php/PlatformGames) and [GetPlatformGames](http://wiki.thegamesdb.net/index.php/GetPlatformGames) which could allow for a great reduction in the number of searches performed on this scraper. The returned XML could be fuzzy matched against the file names within the input directory.

Additionally, the PlatformGames API also exposes a URL to the thumbnail (if there is one), so this could aid in determining whether or not a thumbnail exists for a given title.

**Comment by muldjord** [comment]
I am well aware of this. I have reasons to not use the suggested calls, even though I agree it would make sense if you wrote a TGDB only scraper.
