### ISSUE TITLE
Default priorities.xml alongside an example one

### ISSUE THREAD

**Issue by CookiePLMonster** [muldjord/skyscraper#82]
As seen in https://github.com/muldjord/skyscraper/issues/80#issuecomment-447565347, `priorities.xml` behaviour of treating an `.example` file as a default made me confused for a long while.

Let's go through an existing flow when you scrape any platform:

1. Skyscraper copies `priorities.xml.example` from its own directory to `dbs`, forcibly overwriting an already existing file. Therefore, this file should be considered read-only.
2. Skyscraper looks for `priorities.xml` in `dbs\platform`. If none is found, `dbs\priorities.xml.example` is copied there.

Basing on 2. you may think of `priorities.xml.example` as a default `priorities.xml`. However, this creates an issue if user wishes to modify those defaults, because as per 1. this file is not editable.

I propose modifying the flow so an editable default `priorities.xml` exists:

1. Skyscraper copies `priorities.xml.example` from its own directory to `dbs`, forcibly overwriting an already existing file. Therefore, this file should be considered read-only.
2. **Skyscraper looks for `priorities.xml` (or `priorities.xml.default` in `dbs`. If none is found, `dbs\priorities.xml.example` is copied there.**
3. Skyscraper looks for `priorities.xml` in `dbs\platform`. **If none is found, `dbs\priorities.xml` (or `priorities.xml.default`) is copied there.**

With this modification, you can define priorities for future platforms you may add. Right now, you are forced to keep track of what you're adding and modify accordingly.

**EDIT:**
**Additionally**, I suggest changing the wording around `priorities.xml`. Currently, Skyscraper claims to be looking for an "optional" file, but 2. is executed unconditionally so in practice it now **always** exists.

**Comment by muldjord** [comment]
Skyscraper will copy the priorities.xml.example if none exists already, to provide a starting point for the user. It's better than not having one to begin with, as it's quite important, for instance, that "import", "screenscraper" and "arcadebd" are relatively high up, as those are 100%'ers, meaning that they are based on non-search terms so with a high degree of certainty will give correct data.

I will consider the behaviour and might change it.

If you wish it to use the timestamps instead, just remove all entries from the nodes. I will edit the help text to avoid confusion.
