### ISSUE TITLE
--nobrackets also removes brackets from returned titles

### ISSUE THREAD

**Issue by CookiePLMonster** [muldjord/skyscraper#83]
Test case: `Gran Turismo 2 (Arcade).iso`

When Gran Turismo 2 Arcade disk is scraped from screenscraper, following title is returned and saved in localdb:
```xml
<resource sha1="7bf5fe0736330420facc181c9fbffdf163600de1" type="title" source="screenscraper" timestamp="1544879876698">Gran Turismo 2 (Arcade Mode)</resource>
```

When scraping from localdb without `--nobrackets`, all the info from ISO filename gets appended to the original name, so scraped name ends up being:
```xml
<name>Gran Turismo 2 (Arcade Mode)(Arcade)</name>
```

However, `--nobracket` not only strips brackets carried over from the filename, but also the ones returned from scraper data! Scrape again with `--nobrackets` and this title is saved instead:
```xml
<name>Gran Turismo 2</name>
```

I am not sure if it's intended, but feels like `--nobrackets` should only omit appending brackets from filenames, and not touch the ones returned from scrapers.

EDIT:
This behaviour will also make it unable to overload the name from a local import. I assume in this case "user knows better" and I should be even able to name my ROM `Game (XD) [!!@@] {namename!}` if I wish to.

**Comment by muldjord** [comment]
It's subjective and it's intended to be the way it is. It was actually the other way around some months ago, but the fact that it didn't give you control over the bracket notes in returned titles caused issues and users asked why it didn't remove them when they used --nobrackets. I like it how it is and will keep it like that.

Also, could you ask questions like this on the retropie forums instead? It's clearly not an issue as the help text clearly states "Disables any [] and () tags in the frontend game titles.". I'd rather have the opportunity to clear these questions up with informal chat, than have issues for every question. Thanks. :) Bugs and clear issues of course still welcome to be reported here.

**Comment by CookiePLMonster** [comment]
> Also, could you ask questions like this on the retropie forums instead?

Sure, I reported it as a bug for same reasons you changed the behaviour - I thought it's not intended.
