### ISSUE TITLE
Dreamcast CHD Scrapping

### ISSUE THREAD

**Issue by pmat1218** [muldjord/skyscraper#85]
**Describe the bug**
Fantastic scrapper and we all appreciate your hard-work.  Dreamcast system seems to be the only system i can't scrape.  I'm using CHD files with perfect names and (USA) prefix.  However skyscrapper can't seem to match the files with any scraping source.  Your scrapper is pretty good at finding roms so i didn't know if this was a bug.  It does see all the files just doesn't match anything for the dreamcast. I tried gdi versions but scrapper can't seem to find them if they are in subfolders.  cdi versions have the same problem CHD.  

**To Reproduce**
I ran the scrape through retropie setup menu under the experimental packages

**Special circumstances**
Is your system set up in any special manner that could interfere with how Skyscraper works?  No,  every other system was perfect.

**Terminal output**
Used RetroPie Setup menu to run the scrape after exiting emulation station

**Technical information**
 - Skyscraper version: 2.9.1
 - Internet connection: wifi
 - OS: Retropie
 - OS Version 4.4.4

**Additional context**
None- but please let me know if i can provide any additional information.

**Comment by muldjord** [comment]
Can you give me an exact example filename of one of your .chd files that won't work? That would help me in identifying the issue. Thanks.

**Comment by pmat1218** [comment]
Sure
4 Wheel Thunder (USA).chd
4X4 EVO (USA).chd
18 Wheeler - American Pro Trucker (USA).chd
102 - Dalmatians - Puppies to the Rescue (USA).chd
Aerowings (USA).chd
AeroWings 2 - Airstrike (USA).chd
Airforce Delta (USA).chd

Let me know if you need more

**Comment by muldjord** [comment]
I think I know what the issue might be for you. I created an empty file called "4 Wheel Thunder (USA).chd" in my dreamcast rom folder and scraped it with the "thegamesdb" scraping module. And that worked just fine giving me the result for "4 Wheel Thunder". But if you've been using the "thegamesdb" source a lot, then you've run out of requests for this month, so it won't work for you until next month. It has a 1000 requests per month limit.

Have you tried manually looking up the crc32, md5 or sha1 checksums in the screenscraper.fr database? It might be that they simply don't have the games. They are largely focused on retro consoles.

**Comment by muldjord** [comment]
Ah, yes! That is the problem then. If you've converted them yourself, they won't be picked up in the "screenscraper" database. They only have "well-known" checksums in their database. And if you've also renamed them yourself, then it won't match per filename either.
I'm a little confused why you say it doesn't fint the .gdi folder in subfolders. It should. Can you give me an example of a filename for one of your .gdi's?

**Comment by pmat1218** [comment]
Sure,  for some reason skyscraper won't see them
roms/dreamcast/AeroWings v1.002 (1999)(Crave)(NTSC)(US)[!]/AeroWings v1.002 (1999)(Crave)(NTSC)(US)[!].gdi

Also in that subfolder are the tracks with bin and raw extesions. I can always edit the gamelist.xml if i can get the scrape.

**Comment by muldjord** [comment]
That's odd, it works just fine for me. I created an empty file called "roms/dreamcast/AeroWings v1.002 (1999)(Crave)(NTSC)(US)[!]/AeroWings v1.002 (1999)(Crave)(NTSC)(US)[!].gdi". Which means the filename is a match inside of "screenscraper". Might be related to some of the command line parameters the RetroPie script uses then (I always run Skyscraper from command line for better control). Not sure. Please be sure to have the "refresh" enabled in the menu.

**Comment by pmat1218** [comment]
Okay I'll do that,  I'll also try giving a shot using the command line and report back.

**Comment by muldjord** [comment]
This is the command I used for reference "Skyscraper -p dreamcast -s screenscraper --refresh"

**Comment by pmat1218** [comment]
Hi Muldjord, i got it.  thank you so much! You are the man!
