### ISSUE TITLE
Snes scraping and mgd extension

### ISSUE THREAD

**Issue by slolo2000** [muldjord/skyscraper#86]
Hello,

It seems that skyscraper does not detect file with mgd extension in snes folder.
The same filename with sfc extension is detected and scraped correctly.

Can you confirm this problem?

Version of skyscraper used: 2.9.1 on Retropie 4.4 with all up to date.

**Comment by muldjord** [comment]
That is correct. I've added it and it will be in 2.9.2 when it's released. Until then you can manually add it with the `--allowext *.mgd` option.
