### ISSUE TITLE
Ability to strip region codes from game titles

### ISSUE THREAD

**Issue by terry-au** [muldjord/skyscraper#9]
I'm considering implementing functionality to strip region names from game titles in hopes that it may improve accuracy. How feasible/worthwhile would this endeavour be?

For example:

Adventures of Dr. Franken, The (Europe) (En,Fr,De,Es,It,Nl,Sv)

Could be translated to:
Adventures of Dr. Franken, The (Europe)

Or:
Adventures of Dr. Franken, The

Or perhaps even (if we were to detect the presence of ", The" succeeding all else but region/language tags:
The Adventures of Dr. Franken

**Comment by muldjord** [comment]
This would have no effect at all. I already strip everything in brackets and parentheses. I also look for "the" and strip it away to see if it gives a better fit.
