### ISSUE TITLE
Scraping TI-99/4A roms

### ISSUE THREAD

**Issue by jhbeskow** [muldjord/skyscraper#90]
I am running Skyscraper with great results for every other platform except the TI-99/4A.  When I run it for any of the sources (including local import) for this system, it returns immediately and says scraping complete.  I believe this is because it does not recognize the "platform" for this system.  I know that the default RetroPie scraper does not seem to see the platform for the system, either.  (i.e. "Warning: some of your selected systems do not have a platform set. Results may be even more inaccurate than usual!  Continue anyway?") 

Do you pull your platform value from the same place?  If so, is there anything I can update to force skyscraper to recognize this platform?  If I am out of luck, I completely understand. :-D

**Comment by muldjord** [comment]
Your roms for this system are .ctg or .zip files, right?

**Comment by jhbeskow** [comment]
.ctg only.  It uses the ti99sim in the experimental packages, which only accepts .ctg.

**Comment by muldjord** [comment]
Great, I've implemented it now. Will be in 2.9.2. :)

**Comment by jhbeskow** [comment]
Thank you!

**Comment by muldjord** [comment]
You're welcome!

**Comment by muldjord** [comment]
Btw, could you provide me with a filename (just the name, not the rom itself) of a couple of your roms? Just need something to test it with.

**Comment by jhbeskow** [comment]
Yeah, I found a bunch of them online.  The filenames suck, so I need to rename them.  I don't think I will ever make them match ScreenScraper, but MobyGames and TheGamesDB.net might work alright after a rename



[ti99.zip](https://github.com/muldjord/skyscraper/files/2700623/ti99.zip)

.

**Comment by muldjord** [comment]
Thank you, but I deleted your post. I don't (and github don't) allow roms on here, just need the filenames. :)

**Comment by jhbeskow** [comment]
OH!  Oops.  Sorry.

advture.ctg
alpiner.ctg
Burgertime.ctg
centipe.ctg
computerwar.ctg
digdug.ctg
donkey.ctg

Like I said...terrible.

**Comment by muldjord** [comment]
Hm, yeah. They might pose a problem then. Usually with files that don't have spaces in them they are at least capitalized like "GameName" but these aren't. So I can't even add the spaces by looking for capital letters. But I'm pretty sure it'll work if you rename them to have spaced or underscores so it's either "game name" or "game_name".

**Comment by muldjord** [comment]
Just tried renaming those and it found all of them with the "thegamesdb" module. So it's looking pretty good. :)

**Comment by jhbeskow** [comment]
Awesome!  Thank you!  Yes, I plan on renaming if they will work.  I have no issue with renaming 25 files.  I can fill in some of the extra media.  It's just the textual stuff that is tough to do by hand.

**Comment by jhbeskow** [comment]
I just wanted to add that this is fantastic work. Thank you for providing it. It's easily the best scraper I've used.

**Comment by muldjord** [comment]
Thank you, I appeciate that :)

**Comment by muldjord** [comment]
2.9.5 is out now, with the `ti99` platform enabled. :) Have fun!

**Comment by jhbeskow** [comment]
Thank you!!!
