### ISSUE TITLE
OpenRetro Lookup Often Fails

### ISSUE THREAD

**Issue by Enverex** [muldjord/skyscraper#91]
**Describe the bug**
Scanning an Amiga collection (of LHA WHDLoad games) against OpenRetro results in many games not being identified despite their names matching exactly. Not everything is failing, just a good amount of them.

**To Reproduce**
Scan WHDLoad Amiga games against OpenRetro (not sure how relevant it is that it's WHDLoad files).

**Terminal output**
Example failures (these were all in a row, yet all exist on the site with these names if you search for them):
```
#343/2212 (T1) Pass 1 Pass 2 ---- Game 'Chaos In Andromeda - Eyes Of The Eagle' not found :( ----


218/125/343
Elapsed time   : 00:08:02
Est. time left : 00:43:47

#344/2212 (T1) Pass 1 Pass 2 ---- Game 'Chaos Strikes Back' not found :( ----


218/126/344
Elapsed time   : 00:08:02
Est. time left : 00:43:38

#345/2212 (T1) Pass 1 Pass 2 ---- Game 'Charlie J. Cool' not found :( ----


218/127/345
Elapsed time   : 00:08:02
Est. time left : 00:43:31

#346/2212 (T1) Pass 1 Pass 2 ---- Game 'Chase HQ II - Special Criminal Investigation' not found :( ----


218/128/346
Elapsed time   : 00:08:02
Est. time left : 00:43:22
```

**Technical information**
 - Skyscraper version: v2.9.5
 - Internet connection: VDSL
 - OS: Arch Linux x86_64
 - OS Version: N/A

**Additional context**
I'm not sure if hashes are used for these games rather than names, but even if that's the case, these are the RetroPlay files and thus are basically the authoritative versions (but if that's the case, it's an OpenRetro issue unless SkyScraper can fall back to name matching).

Let me know if you need any more info.

**Comment by muldjord** [comment]
Yes, this is unfortunately a restriction in the openretro site. This happens in the 2nd pass, which is a search based pass used in cases where uuid's don't exist (1st pass) in OpenRetro for the current file. They currently have a "2 word search limit" applied due to high server loads. So this is not a Skyscraper issue, but an openretro issue. I'll leave this open for a while in case others wonder about this.

**Comment by muldjord** [comment]
It's complicated. :D It uses hashes for lha files but not for all other files. And the hashes aren't checksums but rather uuid's of the openretro game url's that have been compiled by some of the good people I work with behind the scenes in regards to the openretro module. :)

`unpack` is only supported by the `screenscraper` module.

**Comment by otherguy** [comment]
@muldjord ah, that makes sense. Thanks for the explanation!

**Comment by muldjord** [comment]
3.0.0 now out where I've "fixed" this issue. It will now cut any game search for OpenRetro down to just two words. This ensures that all searches work, but they might provide some pretty lousy results. But it's a definite improvement over 2.9.5's version of handling it (which it didn't). Closing this now.

**Comment by otherguy** [comment]
@muldjord congrats on releasing 3.0! 🎉

**Comment by muldjord** [comment]
Thanks! :)
