### ISSUE TITLE
Textual game description import

### ISSUE THREAD

**Issue by scthirouin** [muldjord/skyscraper#93]
Just wondering if there was any way to format the description in imported textual files to have line breaks. I have looked and tried everything to my limited knowledge and can’t replicate what can be scraped normally. Thanks for any advice, and Skyscraper is my new go-to scraper. Excellent work!

**Comment by muldjord** [comment]
Just looked over the code and it's actually not possible to do so at the moment. I've just added the option to add "\n" to the lines which will then convert to newlines. It will be in the next release. :)

Happy new year!

**Comment by scthirouin** [comment]
Thanks for the quick reply. I know it’s not a huge issue, but thanks for addressing it. Looking forward to future updates. Your scraper surpasses all the other I’ve used. Thanks for all your hard work!
