### ISSUE TITLE
_q_startOperation was called more than once

### ISSUE THREAD

**Issue by otherguy** [muldjord/skyscraper#95]
When running `skyscraper`, I sometimes get the message:

```
DEBUG: 'QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://openretro.org/browse?q=007+the+world+is+not+enough&unpublished=1")
```

This does not affect the operation of `skyscraper` but is likely worth mentioning for you.

**Comment by muldjord** [comment]
Thanks for notifying me. I've never seen this myself and it seems to be connected to how the OS itself handles network connections (I've only spend 2 minutes looking into this so I might be misunderstanding what people write, but that's what I get from it). It is benign and not something I can fix: https://forum.qt.io/topic/15069/qnetworkreplyimpl-_q_startoperation-was-called-more-than-once/3

If you find out more than that please let me know.

**Comment by otherguy** [comment]
@muldjord true, seems to be related to QT. Maybe up the default log level to `INFO`, though?

**Comment by muldjord** [comment]
Nah, I'd like to know if these things happen. And it would seem that this is related to your particular system. I haven't had it reported before by anyone else.

**Comment by otherguy** [comment]
@muldjord macOS Mojave and QT installed through homebrew, albeit prior to the mojave upgrade. It might be that I can get rid of it by recompiling QT now.
