### ISSUE TITLE
Unexpected release date format for EmulationStation (from ScreenScraper, at least)

### ISSUE THREAD

**Issue by michaelbaudino** [muldjord/skyscraper#98]
**Describe the bug**
Data scraped from ScreenScraper and output in EmulationStation `gamelist.xml` format seems to have release dates in an unexpected format.

EmulationStation expects a date (a timestamp, actually) in the format `%Y%m%dT%H%M%S%F%q`, but the `gamelist.xml` generated by Skyscraper contains release dates in the format `%Y%m%d` (only the date is present, the time is missing, as well as the `T` character to separate them). See EmulationStation [official reference for `gamelist.xml`](https://github.com/Aloshi/EmulationStation/blob/master/GAMELISTS.md#reference).

I did not try with other data sources than ScreenScraper.

**To Reproduce**
I scrape a collection of SNES roms with the exact following command (only credentials are redacted):

```
Skyscraper \
  -p snes \
  -s screenscraper \
  -u LOGIN:PASSWORD \
  -i /mnt/RECALBOX_DATA/recalbox/roms/snes/ \
  --unpack \
  -t 8 \
  -f emulationstation \
  --lang fr \
  --region eu \
  --unattend \
  --relative
```

**Terminal output**
No terminal output, unfortunately, but EmulationStation (embedded in RecalBox) outputs (well, displays) "Unknown" as release date for all the roms.

When I manually append `T000000` to a release date in `gamelist.xml`, EmulationStation properly displays it.

**Technical information**
 - Skyscraper version: 1.9.5
 - Internet connection: adsl
 - OS: LinuxMint 18.3 (based on Ubuntu Xenial)
 - Installed following the [README instructions](https://github.com/muldjord/skyscraper#download-compile-and-install)

**Additional context**
I'm running Skyscraper from my LinuxMint laptop but running EmulationStation as embedded in RecalBox on a Raspberry Pi 3b+. Not sure if it is relevant or not.

**Comment by muldjord** [comment]
Interesting, I'll need to look into this again (obviously I've looked into it before and fixed it, but maybe they changed something). I can easily add the T000000 by default.

**Comment by michaelbaudino** [comment]
That would be awesome :100:
