### ISSUE TITLE
Any plans for output to HyperSpin db format?

### ISSUE THREAD

**Issue by Shawson** [muldjord/skyscraper#99]
**Describe the feature**
An additional front end output parameter to export to HyperSpin db format

**Contact mails and documentation**
hyperspin list site has lots of example xml's- the format is not dissimilar to the gamelist.xml files that emulationstation uses- i wrote a powershell script converts gamelist.xml files into hyperspin format.  Here's a snippet as an example;
```
<?xml version="1.0"?>
<menu>
	<header>
		<listname>Nintendo Entertainment System</listname>
		<lastlistupdate>03/07/2016</lastlistupdate>
		<listversion>1.3</listversion>
		<exporterversion>HyperList XML Exporter Version 1.3 Copywrite (c) 2009-2011 William Strong</exporterversion>
	</header>
	<game name="10-Yard Fight (USA, Europe)" index="true" image="1">
		<description>10-Yard Fight (USA, Europe)</description>
		<cloneof></cloneof>
		<crc>C38B62CB</crc>
		<manufacturer>Nintendo</manufacturer>
		<year>1985</year>
		<genre>Sports/Football</genre>
		<rating>Other - NR (Not Rated)</rating>
		<enabled>Yes</enabled>
	</game>
```

**Additional context**
none

**Comment by muldjord** [comment]
I'd love to hear if there are others who are interested in this. Skyscraper doesn't support Windows officially so I'm wondering how much of a niche this request is. I'm not opposed to making it happen though. And, as you mention, it doesn't seem to be a huge task to implement as it's already very similar to ES game lists.

One note though, I do feel like it's unfortunate that Hyperspin is seemingly closed source.

**Comment by Shawson** [comment]
Good point- perhaps this is kind of an edge case!
